"""Amazon rank-and-convert layer. Listing-side only. Covers/interiors unchanged.

Title stays GLP-1 (safer than a brand). Backend keywords and the first line of
the description speak the queries people actually type. Also-bought paths are
printed so one sale trains the catalog instead of a pile of orphans.
"""

from __future__ import annotations

# Seven backend keywords each. Unique across the 36. No trademark-as-title.
# Mix: (1) exact query (2) mechanism (3) adjacent high-volume (4) undated/gift.
KEYWORDS = {
    "01": [
        "glp-1 meal journal",
        "semaglutide food diary",
        "protein fiber tracker undated",
        "hunger scale notebook",
        "satiety log book",
        "weight loss meal tracker",
        "injection day food journal",
    ],
    "02": [
        "glp-1 side effect tracker",
        "semaglutide symptom diary",
        "nausea constipation log",
        "weekly severity grid journal",
        "clinic visit prep notebook",
        "injection site symptom log",
        "undated gi side effect diary",
    ],
    "03": [
        "weight loss plateau journal",
        "glp-1 30 day challenge",
        "plateau breaker habit tracker",
        "undated challenge planner",
        "protein habit grid book",
        "mindset prompt journal women",
        "encore cycle planner",
    ],
    "04": [
        "weight maintenance journal",
        "glp-1 maintenance tracker",
        "range band weight log",
        "refill reminder notebook",
        "post shot maintenance diary",
        "12 month health tracker",
        "relapse prevention journal",
    ],
    "05": [
        "craving tracker journal",
        "glp-1 hunger log",
        "emotional eating diary undated",
        "what i did instead notebook",
        "appetite awareness journal",
        "90 day craving log",
        "mood food tracker",
    ],
    "06": [
        "glp-1 workout log",
        "strength training while losing",
        "step tracker journal undated",
        "muscle preservation log book",
        "rpe fitness notebook",
        "walking habit tracker",
        "recovery lifting diary",
    ],
    "07": [
        "glp-1 titration log",
        "pocket injection notebook",
        "dose as prescribed journal",
        "pen refill tracker 5x8",
        "weekly shot date log",
        "semaglutide dose notebook",
        "undated med pocket log",
    ],
    "08": [
        "non scale victory journal",
        "glp-1 gratitude journal",
        "clothing fit tracker",
        "body kindness diary women",
        "undated nsv notebook",
        "weight loss mindset journal",
        "120 day gratitude log",
    ],
    "09": [
        "glp-1 injection calendar",
        "sticker shot planner 8.5x11",
        "site rotation tracker book",
        "weekly injection log calendar",
        "undated med calendar",
        "semaglutide sticker journal",
        "refill reminder calendar",
    ],
    "10": [
        "sober curious journal",
        "90 day sober tracker",
        "alcohol craving log undated",
        "dry january journal",
        "gender neutral recovery notebook",
        "sober october diary",
        "not 12 step journal",
    ],
    "11": [
        "intermittent fasting log",
        "16 8 fasting tracker",
        "fasting window journal",
        "24 hour timeline food diary",
        "time restricted eating log",
        "12 week if notebook",
        "undated fasting tracker",
    ],
    "12": [
        "migraine tracker journal",
        "headache weather diary",
        "barometric pressure log",
        "aura symptom notebook",
        "pain map headache journal",
        "undated migraine log",
        "trigger diary for migraines",
    ],
    "13": [
        "adhd medication log book",
        "stimulant dose as prescribed",
        "pomodoro focus tracker",
        "adhd daily focus boxes",
        "wear off crash journal",
        "undated adhd med notebook",
        "copy the bottle log",
    ],
    "14": [
        "hot flash tracker journal",
        "sleep wheel peri chart",
        "night sweat log book",
        "cycle timeline notebook",
        "peri symptom tally journal",
        "undated hot flash diary",
        "clinic questions peri log",
    ],
    "15": [
        "low fodmap food diary",
        "ibs symptom tracker journal",
        "bristol stool log book",
        "elimination diet notebook",
        "gut latency food journal",
        "reintroduction food cards",
        "undated fodmap diary",
    ],
    "16": [
        "screen time journal 30 day",
        "phone habit tracker workbook",
        "digital wellbeing log",
        "real world substitution journal",
        "attention journal undated",
        "social media hours tracker",
        "unplug 30 day notebook",
    ],
    "17": [
        "postpartum recovery journal",
        "pelvic floor pt homework log",
        "c section recovery tracker",
        "12 week new mom planner",
        "assigned homework notebook",
        "undated postpartum log",
        "stitches incision care diary",
    ],
    "18": [
        "spoon theory journal",
        "autoimmune flare tracker",
        "chronic illness energy log",
        "fatigue pain grid notebook",
        "undated flare diary",
        "medication as prescribed log",
        "immune symptom journal",
    ],
    "19": [
        "high protein grocery planner",
        "glp-1 meal prep journal",
        "batch cooking log book",
        "fridge map leftover tracker",
        "12 week shopping list book",
        "semaglutide grocery planner",
        "undated protein meal prep",
    ],
    "20": [
        "restaurant food diary undated",
        "eating out journal glp-1",
        "travel meal log book",
        "usual order cards notebook",
        "social event food tracker",
        "trip kit health journal",
        "dining out fullness log",
    ],
    "21": [
        "body measurement journal inches",
        "clothing size log book",
        "progress photo tracker undated",
        "lab results copy sheets",
        "waist hip notebook",
        "glp-1 progress binder",
        "12 month measurement diary",
    ],
    "22": [
        "bristol stool diary glp-1",
        "constipation tracker journal",
        "hydration log book undated",
        "sleep bowel water companion",
        "90 day bathroom diary",
        "semaglutide gi companion",
        "water intake tally journal",
    ],
    "23": [
        "body image journal 90 day",
        "changing body prompt journal",
        "self compassion notebook undated",
        "weight loss feelings diary",
        "unique prompts no repeats",
        "glp-1 mindset journal",
        "body truce practice book",
    ],
    "24": [
        "clinic visit journal 52 week",
        "one page doctor brief",
        "weekly health review notebook",
        "patient appointment notes",
        "glp-1 weekly log book",
        "undated medical visit journal",
        "clinician handoff notebook",
    ],
    "25": [
        "injection day pocket journal",
        "0 48 hour shot log",
        "glp-1 shot day notebook",
        "5x8 side effect diary",
        "next 48 hours tracker",
        "weekly injection pocket log",
        "undated shot notebook 5x8",
    ],
    "26": [
        "what sat well recipe log",
        "protein leftover journal",
        "blank recipe cards protein",
        "glp-1 kitchen notebook",
        "make again retire cards",
        "undated recipe log book",
        "meal prep leftover tracker",
    ],
    "27": [
        "glp-1 five minute journal",
        "compact daily shot log",
        "short morning pages undated",
        "120 day one sentence diary",
        "minimalist glp-1 tracker",
        "quick protein daily log",
        "people who wont fill a spread",
    ],
    "28": [
        "anxiety journal unique prompts",
        "panic sensation log undated",
        "body first anxiety notebook",
        "peak and pass tracker",
        "90 day panic diary",
        "therapist homework journal",
        "worry loop checkbox log",
    ],
    "29": [
        "waso sleep diary journal",
        "clinical sleep log 12 week",
        "sleep latency tracker",
        "wind down checkbox diary",
        "insomnia tracking notebook",
        "rise time sleep journal",
        "undated sleep window log",
    ],
    "30": [
        "pmdd tracker journal",
        "luteal phase mood chart",
        "6 cycle daily mood log",
        "premenstrual irritability diary",
        "hormone mood notebook undated",
        "pmdd symptom severity log",
        "flag day cycle journal",
    ],
    "31": [
        "blood sugar log book undated",
        "cgm companion journal",
        "glucose meal timing diary",
        "meter reading copy sheets",
        "90 day diabetes tracker",
        "not a dosing protocol log",
        "undated glucose notebook",
    ],
    "32": [
        "chronic pain body map",
        "flare tracker diary undated",
        "pain function log book",
        "front back pain journal",
        "monthly pain dashboard",
        "chronic illness flare notebook",
        "72 flare pages diary",
    ],
    "33": [
        "grief journal 90 day",
        "bereavement prompts no stages",
        "gender neutral grief diary",
        "loss writing prompts unique",
        "mourning journal undated",
        "no silver lining grief book",
        "memorial writing notebook",
    ],
    "34": [
        "habit contract journal 12 week",
        "minimum viable habit tracker",
        "identity habit notebook",
        "bad day minimum log",
        "undated habit operating system",
        "weekly behavior contract",
        "environment design journal",
    ],
    "35": [
        "burnout journal knowledge work",
        "energy budget notebook",
        "meeting cost tracker",
        "resentment signal diary",
        "12 week burnout log",
        "decline delegate journal",
        "undated recovery from hustle",
    ],
    "36": [
        "3 day bladder diary",
        "voiding log book clinic",
        "urgency leak pad tracker",
        "pelvic symptom diary undated",
        "drink void diary 16 blocks",
        "urogynecology notebook",
        "bladder diary for appointment",
    ],
}

# First sentence Amazon indexes. Mechanism, not poetry.
HOOKS = {
    "01": "Two-page daily spreads for protein, fiber, hunger, and injection timing — eight undated weeks.",
    "02": "36 weekly 0–5 symptom grids plus a clinic visit-prep page every four weeks.",
    "03": "Thirty two-page challenge days, a unique prompt each day, then thirty encore pages.",
    "04": "Twelve months of an agreed range band, refill logistics, and relapse-risk — not a daily trial.",
    "05": "Ninety four-quadrant days: mood, craving intensity, what I did instead, a small reward.",
    "06": "32 weeks of strength vs cardio/steps, RPE, recovery — built for muscle while the scale moves.",
    "07": "Pocket 5×8. Copy the dose you were prescribed. Date it. 52 weeks. Never invent a number.",
    "08": "120 days, half gratitude, half non-scale victory. Quiet evidence the scale is too crude to see.",
    "09": "8.5×11 undated sticker calendars, site map, refill pages. White paper so vinyl actually sticks.",
    "10": "Ninety honest days. Trigger, craving slider, gratitude. Gender-neutral. Not 12-step branded.",
    "11": "Shade the hours you actually fasted on a 24-hour bar. 12 weeks. 16:8, 18:6, or custom.",
    "12": "72 episode pages with head maps, weather, aura lists, plus 12 monthly dashboards.",
    "13": "Copy the bottle. Pomodoro boxes for blocks you started. Wear-off line. Not a dopamine menu.",
    "14": "Tally marks for flashes and night sweats, a 1–5 sleep wheel, a chaotic-cycle timeline.",
    "15": "Eight weeks of meals, latency, Bristol 1–7, and 12 reintroduction cards you fill from your plan.",
    "16": "Copy hours from Screen Time. Name the trigger. Tick a real-world swap. 30 days + coda.",
    "17": "Track the pelvic-floor homework your PT assigned — nothing extra, no QR workouts.",
    "18": "90 spoon-budget days, 0–5 grids, meds copied from the label. Flares as weather, not failure.",
    "19": "12 weeks of protein-first shopping lists, batch-cook logs, fridge maps, leftover days.",
    "20": "Usual-order cards, 60 eating-out pages, 12 trip kits. How it sat — not a restaurant ranking.",
    "21": "A quiet 12-month binder: inches, clothing, optional photos, blank lab copy sheets. Skip any metric.",
    "22": "90 days of the unglamorous trio — sleep, Bristol, water — that decides if a week feels human.",
    "23": "90 unique prompts. None repeated. A truce practice for a changing body, not a glow-up packet.",
    "24": "52 weeks: signals on the left, a 90-second clinician brief on the right. Hand it over.",
    "25": "Pocket 5×8. Shot day + the next 48 hours. 36 cycles. How it actually went.",
    "26": "60 cards you write: name, protein, how it sat, make-again or retire. 30 leftover logs. Not a cookbook.",
    "27": "120 compact days for people who will not fill a spread. Shot, protein, one sentence, done.",
    "28": "90 unique prompts. Sensation first, story second. Peak-and-pass timing. Not a protocol.",
    "29": "Classic clinician fields: bed, latency, WASO, rise, wind-down. 12 weeks. Tracking only.",
    "30": "Six undated cycles, 28 daily pages each. Mood, irritability, luteal flags. 188 pages. Bring two cycles.",
    "31": "90 days to copy meter or CGM readings and meal context. Targets blank on purpose. Not a dosing book.",
    "32": "72 flare pages with front/back maps, plus 12 monthly function dashboards.",
    "33": "90 unique prompts. No stages, no timeline, no silver lining required. Gender-neutral.",
    "34": "At most three habits. A minimum version for loud days. Weekly contracts. Not a 75-day clone.",
    "35": "12 weeks for knowledge-work humans: meeting cost, recovery, resentment, the decline page.",
    "36": "16 three-day voiding diaries in the format clinics ask for: drink, void, urgency, leak, pad.",
}

# One sale should train the next. Printed in every listing.
ALSO = {
    "01": ["05 Hunger & Craving", "09 Injection Calendar", "19 Protein Grocery"],
    "02": ["22 Sleep / Bowel / Water", "25 Shot-Day 0–48h", "24 Clinic Brief"],
    "03": ["01 Meal & Satiety", "08 NSV Gratitude", "06 Muscle companion"],
    "04": ["01 Meal & Satiety", "21 Progress binder", "24 Clinic Brief"],
    "05": ["01 Meal & Satiety", "23 Body Image", "08 NSV"],
    "06": ["01 Meal & Satiety", "03 Plateau-Breaker", "19 Protein Grocery"],
    "07": ["09 Injection Calendar", "25 Shot-Day pocket", "01 Meal & Satiety"],
    "08": ["01 Meal & Satiety", "23 Body Image", "05 Craving"],
    "09": ["07 Titration pocket", "25 Shot-Day 0–48h", "01 Meal & Satiety"],
    "10": ["28 Anxiety & Panic", "05 Craving (same skill, different substance)"],
    "11": ["01 Meal & Satiety", "05 Hunger log"],
    "12": ["32 Chronic Pain maps", "29 Sleep Window"],
    "13": ["34 Habit OS", "16 Digital Detox — this is dose-as-Rx, not a dopamine menu"],
    "14": ["30 PMDD 6-cycle (deeper)", "29 Sleep Window — this is tallies + sleep wheel, not a peri memoir"],
    "15": ["22 Sleep / Bowel / Water", "31 Glucose"],
    "16": ["34 Habit OS", "35 Burnout"],
    "17": ["36 Bladder / pelvic diary", "14 Hot-flash chart"],
    "18": ["32 Chronic Pain", "24 Clinic Brief"],
    "19": ["01 Meal & Satiety", "26 What-Sat-Well cards", "06 Muscle"],
    "20": ["01 Meal & Satiety", "19 Grocery & Prep"],
    "21": ["04 Maintenance", "08 NSV", "01 Meal & Satiety"],
    "22": ["02 Side-Effect Diary", "01 Meal & Satiety"],
    "23": ["08 NSV Gratitude", "05 Craving", "01 Meal"],
    "24": ["02 Side effects", "01 Meal", "09 Calendar"],
    "25": ["09 Calendar", "07 Titration", "02 Side effects"],
    "26": ["19 Grocery & Prep", "01 Meal & Satiety"],
    "27": ["01 Meal (if you will fill a spread)", "09 Calendar"],
    "28": ["33 Grief", "35 Burnout"],
    "29": ["22 Sleep / Bowel / Water", "12 Migraine — this is WASO fields, not a 3 a.m. prompt journal"],
    "30": ["14 Hot-flash tally chart", "31 Glucose"],
    "31": ["15 FODMAP", "01 Meal & Satiety"],
    "32": ["18 Autoimmune spoons", "12 Migraine maps"],
    "33": ["28 Anxiety", "08 NSV (different job)"],
    "34": ["03 Plateau-Breaker", "16 Digital Detox"],
    "35": ["34 Habit OS", "16 Digital Detox", "28 Anxiety"],
    "36": ["17 Postpartum PT homework", "14 Hot-flash chart"],
}

# Cashflow waves — do not ads-blast 36.
WAVES = [
    ("Wave 1 — cash", ["01", "09", "05", "30", "10", "12"],
     "Highest search × conversion. Ads live here. $9.99. Proof 01, 07, 09 trims first."),
    ("Wave 2 — also-bought", ["02", "19", "08", "25", "07", "24", "22"],
     "Ride Wave 1 traffic. No ads until 01/09 have 10+ reviews."),
    ("Wave 3 — companions", ["03", "06", "23", "27", "20", "11", "15", "18"],
     "Series page + backend. Let also-bought do the work."),
    ("Wave 4 — deep / quiet", ["04", "21", "26", "14", "13", "16", "17", "28", "29", "31", "32", "33", "34", "35", "36"],
     "Publish so the catalog is complete. Do not ads. 13/14/29 stay off Quiet Mind queries."),
]

def assert_unique() -> None:
    seen: dict[str, str] = {}
    errors = []
    for n, kws in KEYWORDS.items():
        if len(kws) != 7:
            errors.append(f"{n}: {len(kws)} keywords")
        for w in kws:
            key = w.lower().strip()
            if key in seen:
                errors.append(f"dup '{w}' ({seen[key]} & {n})")
            seen[key] = n
        if n not in HOOKS or n not in ALSO:
            errors.append(f"{n} missing hook/also")
    expected = {f"{i:02d}" for i in range(1, 37)}
    if set(KEYWORDS) != expected:
        errors.append(f"KEYWORDS keys {sorted(set(KEYWORDS)^expected)}")
    if errors:
        raise SystemError("algorithm keyword guard: " + "; ".join(errors))


# Quiet Mind (ADHD-Journals) owns these queries. Do not bid.
LEAVE_FOR_QMP = [
    "dopamine menu",
    "75 soft journal",
    "somatic journal",
    "3am journal / night pages",
    "perimenopause journal (memoir/clinic-file) — we sell the tally chart instead",
    "cozy coloring / celestial / tidal / botanical",
]
