"""Volume 2 titles 19–36 — premium companions."""

TITLES_VOL2 = [
    dict(n="19", file_interior="19_GLP1_Protein_Grocery_and_Prep_Planner_6x9.pdf", stem="19_GLP1_Protein_Grocery",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  19",
         cover_title="High-Protein\nGrocery & Prep", cover_title_one="High-Protein Grocery & Prep",
         subtitle="Twelve weeks of shopping lists,\nbatch-cook logs, and fridge maps",
         spine="Protein Grocery & Prep", kdp_title="GLP-1 High-Protein Grocery & Meal Prep Planner",
         kdp_subtitle="12-Week Shopping Lists, Batch-Cook Logs & Fridge Maps (Undated)",
         tagline="Twelve undated weeks  ·  6 × 9 in", pages=136, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.78, 0.84, 0.76), ink=(0.14, 0.22, 0.16), panel=(0.93, 0.95, 0.91),
         bullets=["Weekly shop lists by protein / produce / extras", "Prep-session log and fridge map", "Seven daily leftover pages per week", "Clinic brief if nutrition comes up"],
         keywords=["protein meal prep planner", "glp-1 grocery list", "batch cooking journal", "high protein shopping list", "fridge leftover log", "12 week meal prep", "undated grocery planner"],
         bisac=["HEA017000", "HEA019000"], bisac_names=["HEALTH & FITNESS / Diet & Nutrition / Food Content Guides", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"], price=9.99, qr=None),
    dict(n="20", file_interior="20_GLP1_Restaurant_Travel_and_Social_Log_6x9.pdf", stem="20_GLP1_Out_and_About",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  20",
         cover_title="Restaurant,\nTravel & Social", cover_title_one="Restaurant, Travel & Social Log",
         subtitle="Sixty event pages, trip kits,\nand 'my usual order' cards",
         spine="Out & About Log", kdp_title="GLP-1 Restaurant, Travel & Social Event Log",
         kdp_subtitle="60 Eating-Out Pages, 12 Trip Kits & Usual-Order Cards",
         tagline="Undated  ·  6 × 9 in", pages=85, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.86, 0.82, 0.76), ink=(0.26, 0.18, 0.12), panel=(0.96, 0.93, 0.90),
         bullets=["My-usual-order cards you fill once", "60 event pages: order, fullness, repeat", "12 trip kits: refill, time zone, bag backups", "Not a restaurant ranking"],
         keywords=["restaurant food diary", "travel meal log", "eating out journal", "glp-1 social survival", "trip packing health", "usual order cards", "undated dining log"],
         bisac=["HEA019000", "TRV026000"], bisac_names=["HEALTH & FITNESS / Diet & Nutrition / Nutrition", "TRAVEL / Special Interest / General"], price=9.99, qr=None),
    dict(n="21", file_interior="21_GLP1_Measurements_Photos_and_Labs_Archive_6x9.pdf", stem="21_GLP1_Archive",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  21",
         cover_title="Measurements,\nPhotos & Labs", cover_title_one="Measurements, Photos & Labs Archive",
         subtitle="A quiet archive: inches, clothing,\nphoto log, blank lab sheets",
         spine="Measurements & Labs", kdp_title="GLP-1 Measurements, Photos & Lab Archive",
         kdp_subtitle="12-Month Inches, Clothing, Photo Log & Blank Lab Copy Sheets",
         tagline="Twelve months  ·  6 × 9 in", pages=85, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.90, 0.88, 0.84), ink=(0.20, 0.18, 0.16), panel=(0.97, 0.96, 0.93),
         bullets=["Monthly range, clothing, optional photos", "Blank lab copy sheets — no interpretation", "52 optional weekly inches pages", "Skip any metric that makes you worse"],
         keywords=["body measurement journal", "lab results log book", "progress photo tracker", "waist hip notebook", "glp-1 archive", "clothing size log", "undated measurement diary"],
         bisac=["HEA019000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diet & Nutrition / Nutrition", "HEALTH & FITNESS / Reference"], price=9.99, qr=None),
    dict(n="22", file_interior="22_GLP1_Sleep_Bowel_and_Hydration_Companion_6x9.pdf", stem="22_GLP1_Sleep_Bowel_Water",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  22",
         cover_title="Sleep, Bowel\n& Hydration", cover_title_one="Sleep, Bowel & Hydration Companion",
         subtitle="Ninety days of the unglamorous trio\nthat decides whether a week feels human",
         spine="Sleep · Bowel · Water", kdp_title="GLP-1 Sleep, Bowel & Hydration Companion",
         kdp_subtitle="90-Day Bristol Chart, Sleep Quality & Water Tally (Undated)",
         tagline="Ninety undated days  ·  6 × 9 in", pages=110, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.82, 0.86, 0.88), ink=(0.14, 0.20, 0.24), panel=(0.93, 0.95, 0.96),
         bullets=["Sleep hours + quality scale", "Bristol 1–7 tracking shorthand + ease", "Water tally", "Weekly pattern + clinic brief"],
         keywords=["constipation tracker journal", "bristol stool diary", "hydration log book", "sleep bowel journal", "glp-1 side companion", "water intake tracker", "undated bathroom diary"],
         bisac=["HEA039010", "HEA043000"], bisac_names=["HEALTH & FITNESS / Diseases / Gastrointestinal", "HEALTH & FITNESS / Sleep"], price=9.99, qr=None),
    dict(n="23", file_interior="23_GLP1_Body_Image_and_Mindset_90_Day_6x9.pdf", stem="23_GLP1_Body_Image",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  23",
         cover_title="Body Image\n& Mindset", cover_title_one="Body Image & Mindset 90-Day",
         subtitle="Ninety unique prompts.\nA truce practice, not a glow-up packet.",
         spine="Body Image & Mindset", kdp_title="GLP-1 Body Image & Mindset Journal",
         kdp_subtitle="90 Unique Prompts for a Changing Body (Undated Truce Practice)",
         tagline="Ninety unique prompts  ·  6 × 9 in", pages=110, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.91, 0.84, 0.82), ink=(0.28, 0.14, 0.14), panel=(0.97, 0.93, 0.92),
         bullets=["90 prompts — none repeated", "'Not today' is a complete answer", "Weekly truce page", "Therapist / clinic brief"],
         keywords=["body image journal", "glp-1 mindset", "self compassion notebook", "changing body diary", "90 day unique prompts", "weight loss feelings journal", "undated body kindness"],
         bisac=["SEL014000", "SEL016000"], bisac_names=["SELF-HELP / Eating Disorders & Body Image", "SELF-HELP / Personal Growth / Happiness"], price=9.99, qr=None),
    dict(n="24", file_interior="24_GLP1_Weekly_Review_and_Clinic_Brief_6x9.pdf", stem="24_GLP1_Weekly_Brief",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  24",
         cover_title="Weekly Review\n& Clinic Brief", cover_title_one="Weekly Review & Clinic Brief",
         subtitle="Fifty-two weeks: one review spread\n+ a one-page brief you could hand over",
         spine="Weekly Clinic Brief", kdp_title="GLP-1 Weekly Review & Clinic Brief Binder",
         kdp_subtitle="52 Weeks of Review Spreads + One-Page Clinician Briefs",
         tagline="Fifty-two undated weeks  ·  6 × 9 in", pages=115, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.88, 0.86, 0.80), ink=(0.22, 0.20, 0.14), panel=(0.96, 0.95, 0.91),
         bullets=["Left: the week in signals", "Right: a 90-second clinician brief", "Flag box for loud weeks", "Four quarterly letters"],
         keywords=["clinic visit journal", "weekly health review", "doctor appointment notes", "glp-1 weekly log", "patient brief notebook", "52 week health diary", "undated medical journal"],
         bisac=["HEA020000", "HEA039000"], bisac_names=["HEALTH & FITNESS / Reference", "HEALTH & FITNESS / Diseases / General"], price=9.99, qr=None),
    dict(n="25", file_interior="25_GLP1_Shot_Day_0_48h_Pocket_Log_5x8.pdf", stem="25_GLP1_Shot_Day_Pocket",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  25",
         cover_title="Shot-Day\n0–48h Log", cover_title_one="Shot-Day 0–48h Pocket Log",
         subtitle="Pocket pages for the day of\nand the day after — how it actually went",
         spine="Shot-Day 0–48h", kdp_title="GLP-1 Shot Day 0-48 Hour Pocket Log",
         kdp_subtitle="5x8 Two-Page Cycles: Injection Day + Next 48 Hours (36 Cycles)",
         tagline="Thirty-six cycles  ·  5 × 8 in", pages=79, trim=(5.0, 8.0), paper="white", dark=True,
         bg=(0.18, 0.16, 0.16), ink=(0.93, 0.90, 0.86), panel=(0.24, 0.22, 0.22),
         bullets=["Shot day as prescribed: time, site, 0–12h", "Echo page: +24 to +48h", "36 cycles in a pocket trim", "Copy the dose — never invent one"],
         keywords=["injection day journal", "glp-1 shot log", "pocket side effect diary", "0-48 hour tracker", "5x8 medication log", "weekly injection notes", "undated shot notebook"],
         bisac=["HEA039000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"], price=9.99, qr=None),
    dict(n="26", file_interior="26_GLP1_Protein_Kitchen_Recipe_and_Leftover_Log_6x9.pdf", stem="26_GLP1_Protein_Kitchen",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  26",
         cover_title="Protein Kitchen\nJournal", cover_title_one="Protein Kitchen Journal",
         subtitle="Sixty recipe cards you write yourself,\nplus leftover and 'sat well' notes",
         spine="Protein Kitchen", kdp_title="GLP-1 Protein Kitchen Recipe & Leftover Log",
         kdp_subtitle="60 Blank Recipe Cards + 30 Leftover Logs (Not a Cookbook)",
         tagline="Your recipes, not ours  ·  6 × 9 in", pages=98, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.84, 0.80, 0.72), ink=(0.24, 0.16, 0.10), panel=(0.95, 0.93, 0.88),
         bullets=["60 cards: name, protein, how it sat", "Make-again vs retire", "30 leftover logs so prep gets eaten", "No branded meal plan"],
         keywords=["blank recipe journal", "protein recipe cards", "leftover meal log", "glp-1 kitchen notebook", "how food sat diary", "undated recipe book", "meal prep leftovers"],
         bisac=["CKB000000", "HEA019000"], bisac_names=["COOKING / General", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"], price=9.99, qr=None),
    dict(n="27", file_interior="27_GLP1_Five_Minute_Morning_Pages_6x9.pdf", stem="27_GLP1_Five_Minute",
         series="GLP-1 COMPANION SERIES", series_short="GLP-1 COMPANION  ·  27",
         cover_title="Five-Minute\nMorning Pages", cover_title_one="Five-Minute Morning Pages",
         subtitle="One hundred twenty compact days:\nshot, protein, one sentence, done",
         spine="Five-Minute Pages", kdp_title="GLP-1 Five-Minute Morning Pages",
         kdp_subtitle="120 Compact Daily Pages for People Who Won't Fill a Spread",
         tagline="120 undated days  ·  6 × 9 in", pages=130, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.93, 0.91, 0.86), ink=(0.18, 0.16, 0.14), panel=(0.98, 0.97, 0.94),
         bullets=["Five minutes, then leave the book", "Shot / not-shot, protein, body scale", "One sentence + one gratitude", "30-day harvest pages"],
         keywords=["five minute journal", "glp-1 daily log", "short morning pages", "compact health diary", "120 day undated", "quick daily tracker", "minimalist glp journal"],
         bisac=["SEL010000", "HEA019000"], bisac_names=["SELF-HELP / Journaling", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"], price=9.99, qr=None),
    dict(n="28", file_interior="28_Anxiety_and_Panic_Sensation_Log_6x9.pdf", stem="28_Anxiety_Panic",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  28",
         cover_title="Anxiety & Panic\nSensation Log", cover_title_one="Anxiety & Panic Sensation Log",
         subtitle="Ninety unique prompts, body-first\nsensation, peak-and-pass timing",
         spine="Anxiety & Panic Log", kdp_title="Anxiety & Panic Sensation Log",
         kdp_subtitle="90 Unique Prompts, Body-First Tracking & Peak Timing (Not a Protocol)",
         tagline="Ninety unique prompts  ·  6 × 9 in", pages=110, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.84, 0.86, 0.90), ink=(0.16, 0.18, 0.28), panel=(0.94, 0.95, 0.97),
         bullets=["Sensation first, story second", "90 prompts — none repeated", "Loop checkboxes (google, check, ask)", "Therapist brief pages"],
         keywords=["anxiety journal undated", "panic attack log", "sensation tracker", "worry diary unique prompts", "90 day anxiety notebook", "body scan journal", "therapist homework log"],
         bisac=["SEL020000", "PSY022000"], bisac_names=["SELF-HELP / Anxieties & Phobias", "PSYCHOLOGY / Psychopathology / Anxieties & Phobias"], price=9.99, qr=None),
    dict(n="29", file_interior="29_Sleep_Window_and_Wind_Down_Diary_6x9.pdf", stem="29_Sleep_Window",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  29",
         cover_title="Sleep Window\n& Wind-Down", cover_title_one="Sleep Window & Wind-Down Diary",
         subtitle="Twelve weeks of classic diary fields:\nbed, latency, WASO, rise, wind-down",
         spine="Sleep Window Diary", kdp_title="Sleep Window & Wind-Down Diary",
         kdp_subtitle="12-Week Sleep Diary: Latency, WASO, Rise Time & Wind-Down (Tracking Only)",
         tagline="Twelve undated weeks  ·  6 × 9 in", pages=104, trim=(6.0, 9.0), paper="white", dark=True,
         bg=(0.12, 0.14, 0.20), ink=(0.90, 0.90, 0.88), panel=(0.18, 0.20, 0.26),
         bullets=["Classic sleep-diary fields clinicians recognize", "Wind-down checkboxes", "Weekly pattern page", "Not a restriction protocol"],
         keywords=["sleep diary journal", "insomnia tracker", "WASO sleep log", "wind down notebook", "12 week sleep diary", "latency sleep journal", "undated sleep log"],
         bisac=["HEA043000", "SEL032000"], bisac_names=["HEALTH & FITNESS / Sleep", "SELF-HELP / Self-Management / General"], price=9.99, qr=None),
    dict(n="30", file_interior="30_PMDD_and_Cycle_Mood_Chart_6x9.pdf", stem="30_PMDD_Cycle",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  30",
         cover_title="PMDD &\nCycle Mood Chart", cover_title_one="PMDD & Cycle Mood Chart",
         subtitle="Six undated cycles of daily mood,\nirritability, energy, with luteal flags",
         spine="PMDD Cycle Chart", kdp_title="PMDD & Cycle Mood Chart",
         kdp_subtitle="6-Cycle Daily Mood, Irritability & Luteal Flag Tracker (Not a Diagnosis)",
         tagline="Six cycles  ·  6 × 9 in", pages=188, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.88, 0.80, 0.84), ink=(0.28, 0.12, 0.20), panel=(0.96, 0.92, 0.94),
         bullets=["28 daily pages × 6 cycles", "0–5 mood / rage / hopeless / bloat", "Flag days you would not make a life decision", "Two cycles is a climate hint — bring them"],
         keywords=["pmdd tracker journal", "cycle mood chart", "luteal phase diary", "pmdd symptom log", "hormone mood notebook", "undated cycle tracker", "premenstrual journal"],
         bisac=["HEA024000", "HEA028000"], bisac_names=["HEALTH & FITNESS / Menopause", "HEALTH & FITNESS / Women's Health"], price=9.99, qr=None),
    dict(n="31", file_interior="31_Glucose_and_Meal_Timing_Log_6x9.pdf", stem="31_Glucose_Meal",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  31",
         cover_title="Glucose &\nMeal Timing", cover_title_one="Glucose & Meal Timing Log",
         subtitle="Ninety days to copy meter / CGM\nreadings and meal times as directed",
         spine="Glucose & Meal Timing", kdp_title="Glucose & Meal Timing Log",
         kdp_subtitle="90-Day Meter/CGM Copy Sheets & Meal Context (Not a Dosing Protocol)",
         tagline="Ninety undated days  ·  6 × 9 in", pages=110, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.90, 0.90, 0.86), ink=(0.18, 0.18, 0.16), panel=(0.97, 0.97, 0.94),
         bullets=["Copy the meter — do not interpret a career", "Time, reading, meal/context, note", "Targets left blank on purpose", "Weekly pattern + clinic brief"],
         keywords=["blood sugar log book", "cgm companion journal", "glucose meal diary", "diabetes tracking notebook", "meter reading log", "90 day glucose log", "undated diabetes journal"],
         bisac=["HEA039140", "HEA019000"], bisac_names=["HEALTH & FITNESS / Diseases / Diabetes", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"], price=9.99, qr=None),
    dict(n="32", file_interior="32_Chronic_Pain_Body_Map_and_Flare_Diary_6x9.pdf", stem="32_Chronic_Pain",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  32",
         cover_title="Chronic Pain\nBody-Map Diary", cover_title_one="Chronic Pain Body-Map Diary",
         subtitle="Seventy-two flare pages with front/back\nmark-up, plus twelve monthly dashboards",
         spine="Pain Body-Map Diary", kdp_title="Chronic Pain Body Map & Flare Diary",
         kdp_subtitle="72 Flare Pages, Front/Back Maps, Monthly Function Dashboards",
         tagline="Twelve months of flares  ·  6 × 9 in", pages=92, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.86, 0.84, 0.86), ink=(0.22, 0.16, 0.20), panel=(0.95, 0.94, 0.95),
         bullets=["Simple front/back mark-up", "0–10 plus quality words", "Function I still did — not a failure list", "Monthly dashboards"],
         keywords=["chronic pain journal", "flare tracker diary", "pain body map", "function log book", "monthly pain dashboard", "undated pain diary", "chronic illness notebook"],
         bisac=["HEA009000", "HEA039000"], bisac_names=["HEALTH & FITNESS / Pain Management", "HEALTH & FITNESS / Diseases / General"], price=9.99, qr=None),
    dict(n="33", file_interior="33_Grief_and_Loss_90_Day_Journal_6x9.pdf", stem="33_Grief_Loss",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  33",
         cover_title="Grief & Loss\n90-Day Journal", cover_title_one="Grief & Loss 90-Day Journal",
         subtitle="Ninety unique prompts. No timeline,\nno stages, no silver lining required.",
         spine="Grief & Loss 90", kdp_title="Grief & Loss 90-Day Journal",
         kdp_subtitle="90 Unique Prompts — No Stages, No Silver Linings (Gender-Neutral)",
         tagline="Ninety unique prompts  ·  6 × 9 in", pages=117, trim=(6.0, 9.0), paper="white", dark=True,
         bg=(0.16, 0.16, 0.18), ink=(0.91, 0.89, 0.84), panel=(0.22, 0.22, 0.24),
         bullets=["90 prompts — none repeated", "'Not today' is a complete page", "Optional weekly page — grief owes no calendar", "Crisis line reminder in the front matter"],
         keywords=["grief journal 90 day", "loss diary unique prompts", "bereavement notebook", "gender neutral grief", "mourning journal undated", "grief writing prompts", "memorial journal"],
         bisac=["FAM014000", "SEL010000"], bisac_names=["FAMILY & RELATIONSHIPS / Death, Grief, Bereavement", "SELF-HELP / Journaling"], price=9.99, qr=None),
    dict(n="34", file_interior="34_Twelve_Week_Habit_Operating_System_6x9.pdf", stem="34_Habit_OS",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  34",
         cover_title="12-Week Habit\nOperating System", cover_title_one="12-Week Habit Operating System",
         subtitle="Identity, environment, minimum versions,\nweekly contracts — not a 75-hard clone",
         spine="Habit Operating System", kdp_title="12-Week Habit Operating System",
         kdp_subtitle="Weekly Contracts, Bad-Day Minimums & Environment Design (Undated)",
         tagline="Twelve undated weeks  ·  6 × 9 in", pages=117, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.86, 0.88, 0.82), ink=(0.16, 0.22, 0.14), panel=(0.95, 0.96, 0.92),
         bullets=["At most three habits", "Minimum version for loud days", "Weekly contract + repair after two misses", "Daily tick + one line — no moral essay"],
         keywords=["habit tracker 12 week", "habit contract journal", "identity habits notebook", "minimum viable habit", "undated habit system", "weekly review planner", "behavior change log"],
         bisac=["SEL027000", "SEL016000"], bisac_names=["SELF-HELP / Self-Management / Time Management", "SELF-HELP / Personal Growth / Happiness"], price=9.99, qr=None),
    dict(n="35", file_interior="35_Burnout_and_Energy_Budget_Journal_6x9.pdf", stem="35_Burnout_Energy",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  35",
         cover_title="Burnout &\nEnergy Budget", cover_title_one="Burnout & Energy Budget",
         subtitle="Twelve weeks for knowledge-work humans:\nmeetings, recovery, resentment, sleep",
         spine="Burnout Energy Budget", kdp_title="Burnout & Energy Budget Journal",
         kdp_subtitle="12-Week Meeting Cost, Recovery & Resentment Log (Not a Hustle Planner)",
         tagline="Twelve undated weeks  ·  6 × 9 in", pages=104, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.90, 0.86, 0.80), ink=(0.24, 0.16, 0.10), panel=(0.97, 0.94, 0.90),
         bullets=["Energy at start and close", "Meetings that cost extra", "Resentment as a signal", "Weekly decline / delegate page"],
         keywords=["burnout journal", "energy budget notebook", "resentment tracker", "knowledge worker diary", "meeting fatigue log", "12 week burnout", "undated recovery journal"],
         bisac=["SEL024000", "BUS088000"], bisac_names=["SELF-HELP / Self-Management / Stress Management", "BUSINESS & ECONOMICS / Time Management"], price=9.99, qr=None),
    dict(n="36", file_interior="36_Bladder_and_Pelvic_Symptom_Diary_6x9.pdf", stem="36_Bladder_Pelvic",
         series="WELLNESS COMPANION SERIES", series_short="WELLNESS COMPANION  ·  36",
         cover_title="Bladder &\nPelvic Diary", cover_title_one="Bladder & Pelvic Symptom Diary",
         subtitle="Sixteen three-day diaries in the format\nclinicians actually ask for",
         spine="Bladder & Pelvic Diary", kdp_title="Bladder & Pelvic Symptom Diary",
         kdp_subtitle="16 Three-Day Voiding Diaries (Drink, Void, Urgency, Leak) — Tracking Only",
         tagline="Sixteen 3-day blocks  ·  6 × 9 in", pages=88, trim=(6.0, 9.0), paper="white", dark=False,
         bg=(0.86, 0.88, 0.88), ink=(0.14, 0.20, 0.22), panel=(0.95, 0.96, 0.96),
         bullets=["3 consecutive days — the format clinics want", "Drink / void / urgency / leak / pad", "PT homework line only for assigned items", "16 repeatable blocks"],
         keywords=["bladder diary journal", "voiding log book", "pelvic floor tracker", "urgency leak diary", "3 day bladder diary", "urogynecology notebook", "undated pelvic journal"],
         bisac=["HEA028000", "HEA039000"], bisac_names=["HEALTH & FITNESS / Women's Health", "HEALTH & FITNESS / Diseases / General"], price=9.99, qr=None),
]
