"""Single source of truth for all 18 KDP titles — covers, listings, metadata."""

from __future__ import annotations

# White B&W paperback spine multiplier (inches per page), KDP 2026.
SPINE_WHITE = 0.002252
BLEED = 0.125  # inches
# Spine text only if page count >= 79 (KDP rule).

TITLES = [
    dict(
        n="01",
        file_interior="01_GLP1_Meal_and_Satiety_Journal_6x9.pdf",
        stem="01_GLP1_Meal_and_Satiety",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  01",
        cover_title="Meal &\nSatiety Journal",
        cover_title_one="Meal & Satiety Journal",
        subtitle="Daily two-page spreads for protein, fiber,\nhunger, and non-scale victories",
        spine="Meal & Satiety Journal",
        kdp_title="GLP-1 Meal & Satiety Journal",
        kdp_subtitle="Undated 8-Week Protein, Fiber & Hunger Tracker (Two-Page Daily Spreads)",
        tagline="Eight undated weeks  ·  6 × 9 in",
        pages=131,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.80, 0.85, 0.78),
        ink=(0.16, 0.22, 0.18),
        panel=(0.93, 0.95, 0.91),
        bullets=[
            "Two-page daily spreads: meals, hunger, injection timing",
            "Protein and fiber target vs. actual table",
            "Non-scale victory box every evening",
            "Weekly recap after every seven days",
        ],
        keywords=[
            "glp-1 meal journal",
            "satiety tracker undated",
            "protein fiber log book",
            "hunger scale journal",
            "weight loss food diary",
            "injection timing notebook",
            "non scale victory journal",
        ],
        bisac=["HEA019000", "HEA006000"],  # Diet & Nutrition / Weight Loss-ish — see listings
        bisac_names=["HEALTH & FITNESS / Diet & Nutrition / Nutrition", "HEALTH & FITNESS / Weight Loss"],
        price=12.99,
        qr=None,
    ),
    dict(
        n="02",
        file_interior="02_GLP1_Side_Effect_and_Symptom_Diary_6x9.pdf",
        stem="02_GLP1_Side_Effect_Diary",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  02",
        cover_title="Side-Effect &\nSymptom Diary",
        cover_title_one="Side-Effect & Symptom Diary",
        subtitle="Weekly checklists, 0–5 severity grids,\nand clinic visit-prep pages",
        spine="Side-Effect Diary",
        kdp_title="GLP-1 Side Effect Tracker",
        kdp_subtitle="Weekly Symptom Log with Severity Grids & Clinic Visit Prep Pages",
        tagline="Thirty-six undated weeks  ·  6 × 9 in",
        pages=92,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.88, 0.87, 0.84),
        ink=(0.20, 0.20, 0.20),
        panel=(0.96, 0.95, 0.93),
        bullets=[
            "36 weekly 0–5 observation grids",
            "What helped / what aggravated",
            "Visit-prep page every four weeks",
            "Hydration, sleep, and flag days",
        ],
        keywords=[
            "glp-1 side effect journal",
            "symptom tracker notebook",
            "nausea constipation log",
            "clinic visit prep journal",
            "weekly health diary",
            "injection site tracker",
            "undated symptom log book",
        ],
        bisac=["HEA039000", "HEA028000"],
        bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Women's Health"],
        price=11.99,
        qr=None,
    ),
    dict(
        n="03",
        file_interior="03_GLP1_Plateau_Breaker_30_Day_Planner_6x9.pdf",
        stem="03_GLP1_Plateau_Breaker",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  03",
        cover_title="Plateau-Breaker\n30-Day Challenge",
        cover_title_one="Plateau-Breaker 30-Day Challenge",
        subtitle="Daily habit grids, mindset prompts,\nand a second encore cycle",
        spine="Plateau-Breaker 30",
        kdp_title="GLP-1 Plateau Breaker 30-Day Challenge Planner",
        kdp_subtitle="Daily Habit Grid, Mindset Prompts & Encore Cycle (Undated)",
        tagline="Thirty days + thirty encore  ·  6 × 9 in",
        pages=107,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.86, 0.78, 0.72),
        ink=(0.30, 0.18, 0.14),
        panel=(0.95, 0.91, 0.88),
        bullets=[
            "30 two-page challenge days",
            "Unique mindset prompt each day",
            "Weekly reviews + 30 encore pages",
            "Protein, steps, sleep, NSV",
        ],
        keywords=[
            "weight loss plateau journal",
            "glp-1 challenge planner",
            "30 day habit tracker",
            "mindset prompt journal",
            "protein habit grid",
            "undated challenge book",
            "non scale victory planner",
        ],
        bisac=["HEA019000", "SEL020000"],
        bisac_names=["HEALTH & FITNESS / Diet & Nutrition / Nutrition", "SELF-HELP / Motivational & Inspirational"],
        price=12.99,
        qr="pep",
    ),
    dict(
        n="04",
        file_interior="04_GLP1_Maintenance_Phase_Tracker_6x9.pdf",
        stem="04_GLP1_Maintenance",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  04",
        cover_title="Maintenance\nPhase Tracker",
        cover_title_one="Maintenance Phase Tracker",
        subtitle="Twelve months of range bands,\nrefill reminders, and relapse-risk notes",
        spine="Maintenance Tracker",
        kdp_title="GLP-1 Maintenance Phase Tracker",
        kdp_subtitle="12-Month Range Band, Refill Log & Relapse-Risk Journal",
        tagline="Twelve undated months  ·  6 × 9 in",
        pages=85,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.91, 0.87, 0.80),
        ink=(0.26, 0.22, 0.16),
        panel=(0.97, 0.95, 0.91),
        bullets=[
            "Agreed range band — not a daily trial",
            "Four weekly pages inside each month",
            "Refill, labs, and waist/clothes notes",
            "Relapse-risk slider and repairs",
        ],
        keywords=[
            "weight maintenance journal",
            "post glp-1 tracker",
            "refill reminder log book",
            "range band weight log",
            "relapse prevention journal",
            "12 month health tracker",
            "undated maintenance diary",
        ],
        bisac=["HEA019000", "HEA028000"],
        bisac_names=["HEALTH & FITNESS / Diet & Nutrition / Nutrition", "HEALTH & FITNESS / Women's Health"],
        price=11.99,
        qr=None,
    ),
    dict(
        n="05",
        file_interior="05_GLP1_Hunger_and_Craving_Mood_Log_6x9.pdf",
        stem="05_GLP1_Hunger_Craving",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  05",
        cover_title="Hunger &\nCraving Log",
        cover_title_one="Hunger & Craving Log",
        subtitle="Four-quadrant daily pages: mood,\nintensity, what I did instead, reward",
        spine="Hunger & Craving Log",
        kdp_title="GLP-1 Hunger & Craving Mood Log",
        kdp_subtitle="90-Day Four-Quadrant Tracker for Mood, Intensity & What I Did Instead",
        tagline="Ninety undated days  ·  6 × 9 in",
        pages=113,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.90, 0.82, 0.82),
        ink=(0.30, 0.16, 0.18),
        panel=(0.97, 0.93, 0.93),
        bullets=[
            "90 four-quadrant daily pages",
            "Peak craving 1–10 + what I craved",
            "What I did instead + sticker space",
            "Weekly pattern harvest",
        ],
        keywords=[
            "craving tracker journal",
            "glp-1 hunger log",
            "mood food diary",
            "emotional eating journal",
            "habit instead tracker",
            "90 day undated log",
            "appetite awareness notebook",
        ],
        bisac=["HEA019000", "SEL014000"],
        bisac_names=["HEALTH & FITNESS / Diet & Nutrition / Nutrition", "SELF-HELP / Eating Disorders & Body Image"],
        price=12.99,
        qr=None,
    ),
    dict(
        n="06",
        file_interior="06_GLP1_Fitness_and_Step_Companion_6x9.pdf",
        stem="06_GLP1_Fitness",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  06",
        cover_title="Fitness &\nStep Companion",
        cover_title_one="Fitness & Step Companion",
        subtitle="Weekly strength–cardio splits,\nrecovery notes, cooldown timer graphic",
        spine="Fitness & Step Companion",
        kdp_title="GLP-1 Fitness & Step Companion",
        kdp_subtitle="32-Week Strength, Cardio & Recovery Log (Undated)",
        tagline="Thirty-two undated weeks  ·  6 × 9 in",
        pages=85,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.80, 0.85, 0.88),
        ink=(0.14, 0.20, 0.26),
        panel=(0.93, 0.95, 0.96),
        bullets=[
            "Plan on the left, log on the right",
            "Strength + cardio / steps split",
            "RPE and recovery notes",
            "Timer ring is a personal record, not a protocol",
        ],
        keywords=[
            "glp-1 workout log",
            "step tracker journal",
            "strength cardio planner",
            "weekly fitness notebook",
            "recovery log book",
            "undated training diary",
            "walking habit tracker",
        ],
        bisac=["HEA007000", "HEA019000"],
        bisac_names=["HEALTH & FITNESS / Exercise / General", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
        price=11.99,
        qr=None,
    ),
    dict(
        n="07",
        file_interior="07_GLP1_Titration_Schedule_Notebook_5x8.pdf",
        stem="07_GLP1_Titration_Pocket",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  07",
        cover_title="Titration\nSchedule",
        cover_title_one="Titration Schedule Notebook",
        subtitle="Pocket log for dose dates,\nnext-pen reminders, sticker space",
        spine="Titration Log",
        kdp_title="GLP-1 Titration Log (Pocket 5x8)",
        kdp_subtitle="Weekly Dose-as-Prescribed Notebook with Pen & Refill Reminders",
        tagline="Fifty-two weeks  ·  5 × 8 in pocket",
        pages=78,
        trim=(5.0, 8.0),
        paper="white",
        dark=True,
        bg=(0.16, 0.17, 0.18),
        ink=(0.93, 0.91, 0.87),
        panel=(0.22, 0.23, 0.24),
        bullets=[
            "Copy the dose you were prescribed — never invent one",
            "52 weekly date / time / site tables",
            "Next-pen and discard-after lines",
            "Sticker / lot margin",
        ],
        keywords=[
            "glp-1 titration log",
            "dose date notebook",
            "pocket medication log",
            "pen refill tracker",
            "5x8 health journal",
            "weekly injection log",
            "undated med notebook",
        ],
        bisac=["HEA039000", "HEA020000"],
        bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"],
        price=9.99,
        qr=None,
    ),
    dict(
        n="08",
        file_interior="08_GLP1_Non_Scale_Victories_Gratitude_Journal_6x9.pdf",
        stem="08_GLP1_NSV_Gratitude",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  08",
        cover_title="Non-Scale\nVictories",
        cover_title_one="Non-Scale Victories Gratitude Journal",
        subtitle="Half-page gratitude, half-page NSV —\nenergy, clothing, labs, quiet evidence",
        spine="NSV Gratitude Journal",
        kdp_title="Non-Scale Victories Gratitude Journal",
        kdp_subtitle="120-Day GLP-1 Progress Log for Energy, Clothing Fit & Labs",
        tagline="One hundred twenty days  ·  6 × 9 in",
        pages=131,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.93, 0.90, 0.84),
        ink=(0.24, 0.20, 0.14),
        panel=(0.98, 0.96, 0.92),
        bullets=[
            "120 undated daily pages",
            "Three true gratitudes + one NSV",
            "Rotating hints you can ignore",
            "30-day harvest lists",
        ],
        keywords=[
            "non scale victory journal",
            "gratitude journal women",
            "glp-1 progress log",
            "body kindness diary",
            "clothing fit tracker",
            "undated gratitude book",
            "weight loss mindset journal",
        ],
        bisac=["SEL016000", "HEA019000"],
        bisac_names=["SELF-HELP / Personal Growth / Happiness", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
        price=12.99,
        qr=None,
    ),
    dict(
        n="09",
        file_interior="09_GLP1_Injection_Sticker_Calendar_85x11.pdf",
        stem="09_GLP1_Injection_Calendar",
        series="GLP-1 TRACKING SERIES",
        series_short="GLP-1 SERIES  ·  09",
        cover_title="Injection\nSticker Calendar",
        cover_title_one="Pre- & Post-Injection Sticker Calendar",
        subtitle="Undated monthly calendars with sticker\ncircles, site rotation, and refill logs",
        spine="Injection Sticker Calendar",
        kdp_title="GLP-1 Injection Sticker Calendar",
        kdp_subtitle="Undated 12-Month 8.5 x 11 Log with Site Map & Refill Pages",
        tagline="Twelve undated months  ·  8.5 × 11 in",
        pages=98,
        trim=(8.5, 11.0),
        paper="white",
        dark=False,
        bg=(0.90, 0.89, 0.85),
        ink=(0.18, 0.18, 0.18),
        panel=(0.97, 0.96, 0.94),
        bullets=[
            "Six-row sticker calendars you number yourself",
            "Blank site map — copy what your clinic showed you",
            "Injection log, weekly sheets, refill notes",
            "White paper recommended for vinyl stickers",
        ],
        keywords=[
            "injection calendar book",
            "glp-1 sticker planner",
            "weekly injection log",
            "site rotation tracker",
            "8.5 x 11 health calendar",
            "undated med calendar",
            "refill reminder notebook",
        ],
        bisac=["HEA039000", "NON000000"],
        bisac_names=["HEALTH & FITNESS / Diseases / General", "NON-CLASSIFIABLE"],
        price=14.99,
        qr="coupon",
    ),
    dict(
        n="10",
        file_interior="10_Sobriety_and_Sober_Curious_Journal_90_Day_6x9.pdf",
        stem="10_Sobriety_90",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  10",
        cover_title="Sober /\nSober-Curious",
        cover_title_one="Sobriety & Sober-Curious Journal",
        subtitle="Ninety days: trigger log, craving slider,\ngratitude — gender-neutral, not 12-step branded",
        spine="Sober / Sober-Curious 90",
        kdp_title="Sober Curious 90-Day Journal",
        kdp_subtitle="Gender-Neutral Trigger, Craving & Gratitude Tracker (Not 12-Step)",
        tagline="Ninety undated days  ·  6 × 9 in",
        pages=113,
        trim=(6.0, 9.0),
        paper="white",
        dark=True,
        bg=(0.18, 0.24, 0.20),
        ink=(0.93, 0.91, 0.86),
        panel=(0.24, 0.30, 0.26),
        bullets=[
            "One page, one honest day",
            "Trigger logistics, not identity essays",
            "Protective-move checkboxes",
            "Weekly reviews · not AA branded",
        ],
        keywords=[
            "sober journal 90 day",
            "sober curious notebook",
            "craving tracker alcohol",
            "gender neutral recovery",
            "dry january journal",
            "sober october diary",
            "undated sobriety log",
        ],
        bisac=["SEL026000", "SEL006000"],
        bisac_names=["SELF-HELP / Substance Abuse & Addictions / Alcohol", "SELF-HELP / Affirmations"],
        price=12.99,
        qr=None,
    ),
    dict(
        n="11",
        file_interior="11_Intermittent_Fasting_Window_Tracker_12_Week_6x9.pdf",
        stem="11_IF_Window_Tracker",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  11",
        cover_title="Fasting Window\nTracker",
        cover_title_one="Intermittent Fasting Window Tracker",
        subtitle="Twelve weeks of 24-hour timeline bars,\nhydration, mood, and weekly reviews",
        spine="Fasting Window Tracker",
        kdp_title="Intermittent Fasting Window Tracker",
        kdp_subtitle="12-Week 16:8 / Custom Fast Log with 24-Hour Timeline Bars",
        tagline="Twelve undated weeks  ·  6 × 9 in",
        pages=107,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.93, 0.92, 0.88),
        ink=(0.12, 0.16, 0.22),
        panel=(0.98, 0.97, 0.94),
        bullets=[
            "Shade the hours you actually fasted",
            "12/12 through 20/4 or custom",
            "Hydration row + energy/mood scales",
            "Optional weight sparkline you can skip",
        ],
        keywords=[
            "intermittent fasting log",
            "16/8 fasting tracker",
            "fasting window journal",
            "18/6 food diary",
            "undated IF notebook",
            "12 week fasting log",
            "time restricted eating",
        ],
        bisac=["HEA019000", "HEA006000"],
        bisac_names=["HEALTH & FITNESS / Diet & Nutrition / Nutrition", "HEALTH & FITNESS / Weight Loss"],
        price=12.99,
        qr=None,
    ),
    dict(
        n="12",
        file_interior="12_Migraine_Weather_and_Trigger_Diary_6x9.pdf",
        stem="12_Migraine_Weather",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  12",
        cover_title="Migraine Weather\n& Trigger Diary",
        cover_title_one="Migraine Weather & Trigger Diary",
        subtitle="Episode pages with pain maps, aura lists,\nbarometric fields, monthly dashboards",
        spine="Migraine Weather Diary",
        kdp_title="Migraine Weather & Trigger Diary",
        kdp_subtitle="Pain Map, Aura Checklist, Barometric Pressure Log & Monthly Dashboard",
        tagline="Twelve months of episodes  ·  6 × 9 in",
        pages=97,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.86, 0.85, 0.90),
        ink=(0.22, 0.20, 0.28),
        panel=(0.95, 0.94, 0.97),
        bullets=[
            "Front + side head maps",
            "Pressure, temp, humidity, storm front",
            "72 episode pages + 12 dashboards",
            "A log you can hand a clinician",
        ],
        keywords=[
            "migraine tracker journal",
            "headache weather diary",
            "barometric pressure log",
            "aura symptom notebook",
            "pain map journal",
            "migraine trigger diary",
            "undated headache log",
        ],
        bisac=["HEA039050", "HEA009000"],
        bisac_names=["HEALTH & FITNESS / Diseases / Nervous System (incl. Brain)", "HEALTH & FITNESS / Pain Management"],
        price=12.99,
        qr=None,
    ),
    dict(
        n="13",
        file_interior="13_ADHD_Medication_and_Focus_Log_6x9.pdf",
        stem="13_ADHD_Focus_Log",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  13",
        cover_title="ADHD Medication\n& Focus Log",
        cover_title_one="ADHD Medication & Focus Log",
        subtitle="Dose/time grids, side-effect columns,\nPomodoro stamps, weekly reviews",
        spine="ADHD Med & Focus Log",
        kdp_title="ADHD Medication & Focus Log",
        kdp_subtitle="90-Day Dose Tracker, Pomodoro Focus Boxes & Dopamine Stamp Pages",
        tagline="Ninety undated days  ·  6 × 9 in",
        pages=113,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.78, 0.87, 0.85),
        ink=(0.10, 0.26, 0.26),
        panel=(0.92, 0.96, 0.95),
        bullets=[
            "Copy the bottle — do not invent a dose",
            "Focus boxes for blocks you actually started",
            "Wear-off / crash line",
            "Dopamine stamp row",
        ],
        keywords=[
            "adhd medication log",
            "stimulant dose tracker",
            "pomodoro focus journal",
            "adhd daily planner",
            "focus tracker notebook",
            "undated adhd log",
            "dopamine reward journal",
        ],
        bisac=["HEA039110", "SEL014000"],
        bisac_names=["HEALTH & FITNESS / Diseases / Nervous System", "SELF-HELP / Personal Growth / Success"],
        price=12.99,
        qr=None,
    ),
    dict(
        n="14",
        file_interior="14_Perimenopause_Symptom_and_Mood_Chart_6x9.pdf",
        stem="14_Perimenopause_Chart",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  14",
        cover_title="Perimenopause\nSymptom Chart",
        cover_title_one="Perimenopause Symptom & Mood Chart",
        subtitle="Daily hot-flash tallies, sleep wheels,\ncycle timelines, clinic question lists",
        spine="Perimenopause Chart",
        kdp_title="Perimenopause Symptom & Mood Chart",
        kdp_subtitle="90-Day Hot Flash, Sleep Wheel & Cycle Timeline Tracker",
        tagline="Ninety undated days  ·  6 × 9 in",
        pages=107,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.89, 0.82, 0.85),
        ink=(0.28, 0.16, 0.22),
        panel=(0.96, 0.92, 0.94),
        bullets=[
            "Tally marks for flashes and night sweats",
            "Sleep-quality wheel 1–5",
            "Chaotic-cycle timeline (blank is data)",
            "Questions for the next visit",
        ],
        keywords=[
            "perimenopause tracker",
            "hot flash journal",
            "menopause symptom diary",
            "cycle mood chart",
            "night sweat log book",
            "undated peri journal",
            "women's health notebook",
        ],
        bisac=["HEA028000", "HEA024000"],
        bisac_names=["HEALTH & FITNESS / Women's Health", "HEALTH & FITNESS / Menopause"],
        price=12.99,
        qr=None,
    ),
    dict(
        n="15",
        file_interior="15_Gut_Health_and_Low_FODMAP_Symptom_Diary_6x9.pdf",
        stem="15_FODMAP_Gut_Diary",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  15",
        cover_title="Gut Health &\nLow-FODMAP Diary",
        cover_title_one="Gut Health & Low-FODMAP Symptom Diary",
        subtitle="Meal columns, symptom latency,\nBristol chart, reintroduction cards",
        spine="Low-FODMAP Diary",
        kdp_title="Low FODMAP Food & Symptom Diary",
        kdp_subtitle="8-Week Gut Tracker with Bristol Chart & Reintroduction Cards",
        tagline="Eight weeks + reintro cards  ·  6 × 9 in",
        pages=88,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.85, 0.86, 0.76),
        ink=(0.20, 0.24, 0.14),
        panel=(0.94, 0.95, 0.88),
        bullets=[
            "Breakfast / lunch / dinner / extras",
            "Latency in minutes + severity 1–5",
            "Bristol 1–7 tracking shorthand",
            "12 reintroduction cards (your plan, not ours)",
        ],
        keywords=[
            "fodmap journal",
            "ibs food diary",
            "gut symptom tracker",
            "bristol stool log",
            "elimination diet notebook",
            "low fodmap diary",
            "reintroduction food log",
        ],
        bisac=["HEA039010", "HEA019000"],
        bisac_names=["HEALTH & FITNESS / Diseases / Gastrointestinal", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
        price=11.99,
        qr=None,
    ),
    dict(
        n="16",
        file_interior="16_Digital_Detox_Screen_Time_Workbook_30_Day_6x9.pdf",
        stem="16_Digital_Detox_30",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  16",
        cover_title="Digital Detox\n30-Day Workbook",
        cover_title_one="Digital Detox Screen-Time Workbook",
        subtitle="Usage bars, dopamine notes,\nreal-world substitutions, maintenance coda",
        spine="Digital Detox 30",
        kdp_title="Digital Detox 30-Day Screen Time Workbook",
        kdp_subtitle="Daily Usage Bar, Dopamine Trigger Log & Real-World Habit Substitutions",
        tagline="Thirty days + twenty maintenance  ·  6 × 9 in",
        pages=96,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.95, 0.95, 0.94),
        ink=(0.12, 0.12, 0.12),
        panel=(1, 1, 1),
        bullets=[
            "Copy hours from Screen Time / Digital Wellbeing",
            "Name the trigger, tick a substitution",
            "30 two-page days + 20 lighter coda days",
            "Minimalist matte-friendly interior",
        ],
        keywords=[
            "screen time journal",
            "digital detox workbook",
            "phone habit tracker",
            "30 day unplug journal",
            "dopamine detox notebook",
            "attention journal undated",
            "social media tracker",
        ],
        bisac=["SEL027000", "SEL043000"],
        bisac_names=["SELF-HELP / Self-Management / Time Management", "SELF-HELP / Green Lifestyle"],
        price=11.99,
        qr=None,
    ),
    dict(
        n="17",
        file_interior="17_Postpartum_Core_and_Pelvic_Floor_Recovery_Planner_6x9.pdf",
        stem="17_Postpartum_Recovery",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  17",
        cover_title="Postpartum\nRecovery Planner",
        cover_title_one="Postpartum Core & Pelvic-Floor Recovery Planner",
        subtitle="Six-week daily pages plus weeks 7–12:\nPT homework ticks, mood, support prompts",
        spine="Postpartum Recovery",
        kdp_title="Postpartum Recovery Planner",
        kdp_subtitle="12-Week Pelvic Floor PT Homework Tracker (Not an Exercise Program)",
        tagline="Weeks 1–6 daily, 7–12 lighter  ·  6 × 9 in",
        pages=102,
        trim=(6.0, 9.0),
        paper="white",
        dark=False,
        bg=(0.92, 0.86, 0.84),
        ink=(0.28, 0.18, 0.18),
        panel=(0.98, 0.94, 0.93),
        bullets=[
            "Track the homework your PT assigned — nothing extra",
            "Stitches / incision care as you were taught",
            "Mood, energy, partner support prompt",
            "Red-flag reminder on every early page",
        ],
        keywords=[
            "postpartum recovery journal",
            "pelvic floor tracker",
            "new mom planner",
            "c-section recovery log",
            "pt homework notebook",
            "12 week postpartum",
            "undated baby journal",
        ],
        bisac=["HEA044000", "HEA028000"],
        bisac_names=["HEALTH & FITNESS / Pregnancy & Childbirth", "HEALTH & FITNESS / Women's Health"],
        price=12.99,
        qr="pt",
    ),
    dict(
        n="18",
        file_interior="18_Autoimmune_Flare_and_Energy_Level_Journal_6x9.pdf",
        stem="18_Autoimmune_Flare",
        series="WELLNESS TRACKING SERIES",
        series_short="WELLNESS  ·  18",
        cover_title="Autoimmune Flare\n& Energy Journal",
        cover_title_one="Autoimmune Flare & Energy-Level Journal",
        subtitle="Daily spoon counts, severity grids,\nmedication-as-prescribed, micro-gratitude",
        spine="Autoimmune Flare Journal",
        kdp_title="Autoimmune Flare & Energy Journal",
        kdp_subtitle="90-Day Spoon Tracker, Symptom Grid & Medication-as-Prescribed Log",
        tagline="Ninety undated days  ·  6 × 9 in",
        pages=113,
        trim=(6.0, 9.0),
        paper="white",
        dark=True,
        bg=(0.16, 0.20, 0.26),
        ink=(0.92, 0.90, 0.86),
        panel=(0.22, 0.26, 0.32),
        bullets=[
            "Spoons as a budget, not a dare",
            "0–5 grids for pain, fatigue, fog, GI, skin",
            "Copy meds from the label",
            "Weekly flare review",
        ],
        keywords=[
            "autoimmune tracker journal",
            "spoon theory notebook",
            "chronic illness diary",
            "flare energy log",
            "fatigue pain tracker",
            "undated health journal",
            "medication log book",
        ],
        bisac=["HEA039000", "HEA039020"],
        bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Diseases / Immune System"],
        price=12.99,
        qr=None,
    ),
]


def spine_in(pages: int) -> float:
    return round(pages * SPINE_WHITE, 4)


def wrap_size(trim: tuple[float, float], pages: int) -> tuple[float, float, float]:
    tw, th = trim
    sp = spine_in(pages)
    width = BLEED + tw + sp + tw + BLEED
    height = BLEED + th + BLEED
    return width, height, sp
