"""Unique prompts — premium volumes. Do not recycle across days."""

BODY_IMAGE_90 = [
    "Where did I treat this body as a project instead of a place I live?",
    "What did clothing feel like at noon, in one honest sentence?",
    "A compliment I almost dismissed. Write it again, slower.",
    "If the mirror were a witness, not a judge, what would it have seen?",
    "What did I need that was not a smaller size?",
    "The first mean sentence of the day — and the shorter true one.",
    "A function I am grateful this body performed without being asked.",
    "Who benefits when I postpone living until I 'arrive'?",
    "What would I wear if nobody's eyes were homework?",
    "Hunger, fullness, or a story — which one was loudest?",
    "A photo I would keep even if the number on the scale changed.",
    "Where did I compare, and what did it cost me in minutes?",
    "Kindness I offered someone else's body. Offer it here.",
    "What 'done' would look like if it could not be a weight.",
    "A social event I want to be in, not just survive.",
    "The part of me that is tired of being managed.",
    "What did strength feel like, even tiny?",
    "If I could not take a progress photo, how else would I know I'm here?",
    "A food I ate in peace. Describe the peace, not the food.",
    "What am I postponing that a future body cannot do for me?",
    "The oldest rule I still obey. Is it mine?",
    "Where did I disappear in a group — and why?",
    "A boundary with talk about bodies (mine or others).",
    "What my face does when I am not arranging it.",
    "Rest I earned by being a person, not by burning enough.",
    "A number I will not give power to today. Name it.",
    "How did I speak about this body to myself in the kitchen?",
    "Someone who likes me in this exact version.",
    "What would a truce day include?",
    "The outfit that felt like me, not like armor.",
    "A grief about change that is allowed to exist beside pride.",
    "Where did I pinch, poke, or test? What was I hoping to know?",
    "If appetite is quieter, what else is asking to be heard?",
    "A future event I will not make hostage to a size.",
    "What did I enjoy with my senses that had nothing to sell?",
    "The sentence I want on the inside of the closet door.",
    "How comparison showed up on a screen.",
    "A way this body carried me through a boring, decent day.",
    "What I would tell a friend in my clothes.",
    "Did I earn food today in my head? Unwrite that.",
    "A softness I can tolerate for ten minutes.",
    "The story of my body at 16 versus the one I need now.",
    "Where did I hide (behind a bag, a table, a joke)?",
    "What 'maintenance' of dignity looks like, not of a number.",
    "A doctor visit: what I want to be besides a chart.",
    "How I want to be touched, including not at all.",
    "The smallest piece of evidence I am allowed to keep.",
    "What I fear people will say — and what they actually said.",
    "A meal I did not narrate.",
    "If this were the body I keep, how would I treat it this week?",
    "A movement that was play, not penance.",
    "The part of the day I was least in the mirror.",
    "What I outsourced to a future thinner self.",
    "A cultural rule I am returning to sender.",
    "How fatigue changed the volume of self-talk.",
    "One true thing the scale cannot measure.",
    "Where I was generous with this body.",
    "A photo from before that I can look at without a trial.",
    "The difference between taking care and taking control.",
    "What I want my partner / friend to stop saying.",
    "What I want them to start saying.",
    "A shop, pool, or room I entered anyway.",
    "How I knew I was safe in a body moment.",
    "The joke about my body I will not finish.",
    "A skill this season of change is teaching that is not discipline.",
    "Where did I apologize for taking space?",
    "What 'enough protein' felt like as care, not a test.",
    "A morning without a weigh-in: what filled the gap?",
    "The person I am becoming that has nothing to do with size.",
    "A piece of clothing I will not throw away in a mood.",
    "How I want to age in this body, in one line.",
    "What I performed and what I actually felt.",
    "A hunger I answered without a story.",
    "The body memory that visited today.",
    "If no one commented for a year, what would I still want?",
    "A ritual that honors this body without improving it.",
    "Where vanity and dignity got confused.",
    "The number of times I checked. Write it. Don't moralize.",
    "A future letter from a body that was not abandoned.",
    "What I want on the table besides food.",
    "How I spoke about other bodies. Recalibrate.",
    "A win that would still count on a plateau.",
    "The room in my house that is hardest. Why?",
    "What I will do with my hands instead of pinch.",
    "A teacher, not a critic, in one sentence.",
    "How medicine (if any) changed the plot — without making it the whole plot.",
    "A desire that is not a smaller jeans size.",
    "The child I was, looking at this adult body.",
    "What I want to be trusted with.",
    "Today's truce terms, signed.",
]

GRIEF_90 = [
    "What is gone, in the simplest nouns I can bear.",
    "Where the missing sits in the room today.",
    "A thing they would have noticed about this morning.",
    "Anger, if it is here. It does not have to be polite.",
    "A small object that still holds them.",
    "What I cannot tell the people who want me 'back'.",
    "A memory that arrived without being invited.",
    "How my body kept the score this afternoon.",
    "The sentence I keep almost saying out loud.",
    "Who can hear the true version, not the tidy one.",
    "A ritual I need that no one taught me.",
    "Guilt that is visiting. Is it a fact or a haunt?",
    "What I would ask if asking still worked.",
    "A place I avoid. A place I seek.",
    "How time is lying and telling the truth at once.",
    "The first laugh, if there was one, and the tax it charged.",
    "What I am not ready to give away.",
    "A dream, or the lack of one.",
    "Food, sleep, and the animal facts of staying alive.",
    "A secondary loss no one counts (role, future, witness).",
    "The weather inside versus the weather outside.",
    "What I need from people that is not advice.",
    "A song I can or cannot play.",
    "The version of me from before. Wave. Do not merge.",
    "What anniversary is approaching in the body before the calendar.",
    "A kindness I can accept without performing okay-ness.",
    "The story others are writing. The one I am writing.",
    "If grief were a guest, what would it eat.",
    "A boundary with platitudes.",
    "What I want remembered, in their words if I have them.",
    "The unfinished conversation, left unfinished on purpose today.",
    "How love is changing shape, not volume.",
    "A rage at God, medicine, luck, or nothing. Let it stand.",
    "The child-part that wants a rewrite.",
    "What I did that was merely practical and therefore holy.",
    "A photograph: what is outside the frame.",
    "Who I am angry at that is still alive.",
    "A tradition I will keep, twist, or retire.",
    "The hour of day that drops the floor.",
    "What I need tonight to be slightly less impossible.",
    "A word they used that I can borrow.",
    "How I am different in rooms they never entered.",
    "The paperwork of death or ending, if it still sits.",
    "A future date I am dreading. Name it.",
    "What I envy in other people's ordinary.",
    "A sensory detail (soap, jacket, voicemail).",
    "The help I will ask for in one concrete sentence.",
    "What I will not make meaning of yet.",
    "A loyalty I feel to sadness.",
    "Where relief and grief share a chair.",
    "The name, written again.",
    "What I want on the table besides memory.",
    "A stranger who was kind without knowing.",
    "How I want to be checked on (frequency, channel).",
    "The part of the story that is still too sharp to tell.",
    "A place in nature that can hold this.",
    "What I am learning about time that I did not want to know.",
    "A letter I will not send. First line only, or all of it.",
    "The body of work of our relationship, in three bullets.",
    "What I need to stop explaining.",
    "A holiday plan that is small enough.",
    "How I betrayed myself to look fine.",
    "The opposite of closure, if I need that instead.",
    "A joke they would still get.",
    "What I want from the dead / gone that the living can actually give.",
    "A room I can cry in.",
    "The first thing I do that is not about this, and whether that's betrayal.",
    "A promise I can keep this week.",
    "Who I have become the historian for.",
    "The fear that I will forget. One detail to keep.",
    "What forgiveness is not ready for.",
    "A map of support, honest about holes.",
    "The sentence 'I am still here' — argue both sides.",
    "A meal that was just a meal.",
    "How I want their name said in public.",
    "The work of grief versus the performance of grief.",
    "A future joy I am willing to not cancel in advance.",
    "What I need from a professional, if anything.",
    "The object I will not tidy away yet.",
    "A conversation with them in the present tense, then the past.",
    "Where I feel them without magic, just memory.",
    "The smallest unit of okay (a minute, a cup).",
    "What I would tell someone one week behind me.",
    "A boundary with people who need me to be inspiring.",
    "The unfinished house / trip / plan. One brick I can still lay, or not.",
    "How my faith / non-faith is changing.",
    "A thank-you that is not a eulogy.",
    "The night plan: light, sound, company, none.",
    "What I am allowed to want now.",
    "Today's true weather, without a moral.",
]

ANXIETY_90 = [
    "Where in the body did it start (jaw, gut, chest, hands)?",
    "What was the first story the sensation hired?",
    "A fact I can verify in five minutes versus a forecast.",
    "The catastrophe movie: title, runtime, how it ends in my head.",
    "What I did with my feet (left, paced, ran a loop).",
    "Caffeine, sleep, cycle, news — confounders, not blame.",
    "A person, app, or room that turned the volume up.",
    "What 'safe enough' would look like for the next hour.",
    "The urge I rode (check, ask, undo, google).",
    "A slower exhale I actually did, or did not.",
    "What I need that is not reassurance on a loop.",
    "Name three objects in the room without interpreting them.",
    "The oldest alarm this feeling reminds me of.",
    "What I postponed because of it.",
    "A body scan from scalp to heel, one word per region.",
    "If this were weather, not identity, what's the forecast window?",
    "Who I texted, and whether I needed a witness or a fix.",
    "The checking behavior I will delay by ten minutes tonight.",
    "What I am trying to make certain that cannot be.",
    "A kind sentence in the second person ('You are…').",
    "Heart, breath, sweat — observations, not diagnoses.",
    "The meeting / message I am dreading. Shrink it to a next action.",
    "What I googled. What I will not google.",
    "A panic wave: peak time, minutes, what I did at minute two.",
    "Where I abandoned my plan to keep the feeling quiet.",
    "The difference between danger and discomfort today.",
    "A boundary with news and true-crime before bed.",
    "What my hands can build or wash instead of wring.",
    "The reassurance I keep asking for. Write it once, here.",
    "A future event I am living twice (now and then).",
    "Sleep last night in hours and quality, no drama.",
    "What I ate, and whether my body had fuel.",
    "A social fear in one concrete sentence.",
    "The exit I want versus the stay I can try for ten minutes.",
    "Who is actually unsafe, if anyone.",
    "A mantra I do not believe yet but can borrow.",
    "The tightest muscle. Unclench it on the page.",
    "What I would tell a friend in this exact nervous system.",
    "A plan for 2 a.m. if it comes (light, water, no phone spiral).",
    "The decision I am circling. Name the smallest reversible step.",
    "Where shame piled on top of fear.",
    "A success I discounted because I was braced.",
    "What 'good enough preparation' is for tomorrow.",
    "The body as ally: one signal that was useful.",
    "A clock-out time for problem-solving tonight.",
    "What I made into a referendum on my worth.",
    "Three things that went ordinarily well.",
    "The caffeine cutoff I will actually keep, or won't.",
    "A walk without a podcast, if I took one.",
    "How I spoke to myself in the bathroom mirror.",
    "The appointment I am avoiding. One administrative action.",
    "What I need from medicine / therapy as already prescribed — not a new protocol.",
    "A list of 'maybe' that I will not solve at midnight.",
    "The safest person / pet / place in reach.",
    "What I over-explained.",
    "A sensation I can be curious about for 30 seconds.",
    "The story 'this will last forever' — evidence against.",
    "How I will close the day (not win it).",
    "A tiny exposure I chose, or a rest I needed.",
    "What I will leave undone on purpose.",
    "The difference between intuition and adrenaline.",
    "A night-time rule for the phone.",
    "Who I became in the meeting: freeze, fawn, fight, flight.",
    "A glass of water and a window. Did I?",
    "The worst-case I am feeding. Starve it of detail.",
    "What I can control in a 2-inch radius.",
    "A laugh, even a bitter one.",
    "How I will ask for help without a novel.",
    "The body after the wave. Report, don't grade.",
    "A tomorrow-morning first five minutes that are kind.",
    "What I will not use to numb (be specific).",
    "A calendar item I can move.",
    "The child who learned this alarm. A nod.",
    "One true risk versus ten imaginary ones.",
    "How perfectionism dressed up as anxiety today.",
    "A place my shoulders could drop.",
    "The email I sent too fast or not at all.",
    "What 'safe' means in my house tonight.",
    "A practice I already have (breath, walk, call). Tick if used.",
    "The news I will not finish.",
    "A sentence to the future me at 6 p.m.",
    "Where I compared my inside to their outside.",
    "A meal that was grounding.",
    "The tremor / twitch / skip I noticed and named.",
    "What I need from sleep, not from a miracle.",
    "A no I said, or needed to.",
    "How I will measure today besides 'calm or not'.",
    "The unfinished loop I will park on paper.",
    "A light at the edge of the day.",
    "Today's weather in the nervous system, one word.",
]

HABIT_OS = [
    "If I could only keep one habit this week, which one is identity, not mood?",
    "What environment change is cheaper than more willpower?",
    "Where did I negotiate with myself after 8 p.m.?",
    "The minimum version of the habit on a bad day.",
    "Who is a useful witness, and who is a jury?",
    "What I will stop tracking so the signal gets cleaner.",
    "A cue I can attach to an existing ritual (kettle, keys, teeth).",
    "The story 'I am bad at this' — replace with a process note.",
    "Where friction should go up (make the old thing harder).",
    "Where friction should go down (make the new thing obvious).",
    "A reward that is not a loophole.",
    "What I will do when I miss two days (the repair, not the restart myth).",
]

CLINIC_Q = [
    "What has changed since last visit, in three bullets.",
    "Questions I want answered (not a novel).",
    "Meds / doses as currently prescribed (copy the bottles).",
    "What I need from this appointment.",
    "Follow-ups, labs, refills to request.",
]
