"""Range Band Press Volume 4 — Deep Health Series (titles 73-90).
Each product solves one underdiagnosed problem with a distinct mechanic. Candidate-only.
"""
DEEP = "DEEP HEALTH SERIES"
BX = ["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"]
BXD = ["HEALTH & FITNESS / Diseases / Diabetes", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"]

DEEP_HEALTH = [
dict(n="73", stem="73_Adenomyosis_Fibroid_Ledger", file_interior="73_Adenomyosis_Fibroid_Ledger_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  73",
     cover_title="Adenomyosis &\nFibroid Ledger", cover_title_one="Adenomyosis & Fibroid Ledger",
     subtitle="Bleed wave, pelvic pressure wave,\nand a cycle-window map",
     spine="Adenomyosis & Fibroid Ledger", kdp_title="Adenomyosis & Fibroid Ledger",
     kdp_subtitle="Bleed Intensity, Pelvic Pressure & Cycle-Window Map (Undated Records)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.80, 0.85), ink=(0.18, 0.16, 0.24), panel=(0.93, 0.93, 0.96),
     mechanic="Two waves on one page — bleed intensity and pelvic pressure — plus a cycle-window map that teaches you which days of your cycle are really happening. The record, not the myth.",
     howto=[("Draw two waves", ["Bleed intensity and pelvic pressure, 0-10, plotted as lines. Waves outlive how you felt."]),
            ("Mark the window", ["Tick which cycle window you were in. The window map is the pattern your clinician needs."]),
            ("Records only", ["This book records what happened. It names nothing, advises nothing, diagnoses nothing."])],
     legend=[("B", "bleed wave"), ("P", "pressure wave"), ("W", "window")],
     daily="wave", wave_series=["Bleed intensity", "Pelvic pressure", "Lower back"],
     bullets=["Two daily waves: bleed and pelvic pressure", "Cycle-window tick on every page", "Monthly pattern page — your own geography", "Clinic brief built from the waves"],
     keywords=["adenomyosis journal", "fibroid tracker", "heavy period log", "pelvic pressure diary", "menstrual wave tracker", "uters symptom journal", "undated pelvic pain book"],
     bisac=["HEA028000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Women's Health", "HEALTH & FITNESS / Reference"],
     also=["74 Hashimoto's Thyroid Energy Map", "86 Fibromyalgia Weather Map", "75 Insulin Resistance Wave"],
     hook="Heavy periods are not a personality; they are a pattern. Adenomyosis & Fibroid Ledger draws bleed and pressure as waves, then maps which cycle window is really happening."),

dict(n="74", stem="74_Hashimoto_Thyroid_Energy_Map", file_interior="74_Hashimoto_Thyroid_Energy_Map_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  74",
     cover_title="Hashimoto's & Thyroid\nEnergy Map", cover_title_one="Hashimoto's Thyroid Energy Map",
     subtitle="Morning energy, neck feel, fog and\nmood — one quadrant page",
     spine="Hashimoto's & Thyroid Energy Map", kdp_title="Hashimoto's Thyroid Energy Map",
     kdp_subtitle="Morning Energy, Neck Feel, Fog & Mood Quadrant Map (Undated Records)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.81, 0.86, 0.82), ink=(0.15, 0.23, 0.18), panel=(0.93, 0.95, 0.93),
     mechanic="Four quadrants a day (morning energy, neck feel, fog, mood) plus a monthly temperature-of-everything pattern — autoimmune symptoms move in clusters, and this book catches the cluster.",
     howto=[("Four quadrants", ["Morning energy, neck feel, brain fog, mood — one honest number each."]),
            ("Cluster, not single", ["Autoimmune shifts move together. The quadrant page is how you see the cluster."]),
            ("Lab grid", ["If you add lab results, enter them in the grid. This book interprets nothing."])],
     legend=[("0", "calm"), ("5", "hum"), ("10", "loud")],
     daily="quad", quad_fields=["Morning energy", "Neck feel", "Brain fog", "Mood"],
     bullets=["Four daily quadrants: energy, neck, fog, mood", "Monthly cluster page — symptoms move together", "Lab grid for record-keeping only", "Clinic brief with no interpretation"],
     keywords=["hashimotos journal", "thyroid symptom tracker", "autoimmune energy diary", "hypothyroid log", "brain fog notebook", "thyroid flare tracker", "undated thyroid journal"],
     bisac=["HEA039000", "HEA028000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Women's Health"],
     also=["76 CKD Clinic & Lab Ledger", "89 MS Sensory Map", "90 Eczema & Psoriasis Flare Map"],
     hook="Autoimmune symptoms arrive in clusters, not single file. Hashimoto's Thyroid Energy Map logs four quadrants a day so the cluster shows itself before the clinic appointment does."),

dict(n="75", stem="75_Insulin_Resistance_Wave", file_interior="75_Insulin_Resistance_Wave_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  75",
     cover_title="Insulin Resistance\nWave", cover_title_one="Insulin Resistance Wave",
     subtitle="Satiety arc, energy dip and\nnext-meal hunger — one wave",
     spine="Insulin Resistance Wave", kdp_title="Insulin Resistance Wave",
     kdp_subtitle="Satiety Arc, Energy Dip & Next-Meal Hunger — One Wave Per Day (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.85, 0.83, 0.80), ink=(0.24, 0.18, 0.13), panel=(0.96, 0.94, 0.92),
     mechanic="One satiety arc per day: how full you felt after eating, where energy dipped, and how hungry you were at the next meal — the three numbers that tell the insulin story without a lab.",
     howto=[("Draw the arc", ["Rate satiety through the day: after meal, mid-day, before next. Three dots, one arc."]),
            ("Dip note", ["Mark when energy dipped. The arc listens; it does not lecture."]),
            ("No numbers needed", ["You do not need a meter. The arc is the observation your care team can read."])],
     legend=[("▲", "full"), ("▼", "dip"), ("○", "next meal")],
     daily="wave", wave_series=["Satiety after meal", "Energy mid-day", "Hunger before next meal"],
     bullets=["One satiety arc per day — three dots", "Energy-dip marker", "Next-meal hunger dot", "No meter required; records only"],
     keywords=["insulin resistance journal", "prediabetes log", "blood sugar energy diary", "satiety tracker", "metabolic health journal", "after meal energy log", "undated prediabetes planner"],
     bisac=["HEA039020", "HEA019000"], bisac_names=["HEALTH & FITNESS / Diseases / Diabetes", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
     also=["83 AFib & Anticoagulation Log", "84 Cholesterol Journey", "73 Adenomyosis & Fibroid Ledger"],
     hook="You can feel the insulin story before a lab can name it. Insulin Resistance Wave draws one satiety arc a day — full, dip, next-meal hunger — with no meter and no advice."),

dict(n="76", stem="76_CKD_Clinic_Lab_Ledger", file_interior="76_CKD_Clinic_Lab_Ledger_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  76",
     cover_title="CKD Clinic\n& Lab Ledger", cover_title_one="CKD Clinic & Lab Ledger",
     subtitle="Lab copy sheets, symptom grid\nand appointment brief",
     spine="CKD Clinic & Lab Ledger", kdp_title="CKD Clinic & Lab Ledger",
     kdp_subtitle="Lab Copy Sheets, Symptom Grid & Appointment Brief (Records Only)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.84, 0.82), ink=(0.18, 0.21, 0.17), panel=(0.95, 0.95, 0.93),
     mechanic="Lab copy sheets you keep in one place, a daily symptom grid, and a one-page appointment brief — the binder that turns scattered results into a clinician-friendly story.",
     howto=[("Copy sheets", ["Enter each result as it is given. The sheet is a filing system, not a verdict."]),
            ("Symptom grid", ["Tick what changed: swell, energy, sleep, appetite. Grids are faster than recall."]),
            ("Appointment brief", ["One page: what changed, what I want to ask. The brief is your voice at the desk."])],
     legend=[("L", "lab"), ("G", "grid"), ("A", "brief")],
     daily="ledger", ledger_cols=["Date", "Lab (as given)", "Value", "Note"],
     bullets=["Lab copy sheets — one place for the record", "Daily symptom grid: swell, energy, sleep, appetite", "One-page appointment brief", "Question list built for the next visit"],
     keywords=["ckd journal", "kidney disease tracker", "renal lab log", "chronic kidney diary", "creatinine log", "nephrology planner", "undated kidney health book"],
     bisac=["HEA039000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"],
     also=["77 Dialysis Session Log", "74 Hashimoto's Thyroid Energy Map", "55 Symptom Detective Kit"],
     hook="Chronic kidney care is a filing system as much as a medical one. CKD Clinic & Lab Ledger keeps lab copies, a symptom grid, and a one-page appointment brief in one binder — records, not verdicts."),

dict(n="77", stem="77_Dialysis_Session_Log", file_interior="77_Dialysis_Session_Log_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  77",
     cover_title="Dialysis\nSession Log", cover_title_one="Dialysis Session Log",
     subtitle="Pre/post weight ladder, treatment-day\nfeel ring, transport check",
     spine="Dialysis Session Log", kdp_title="Dialysis Session Log",
     kdp_subtitle="Pre/Post Weight Ladder, Treatment-Day Feel & Transport Check (Undated)",
     tagline="Sixty undated sessions  ·  6 × 9 in", days=60, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.83, 0.87), ink=(0.15, 0.20, 0.28), panel=(0.93, 0.95, 0.97),
     mechanic="Two-page session spread: pre/post weight ladder, a treatment-day feel ring, and a transport check — so the routine is runnable and the questions are collected.",
     howto=[("Ladder", ["Record pre and post weights as the team gives them. The ladder is the record."]),
            ("Feel ring", ["One ring for how the day felt — before, during, after. No grading, just shape."]),
            ("Transport check", ["Who picked you up, what you brought, what to ask. The routine stays routine."])],
     legend=[("↑", "pre"), ("↓", "post"), ("○", "feel")],
     daily="ladder", ladder_steps=["Weight before", "Weight after", "Treatment felt", "Transport / notes"],
     bullets=["Pre/post weight ladder per session", "Treatment-day feel ring", "Transport check — routine stays routine", "Question box for the care team"],
     keywords=["dialysis journal", "dialysis log book", "kidney treatment diary", "hemodialysis tracker", "renal patient planner", "clinic visit notebook", "undated dialysis log"],
     bisac=["HEA039000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"],
     also=["76 CKD Clinic & Lab Ledger", "80 Restless Legs & Sleep Pressure", "82 Insomnia & Restedness Map"],
     hook="Dialysis routines run on small details. Dialysis Session Log turns each session into a pre/post ladder, a feel ring, and a transport check — so the routine stays runnable."),

dict(n="78", stem="78_COPD_Breath_Scale", file_interior="78_COPD_Breath_Scale_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  78",
     cover_title="COPD\nBreath Scale", cover_title_one="COPD Breath Scale",
     subtitle="Breathlessness ladder, inhaler use as\ndirected, air-quality tick",
     spine="COPD Breath Scale", kdp_title="COPD Breath Scale",
     kdp_subtitle="Breathlessness Ladder, Inhaler Use As Directed & Air Tick (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.82, 0.82), ink=(0.15, 0.20, 0.20), panel=(0.93, 0.94, 0.94),
     mechanic="Breathlessness ladder 0-10 with a 'was it a good day for air' tick — the scale that turns 'I was short' into a number and a pattern your pulmonologist can read.",
     howto=[("Ladder", ["Rate breathlessness at morning, midday, night. Ladders beat adjectives."]),
            ("As directed", ["Record inhaler use exactly as directed. This book never adjusts."]),
            ("Air tick", ["Humidity, smoke, pollen, season — tick what air looked like. Air is context, not judgment."])],
     legend=[("0", "fine"), ("5", "short"), ("10", "very short")],
     daily="hist", hist_rows=["Breath 0-10", "Inhaler (as directed)", "Air tick", "Note"],
     bullets=["Breathlessness ladder — morning, midday, night", "Inhaler record as directed only", "Air tick: humidity, smoke, pollen, season", "Weekly breath pattern for the clinic"],
     keywords=["copd journal", "breathlessness tracker", "pulmonary log", "lung function diary", "inhaler tracker", "shortness of breath journal", "undated respiratory log"],
     bisac=["HEA039000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"],
     also=["79 Asthma Wind & Trigger Log", "80 Restless Legs & Sleep Pressure", "82 Insomnia & Restedness Map"],
     hook="'I was short of breath' is not a measurement. COPD Breath Scale scores it on a 0-10 ladder, records inhalers as directed, and ticks what the air was doing that day."),

dict(n="79", stem="79_Asthma_Wind_Trigger_Log", file_interior="79_Asthma_Wind_Trigger_Log_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  79",
     cover_title="Asthma Wind\n& Trigger Log", cover_title_one="Asthma Wind & Trigger Log",
     subtitle="Breath wind line, trigger constellation,\nreliever use as directed",
     spine="Asthma Wind & Trigger Log", kdp_title="Asthma Wind & Trigger Log",
     kdp_subtitle="Breath-Wind Line, Trigger Constellation & Reliever As Directed (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.82, 0.80), ink=(0.22, 0.17, 0.13), panel=(0.95, 0.93, 0.91),
     mechanic="Breath-wind line (0-10) plus a trigger constellation — pollen, dust, exercise, cold, stress, smoke — with reliever use logged as directed. The constellation is what the inhaler doesn't tell you.",
     howto=[("Wind line", ["One 0-10 breath number per day on the line."]),
            ("Constellation", ["Tick the triggers that were around. Dots make a shape; shapes make a clue."]),
            ("As directed", ["Log reliever use exactly as directed. Record, never adjust."])],
     legend=[("0", "breezy"), ("5", "windy"), ("10", "storm")],
     daily="hist", hist_rows=["Breath 0-10", "Reliever (as directed)", "Trigger tick", "Note"],
     bullets=["Breath-wind line 0-10 daily", "Trigger constellation: pollen, dust, exercise, cold, stress", "Reliever logged as directed", "Monthly constellation review"],
     keywords=["asthma journal", "asthma trigger tracker", "breath wind log", "inhaler use diary", "pollen symptom journal", "respiratory diary", "undated asthma planner"],
     bisac=["HEA039000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"],
     also=["78 COPD Breath Scale", "85 Post-Concussion Recovery Map", "89 MS Sensory Map"],
     hook="An inhaler treats the airway; it cannot see the trigger. Asthma Wind & Trigger Log plots a breath-wind line and a trigger constellation so the pattern gets a shape."),

dict(n="80", stem="80_Restless_Legs_Sleep_Pressure", file_interior="80_Restless_Legs_Sleep_Pressure_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  80",
     cover_title="Restless Legs &\nSleep Pressure", cover_title_one="Restless Legs & Sleep Pressure",
     subtitle="Leg urge ladder, morning and night,\nplus a sleep-pressure gauge",
     spine="Restless Legs & Sleep Pressure", kdp_title="Restless Legs & Sleep Pressure",
     kdp_subtitle="Leg-Urge Ladder, Evening Activity Map & Sleep-Pressure Gauge (Undated)",
     tagline="Sixty undated days  ·  6 × 9 in", days=60, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.80, 0.83), ink=(0.16, 0.16, 0.22), panel=(0.93, 0.93, 0.96),
     mechanic="Two leg-urge ladders (morning and night) plus a sleep-pressure gauge and an evening-activity map — restless legs are about the evening, and this book watches the evening.",
     howto=[("Two ladders", ["Urge in the morning, urge at night. The gap is the story."]),
            ("Evening map", ["What you did in the two hours before bed: walk, sit, screen, bath. Map, not verdict."]),
            ("Sleep pressure", ["One gauge of how sleep also felt. Pressure is data, not failure."])],
     legend=[("AM", "urge"), ("PM", "urge"), ("○", "pressure")],
     daily="gauge2", gauge_fields=["Leg urge AM", "Leg urge PM", "Sleep onset", "Restedness"],
     bullets=["Leg-urge ladder: morning and night", "Evening activity map before bed", "Sleep-pressure gauge", "Weekly rest pattern"],
     keywords=["restless legs journal", "rls tracker", "leg urge diary", "sleep disturbance log", "evening restlessness notebook", "periodic limb movement log", "undated rls planner"],
     bisac=["HEA043000", "HEA039050"], bisac_names=["HEALTH & FITNESS / Sleep", "HEALTH & FITNESS / Diseases / Nervous System"],
     also=["82 Insomnia & Restedness Map", "81 Narcolepsy Sleep Pressure", "78 COPD Breath Scale"],
     hook="Restless legs happen at the edge of sleep, where memory is worst. Restless Legs & Sleep Pressure tracks the urge morning and night, maps the evening, and gauges how sleep actually landed."),

dict(n="81", stem="81_Narcolepsy_Sleep_Pressure", file_interior="81_Narcolepsy_Sleep_Pressure_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  81",
     cover_title="Narcolepsy & Sleep\nPressure Blotter", cover_title_one="Narcolepsy Sleep Pressure Blotter",
     subtitle="Sleep-pressure clock, nap blotter,\nand a day-sleep map",
     spine="Narcolepsy Sleep Pressure Blotter", kdp_title="Narcolepsy Sleep Pressure Blotter",
     kdp_subtitle="Sleep-Pressure Clock, Nap Blotter & Day-Sleep Map (Undated Records)",
     tagline="Sixty undated days  ·  6 × 9 in", days=60, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.83, 0.86), ink=(0.18, 0.18, 0.25), panel=(0.94, 0.94, 0.97),
     mechanic="A 24-hour sleep-pressure clock shaded by hour, plus a nap blotter and a day-sleep map — so 'I keep falling asleep' becomes a time of day, not a complaint.",
     howto=[("Shade the clock", ["Shade when sleep pressure was high. The clock turns a vague complaint into hours."]),
            ("Nap blotter", ["Each nap: time, length, felt. Blotters are quick and honest."]),
            ("Day map", ["Mark what you were doing when sleep hit. Context is the clue; this book draws no conclusion."])],
     legend=[("0", "low"), ("5", "high"), ("10", "collapse")],
     daily="blotter", blotter_fields=["Time of pressure", "What I was doing", "Length", "How I felt after"],
     bullets=["24-hour sleep-pressure clock, shaded hourly", "Nap blotter — time, length, felt", "Day-sleep activity map", "Weekly pressure review for the care team"],
     keywords=["narcolepsy journal", "sleep attack log", "excessive sleepiness diary", "nap tracker", "sleep pressure notebook", "hypersomnia journal", "undated sleep disorder log"],
     bisac=["HEA043000", "HEA039050"], bisac_names=["HEALTH & FITNESS / Sleep", "HEALTH & FITNESS / Diseases / Nervous System"],
     also=["80 Restless Legs & Sleep Pressure", "82 Insomnia & Restedness Map", "89 MS Sensory Map"],
     hook="Excessive sleepiness is a time of day before it is a diagnosis. Narcolepsy Sleep Pressure Blotter shades a 24-hour clock and blots each nap, turning a complaint into a pattern."),

dict(n="82", stem="82_Insomnia_Restedness_Map", file_interior="82_Insomnia_Restedness_Map_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  82",
     cover_title="Insomnia &\nRestedness Map", cover_title_one="Insomnia & Restedness Map",
     subtitle="Bedtime hour wheel, WASO count,\nand a restedness gauge",
     spine="Insomnia & Restedness Map", kdp_title="Insomnia & Restedness Map",
     kdp_subtitle="Bedtime Hour Wheel, WASO Count & Restedness Gauge (Undated Records)",
     tagline="Sixty undated days  ·  6 × 9 in", days=60, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.84, 0.88), ink=(0.17, 0.20, 0.28), panel=(0.93, 0.95, 0.97),
     mechanic="A bedtime-hour wheel, a WASO (wake-after-sleep-onset) count, and a restedness gauge — the three numbers that separate 'I didn't sleep' from 'I slept but didn't rest'.",
     howto=[("Wheel", ["Shade the hour you actually got into bed. The wheel is honest; the plan is not yours to make."]),
            ("WASO count", ["Count the wakes, not the minutes. Count beats 'all night'."]),
            ("Restedness", ["One gauge of how rested the day felt. Rest and sleep are different numbers."])],
     legend=[("0", "rested"), ("5", "okay"), ("10", "not")],
     daily="wheel", wheel_rings=["Bedtime hour", "WASO count", "Awake minutes", "Restedness"],
     bullets=["Bedtime-hour wheel", "WASO count (wakes, not minutes)", "Restedness gauge", "Weekly sleep shape review"],
     keywords=["insomnia journal", "sleep tracker notebook", "waso log", "bedtime wheel diary", "restedness tracker", "sleep quality journal", "undated insomnia log"],
     bisac=["HEA043000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Sleep", "HEALTH & FITNESS / Reference"],
     also=["80 Restless Legs & Sleep Pressure", "81 Narcolepsy Sleep Pressure", "78 COPD Breath Scale"],
     hook="There are two different failures: not sleeping, and not resting. Insomnia & Restedness Map records the bedtime hour wheel, the wake count, and a restedness gauge — so you know which one you're fighting."),

dict(n="83", stem="83_AFib_Anticoagulation_Log", file_interior="83_AFib_Anticoagulation_Log_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  83",
     cover_title="AFib &\nAnticoagulation Log", cover_title_one="AFib & Anticoagulation Log",
     subtitle="Palpitation blotter, pulse wave,\ndose as directed only",
     spine="AFib & Anticoagulation Log", kdp_title="AFib & Anticoagulation Log",
     kdp_subtitle="Palpitation Blotter, Pulse Wave & Dose As Directed (Undated Records)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.82, 0.80), ink=(0.23, 0.18, 0.14), panel=(0.95, 0.93, 0.92),
     mechanic="Palpitation blotter (time, what you were doing, how long) plus a daily pulse wave and a dose-as-directed log — the blotter catches the irregular, the wave shows the ordinary.",
     howto=[("Blotter", ["Each palpitation: time, activity, duration. Blotter, not diary."]),
            ("Pulse wave", ["One pulse number per day on the wave. The wave is context; the clinician reads it."]),
            ("As directed", ["Record the anticoagulant dose exactly as directed. This book never adjusts."])],
     legend=[("P", "palpitation"), ("W", "pulse wave"), ("✓", "as directed")],
     daily="blotter", blotter_fields=["Time", "What I was doing", "How long", "Pulse (as taken)"],
     bullets=["Palpitation blotter: time, activity, duration", "Daily pulse wave", "Dose recorded as directed only", "Monthly rhythm review"],
     keywords=["afib journal", "atrial fibrillation tracker", "palpitation diary", "anticoagulation log", "heart rhythm notebook", "blood thinner tracker", "undated heart log"],
     bisac=["HEA007000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Heart", "HEALTH & FITNESS / Reference"],
     also=["84 Cholesterol Journey", "87 Sjogren's Dryness Map", "89 MS Sensory Map"],
     hook="An irregular heartbeat needs a blotter, not a story. AFib & Anticoagulation Log blots each palpitation, plots a pulse wave, and records medication exactly as directed."),

dict(n="84", stem="84_Cholesterol_Journey", file_interior="84_Cholesterol_Journey_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  84",
     cover_title="Cholesterol &\nStatin Journey", cover_title_one="Cholesterol & Statin Journey",
     subtitle="Lab trend bars, muscle/energy side\nlog, and a food note",
     spine="Cholesterol & Statin Journey", kdp_title="Cholesterol & Statin Journey",
     kdp_subtitle="Lab Trend Bars, Muscle-Energy Side Log & Food Note (Records Only)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.81, 0.83), ink=(0.18, 0.17, 0.22), panel=(0.94, 0.93, 0.95),
     mechanic="A lab-trend bar per result plus a muscle/energy side log — the two things a statin conversation actually needs: numbers over time and how the body answered.",
     howto=[("Trend bars", ["Enter each lab result as a bar. Bars compare; no conclusions."]),
            ("Side log", ["Muscle feel and energy, daily. The side log gives the clinician the whole answer, not the headline."]),
            ("Food note", ["One line, no diet advice. Food is context, never a prescription."])],
     legend=[("L", "lab"), ("M", "muscle"), ("F", "food")],
     daily="hist", hist_rows=["Lab number (as given)", "Muscle feel 0-10", "Energy 0-10", "Food note"],
     bullets=["Lab trend bars — one place", "Muscle/energy side log daily", "One-line food note", "Statin conversation prep page"],
     keywords=["cholesterol tracker", "statin journal", "lipid log", "lab results notebook", "muscle energy diary", "lipid tracking notebook", "undated lipid planner"],
     bisac=["HEA007000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Heart", "HEALTH & FITNESS / Reference"],
     also=["83 AFib & Anticoagulation Log", "75 Insulin Resistance Wave", "47 Cardiac Rhythm & BP Wave"],
     hook="A statin conversation needs two things: numbers over time and how the body answered. Cholesterol Journey trends the labs and logs muscle and energy so the discussion has a full record."),

dict(n="85", stem="85_PostConcussion_Recovery_Map", file_interior="85_PostConcussion_Recovery_Map_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  85",
     cover_title="Post-Concussion\nRecovery Map", cover_title_one="Post-Concussion Recovery Map",
     subtitle="Headache, light/noise, focus quadrants\nand a rest gate",
     spine="Post-Concussion Recovery Map", kdp_title="Post-Concussion Recovery Map",
     kdp_subtitle="Headache, Light-Noise, Focus Quadrants & Rest Gate (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.83, 0.84), ink=(0.15, 0.21, 0.22), panel=(0.93, 0.95, 0.95),
     mechanic="Four quadrants (headache, light/noise, focus, rest gate) plus a 'what made it worse' line — concussion recovery is a load management problem, and the gate is the load.",
     howto=[("Quadrants", ["Headache, light/noise, focus, rest gate — one number each. Recovery moves in quadrants, not verdicts."]),
            ("Gate", ["The rest gate is a check-in: did I push, coast, or stop? The gate is not a grade."]),
            ("Worse line", ["One line on what made it worse. The line keeps the plan honest."])],
     legend=[("0", "clear"), ("5", "fog"), ("10", "loud")],
     daily="quad", quad_fields=["Headache", "Light/noise", "Focus", "Rest gate"],
     bullets=["Four recovery quadrants per day", "Rest gate: push, coast, stop", "'What made it worse' line", "Weekly return note — evidence, not guesswork"],
     keywords=["concussion journal", "post concussion tracker", "brain injury recovery log", "mild tbi diary", "headache fog journal", "concussion recovery planner", "undated brain rest log"],
     bisac=["HEA039050", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / Nervous System", "HEALTH & FITNESS / Reference"],
     also=["89 MS Sensory Map", "96 Flashback & Grounding", "86 Fibromyalgia Weather Map"],
     hook="Concussion recovery is load management, and load needs a gate. Post-Concussion Recovery Map runs four quadrants, a push-coast-stop gate, and a line for what made it worse."),

dict(n="86", stem="86_Fibromyalgia_Weather_Map", file_interior="86_Fibromyalgia_Weather_Map_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  86",
     cover_title="Fibromyalgia\nWeather Map", cover_title_one="Fibromyalgia Weather Map",
     subtitle="Tender-point heat map, barometric\ntick, and a storm-shaped week",
     spine="Fibromyalgia Weather Map", kdp_title="Fibromyalgia Weather Map",
     kdp_subtitle="Tender-Point Heat Map, Barometric Tick & Storm-Shaped Week (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.83, 0.86), ink=(0.20, 0.18, 0.26), panel=(0.95, 0.94, 0.97),
     mechanic="Tender-point heat map plus a weather tick (pressure, temp, rain) and a storm-shaped week — fibromyalgia lives at the intersection of body and weather, and this book watches both.",
     howto=[("Heat map", ["Shade each tender area 0-3. The map is the body's weather report."]),
            ("Weather tick", ["What did the sky do? The tick is context, not cause."]),
            ("Storm shape", ["One line per week: did the week feel like a storm, drizzle, or clear? Shape, not score."])],
     legend=[("0", "calm"), ("1", "tender"), ("2", "aching"), ("3", "loud")],
     daily="map", zones=["Neck", "Shoulders", "Upper back", "Lower back", "Hips", "Knees", "Hands", "Feet"],
     bullets=["Tender-point heat map, 0-3", "Weather tick: pressure, temp, rain", "Storm-shaped week review", "Monthly pattern page"],
     keywords=["fibromyalgia journal", "fibro tracker", "tender points log", "chronic pain weather diary", "widespread pain journal", "body pain flare map", "undated fibromyalgia planner"],
     bisac=["HEA009000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Pain Management", "HEALTH & FITNESS / Reference"],
     also=["87 Sjogren's Dryness Map", "90 Eczema & Psoriasis Flare Map", "89 MS Sensory Map"],
     hook="Fibromyalgia is a weather system with a body. Fibromyalgia Weather Map shades tender points, ticks the sky, and draws the week as storm, drizzle, or clear."),

dict(n="87", stem="87_Sjogren_Dryness_Map", file_interior="87_Sjogren_Dryness_Map_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  87",
     cover_title="Sjogren's\nDryness Map", cover_title_one="Sjogren's Dryness Map",
     subtitle="Eye/mouth/skin dryness clock,\nfatigue wave, lab grid",
     spine="Sjogren's Dryness Map", kdp_title="Sjogren's Dryness Map",
     kdp_subtitle="Eye-Mouth-Skin Dryness Clock, Fatigue Wave & Lab Grid (Undated Records)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.85, 0.83), ink=(0.19, 0.22, 0.17), panel=(0.95, 0.95, 0.94),
     mechanic="A dryness clock (eyes, mouth, skin at morning/noon/night) plus a fatigue wave and a lab grid — dry is not one feeling; it is three clocks you learn to read.",
     howto=[("Three clocks", ["Eyes, mouth, skin — tick dryness at three times of day. The clocks separate the dryness you can fix from the dryness you can't."]),
            ("Fatigue wave", ["One fatigue line per day. Dryness and fatigue move on different waves."]),
            ("Lab grid", ["Enter results as given. The grid holds facts; the page interprets nothing."])],
     legend=[("E", "eyes"), ("M", "mouth"), ("S", "skin"), ("F", "fatigue")],
     daily="map", zones=["Eyes", "Mouth", "Skin", "Joints", "Fatigue"],
     bullets=["Dryness clock: eyes, mouth, skin × morning/noon/night", "Fatigue wave daily", "Lab results grid — records only", "Monthly dryness pattern"],
     keywords=["sjogrens journal", "dry eye tracker", "dry mouth log", "autoimmune dryness diary", "fatigue dry journal", "sjogren symptom book", "undated dryness planner"],
     bisac=["HEA039000", "HEA028000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Women's Health"],
     also=["86 Fibromyalgia Weather Map", "88 Scleroderma Raynaud's Log", "90 Eczema & Psoriasis Flare Map"],
     hook="Dryness is not one feeling; it is three clocks. Sjogren's Dryness Map tracks eyes, mouth, and skin at morning, noon, and night, then draws the fatigue wave on a separate line."),

dict(n="88", stem="88_Scleroderma_Raynaud_Log", file_interior="88_Scleroderma_Raynaud_Log_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  88",
     cover_title="Scleroderma & Raynaud's\nLog", cover_title_one="Scleroderma Raynaud's Log",
     subtitle="Raynaud episode blotter, finger color\nmenu, skin-tightness scale",
     spine="Scleroderma & Raynaud's Log", kdp_title="Scleroderma & Raynaud's Log",
     kdp_subtitle="Raynaud Episode Blotter, Finger Color Menu & Skin-Tightness Scale (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.82, 0.81), ink=(0.15, 0.20, 0.17), panel=(0.93, 0.94, 0.94),
     mechanic="Raynaud episode blotter (trigger, duration, finger color from a menu) plus a skin-tightness scale — the two signals that move together in scleroderma.",
     howto=[("Blotter", ["Each episode: cold/stress trigger, duration, color. The blotter is the cold's fingerprint."]),
            ("Color menu", ["White, blue, then red — tick the color. The menu makes the progression readable."]),
            ("Tightness scale", ["Skin tightness 0-3. Separate from the fingers; they are different information."])],
     legend=[("W", "white"), ("B", "blue"), ("R", "red")],
     daily="blotter", blotter_fields=["Time", "Trigger: cold/stress", "Duration", "Color W/B/R"],
     bullets=["Raynaud episode blotter — trigger, duration, color", "Finger color menu: white, blue, red", "Skin-tightness scale 0-3", "Monthly circulation pattern"],
     keywords=["raynauds journal", "scleroderma log", "raynaud episode tracker", "cold hands diary", "skin tightness journal", "autoimmune circulation log", "undated raynauds planner"],
     bisac=["HEA039000", "HEA009000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Pain Management"],
     also=["87 Sjogren's Dryness Map", "89 MS Sensory Map", "86 Fibromyalgia Weather Map"],
     hook="Raynaud's is a fingerprint, not a complaint. Scleroderma & Raynaud's Log blots each episode, ticks the color progression, and scales skin tightness on its own line."),

dict(n="89", stem="89_MS_Sensory_Map", file_interior="89_MS_Sensory_Map_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  89",
     cover_title="MS Sensory\nMap", cover_title_one="MS Sensory Map",
     subtitle="Vision, hands, legs, balance, heat —\none constellation per week",
     spine="MS Sensory Map", kdp_title="MS Sensory Map",
     kdp_subtitle="Vision, Hands, Legs, Balance & Heat Constellation (Undated Records)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.83, 0.87), ink=(0.17, 0.19, 0.28), panel=(0.93, 0.94, 0.97),
     mechanic="A weekly sensory constellation — vision, hands, legs, balance, heat — with daily symptom dots. MS symptoms scatter; the constellation gathers them into a shape the neurologist can read.",
     howto=[("Daily dots", ["One dot per symptom that speaks today. Dots are honest; adjectives leak."]),
            ("Weekly constellation", ["Join the dots each Sunday. The shape is the clue, and you don't have to interpret it."]),
            ("Heat line", ["Tick how the weather felt. Heat is context, not cause."])],
     legend=[("0", "quiet"), ("5", "present"), ("10", "loud")],
     daily="map", zones=["Vision", "Hands", "Legs", "Balance", "Heat"],
     bullets=["Daily sensory dots: vision, hands, legs, balance, heat", "Weekly constellation — join your own dots", "Heat/weather tick", "Monthly pattern for the neurologist"],
     keywords=["multiple sclerosis journal", "ms symptom tracker", "sensory map diary", "neuro symptom log", "ms flare notebook", "balance fatigue journal", "undated ms planner"],
     bisac=["HEA039050", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / Nervous System", "HEALTH & FITNESS / Reference"],
     also=["85 Post-Concussion Recovery Map", "88 Scleroderma Raynaud's Log", "86 Fibromyalgia Weather Map"],
     hook="MS symptoms scatter; the record should gather them. MS Sensory Map dots the daily symptoms, then joins them into a weekly constellation your neurologist can actually read."),

dict(n="90", stem="90_Eczema_Psoriasis_Flare_Map", file_interior="90_Eczema_Psoriasis_Flare_Map_interior.pdf",
     series=DEEP, series_short="DEEP HEALTH  ·  90",
     cover_title="Eczema & Psoriasis\nFlare Map", cover_title_one="Eczema & Psoriasis Flare Map",
     subtitle="Itch wave, skin-patch map, trigger\nconstellation and a care log",
     spine="Eczema & Psoriasis Flare Map", kdp_title="Eczema & Psoriasis Flare Map",
     kdp_subtitle="Itch Wave, Skin-Patch Map, Trigger Constellation & Care Log (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.82, 0.81), ink=(0.23, 0.17, 0.15), panel=(0.95, 0.93, 0.92),
     mechanic="An itch wave (0-10), a skin-patch map (scalp, hands, elbows, knees, torso, legs), a trigger constellation, and a care log — the flare gets four ways to be described.",
     howto=[("Itch wave", ["One itch number per day on the wave. Itch moves in waves, not moods."]),
            ("Patch map", ["Shade where the patches were. Maps beat 'everywhere'."]),
            ("Care log", ["Record what you applied exactly as directed. The log holds the facts."])],
     legend=[("0", "clear"), ("5", "itchy"), ("10", "driving")],
     daily="map", zones=["Scalp", "Hands", "Elbows", "Knees", "Torso", "Legs"],
     bullets=["Itch wave 0-10 daily", "Skin-patch map: scalp, hands, elbows, knees, torso, legs", "Trigger constellation", "Care log as directed"],
     keywords=["eczema journal", "psoriasis tracker", "itch log book", "skin flare diary", "atopic dermatitis journal", "flare map notebook", "undated skin diary"],
     bisac=["HEA039000", "HEA009000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Pain Management"],
     also=["86 Fibromyalgia Weather Map", "87 Sjogren's Dryness Map", "88 Scleroderma Raynaud's Log"],
     hook="A flare has a shape and a wave, and 'everywhere' describes neither. Eczema & Psoriasis Flare Map tracks the itch wave, patches the skin map, and logs care as directed."),
]
