"""Range Band Press Volume 4 — Life Range Series (titles 91-108).
Neurodivergent life, grief, and transition niches — each with a distinct mechanic.
"""
LIFE = "LIFE RANGE SERIES"

LIFE_RANGE = [
dict(n="91", stem="91_ADHD_Task_Paralysis_Planner", file_interior="91_ADHD_Task_Paralysis_Planner_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  91",
     cover_title="ADHD Task\nParalysis Planner", cover_title_one="ADHD Task Paralysis Planner",
     subtitle="Inertia meter, smallest-step box\nand a five-minute ramp",
     spine="ADHD Task Paralysis Planner", kdp_title="ADHD Task Paralysis Planner",
     kdp_subtitle="Inertia Meter, Smallest-Step Box & 5-Minute Ramp (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.85, 0.82), ink=(0.18, 0.23, 0.18), panel=(0.94, 0.96, 0.94),
     mechanic="Inertia meter first (0-10), then the smallest step that isn't the task, then a five-minute ramp — you do not start the mountain, you start the smallest step in front of it.",
     howto=[("Meter the inertia", ["Rate paralysis before you plan. Naming it is the first unblock."]),
            ("Smallest step", ["Write one step smaller than you think is allowed. A step is allowed to be tiny."]),
            ("Five-minute ramp", ["Run five minutes, then decide. The ramp is not a promise; it is a test drive."])],
     legend=[("0", "rolling"), ("5", "stuck"), ("10", "frozen")],
     daily="meter", meter_fields=["Inertia 0-10", "Smallest step", "Five-minute ramp", "Done? ✓"],
     bullets=["Inertia meter before planning", "Smallest-step box — smaller than allowed", "Five-minute ramp, then decide", "'Done' box is for showing up, not finishing"],
     keywords=["task paralysis journal", "adhd execution planner", "executive dysfunction workbook", "adhd inertia tracker", "smallest step planner", "adhd adult journal", "undated adhd routine book"],
     bisac=["SEL032000", "PSY022000"], bisac_names=["SELF-HELP / Journaling", "PSYCHOLOGY / Psychopathology / Anxiety Disorders"],
     also=["92 Autistic Burnout Ledger", "106 Neurodivergent Routine Map", "93 Sensory Overload Kit"],
     hook="ADHD paralysis is not laziness; it is a stuck engine. Task Paralysis Planner meters the inertia, picks a smallest step smaller than allowed, and runs a five-minute ramp."),

dict(n="92", stem="92_Autistic_Burnout_Ledger", file_interior="92_Autistic_Burnout_Ledger_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  92",
     cover_title="Autistic Burnout\nRecovery Ledger", cover_title_one="Autistic Burnout Recovery Ledger",
     subtitle="Capacity bands, sensory load count\nand a recovery-steps map",
     spine="Autistic Burnout Recovery Ledger", kdp_title="Autistic Burnout Recovery Ledger",
     kdp_subtitle="Capacity Bands, Sensory-Load Count & Recovery Steps Map (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.82, 0.86), ink=(0.21, 0.17, 0.26), panel=(0.95, 0.93, 0.96),
     mechanic="Capacity bands (green / yellow / red) instead of grades, a sensory-load count, and a zero-pressure recovery-steps map — burnout recovery is capacity management, not a to-do list.",
     howto=[("Band, not grade", ["Green: full. Yellow: half. Red: rest. Bands are information, not failure."]),
            ("Load count", ["Count sensory inputs: noise, crowds, screens, demands. Load is the number that matters."]),
            ("Recovery steps", ["Choose one from the map: quiet, stim, rest, exit. The map is permission, not a protocol."])],
     legend=[("G", "full"), ("Y", "half"), ("R", "rest")],
     daily="capacity", capacity_fields=["Capacity band", "Sensory load", "One recovery act", "What changed the band"],
     bullets=["Capacity bands instead of grades", "Sensory-load count daily", "Zero-pressure recovery map", "'What changed the band' note"],
     keywords=["autistic burnout journal", "autism recovery planner", "sensory load tracker", "neurodivergent burnout book", "masking fatigue diary", "autism adult journal", "undated burnout recovery log"],
     bisac=["SEL032000", "PSY022000"], bisac_names=["SELF-HELP / Journaling", "PSYCHOLOGY / Psychopathology / Anxiety Disorders"],
     also=["93 Sensory Overload Kit", "91 ADHD Task Paralysis Planner", "106 Neurodivergent Routine Map"],
     hook="Autistic burnout is capacity, not attitude. Autistic Burnout Recovery Ledger replaces grades with bands, counts sensory load, and maps recovery steps that require nothing."),

dict(n="93", stem="93_Sensory_Overload_Emergency_Kit", file_interior="93_Sensory_Overload_Emergency_Kit_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  93",
     cover_title="Sensory Overload\nEmergency Kit", cover_title_one="Sensory Overload Emergency Kit",
     subtitle="Overwhelm dial, exit map, stim menu\nand aftercare",
     spine="Sensory Overload Emergency Kit", kdp_title="Sensory Overload Emergency Kit",
     kdp_subtitle="Overwhelm Dial, Exit Map, Stim Menu & Aftercare (Undated)",
     tagline="Sixty undated days  ·  6 × 9 in", days=60, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.84, 0.88), ink=(0.16, 0.20, 0.28), panel=(0.93, 0.95, 0.97),
     mechanic="An overwhelm dial, a pre-planned exit map (what is around you, what you can leave), a stim menu you choose from, and an aftercare line — the kit that makes overwhelm survivable in the moment.",
     howto=[("Dial", ["Rate overwhelm 0-10. If it is past 7, the kit is in play."]),
            ("Exit map", ["Before the moment, write what is around you. An exit you have mapped is an exit you can take."]),
            ("Stim menu", ["Pick from your own menu: rock, hum, squeeze, leave. Stimming is a tool, not a secret."])],
     legend=[("0", "okay"), ("7", "overloaded"), ("10", "shutdown")],
     daily="blotter", blotter_fields=["Trigger", "Overwhelm 0-10", "Exit map used", "Aftercare"],
     bullets=["Overwhelm dial before it peaks", "Pre-mapped exit — written once", "Stim menu chosen by you", "Aftercare line, no shame"],
     keywords=["sensory overload journal", "overstimulation tracker", "autism meltdown planner", "sensory overwhelm kit", "stim menu journal", "neurodivergent sensory log", "undated overwhelm diary"],
     bisac=["PSY022000", "SEL032000"], bisac_names=["PSYCHOLOGY / Psychopathology / Anxiety Disorders", "SELF-HELP / Journaling"],
     also=["92 Autistic Burnout Ledger", "97 Dissociation Grounding Map", "98 Panic Drill Log"],
     hook="Overwhelm is survivable if the exit is mapped before the moment. Sensory Overload Emergency Kit puts a dial, a written exit map, and your own stim menu on the page."),

dict(n="94", stem="94_Rejection_Sensitivity_Radar", file_interior="94_Rejection_Sensitivity_Radar_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  94",
     cover_title="Rejection\nSensitivity Radar", cover_title_one="Rejection Sensitivity Radar",
     subtitle="Event log, internal replay, evidence\ncheck — three columns",
     spine="Rejection Sensitivity Radar", kdp_title="Rejection Sensitivity Radar",
     kdp_subtitle="Event Log, Internal Replay & Evidence Check (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.85, 0.82, 0.82), ink=(0.25, 0.16, 0.18), panel=(0.96, 0.93, 0.93),
     mechanic="Three-column courtroom for RSD: what actually happened, the replay in your head, and the evidence check — the radar separates the feeling from the fact.",
     howto=[("What happened", ["Facts only: who, what, when. No interpretation."]),
            ("The replay", ["Write what your brain played. The replay is a recording, not a verdict."]),
            ("Evidence check", ["One question: what did the person actually say or do? Evidence ends the loop."])],
     legend=[("F", "fact"), ("R", "replay"), ("E", "evidence")],
     daily="court", court_cols=["What happened", "The replay", "Evidence check"],
     bullets=["Three-column event log", "Internal replay named separately", "Evidence check question", "Self-kindness line after the check"],
     keywords=["rejection sensitivity journal", "rsd tracker", "rejection dysphoria workbook", "adhd emotional log", "self esteem evidence journal", "rumination diary", "undated rsd planner"],
     bisac=["PSY022000", "SEL032000"], bisac_names=["PSYCHOLOGY / Psychopathology / Anxiety Disorders", "SELF-HELP / Journaling"],
     also=["91 ADHD Task Paralysis Planner", "95 Intrusive Thought Ledger", "97 Dissociation Grounding Map"],
     hook="Rejection sensitivity runs on the replay, not the event. Rejection Sensitivity Radar separates what happened from the recording in your head, then checks the evidence once."),

dict(n="95", stem="95_Intrusive_Thought_Compulsion_Ledger", file_interior="95_Intrusive_Thought_Compulsion_Ledger_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  95",
     cover_title="Intrusive Thought\nReframe Ledger", cover_title_one="Intrusive Thought Reframe Ledger",
     subtitle="Urge meter, thought label and\na therapist-directed bounce-back",
     spine="Intrusive Thought Reframe Ledger", kdp_title="Intrusive Thought Reframe Ledger",
     kdp_subtitle="Urge Meter, Thought Label & Therapist-Directed Bounce-Back (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.81, 0.83), ink=(0.17, 0.16, 0.21), panel=(0.94, 0.93, 0.95),
     mechanic="Urge meter 0-10, a thought label (obsession / worry / memory / thought-only), and a bounce-back written with your own therapist's direction — the ledger makes the loop visible, then follows the plan you already made.",
     howto=[("Meter", ["Rate the urge. The meter turns 'I can't stop' into a number."]),
            ("Label", ["Name the thought type. Labeling is noticing, not fighting."]),
            ("Bounce-back", ["Write the step your therapist directed. This book keeps the plan; it does not invent one."])],
     legend=[("0", "quiet"), ("5", "loud"), ("10", "looping")],
     daily="ledger", ledger_cols=["Urge 0-10", "Thought label", "Therapist direction", "Bounce-back"],
     bullets=["Urge meter 0-10", "Thought label — notice, don't fight", "Therapist-directed bounce-back", "Weekly loop count (not a scoreboard)"],
     keywords=["intrusive thoughts journal", "ocd tracker", "urge log", "reassurance loop diary", "therapy homework journal", "cbt thought record", "undated ocd planner"],
     bisac=["PSY022000", "SEL032000"], bisac_names=["PSYCHOLOGY / Psychopathology / Anxiety Disorders", "SELF-HELP / Journaling"],
     also=["94 Rejection Sensitivity Radar", "98 Panic Drill Log", "96 Flashback & Grounding"],
     hook="The thought loop gets louder when it is private. Intrusive Thought Reframe Ledger meters the urge, labels the thought, and follows the bounce-back your therapist already directed."),

dict(n="96", stem="96_Flashback_Grounding_Timeline", file_interior="96_Flashback_Grounding_Timeline_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  96",
     cover_title="Flashback &\nGrounding Timeline", cover_title_one="Flashback & Grounding Timeline",
     subtitle="Trigger blotter plus a 5-4-3-2-1\ngrounding field",
     spine="Flashback & Grounding Timeline", kdp_title="Flashback & Grounding Timeline",
     kdp_subtitle="Trigger Blotter & 5-4-3-2-1 Grounding Field (Undated, Trauma-Informed)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.80, 0.83), ink=(0.22, 0.16, 0.22), panel=(0.95, 0.92, 0.94),
     mechanic="A trigger blotter (time, what happened, how it felt) plus a structured 5-4-3-2-1 grounding field — see 5, hear 4, touch 3, smell 2, taste 1 — written into the page so it is available before the flashback.",
     howto=[("Blotter", ["Time, trigger, felt. The blotter is observation; it is not analysis."]),
            ("Grounding field", ["Write your 5-4-3-2-1 anchors. Preparatory grounding beats mid-freeze invention."]),
            ("Safety line", ["One line about what made you safe. No interpretation required."])],
     legend=[("5", "see"), ("4", "hear"), ("3", "touch"), ("2", "smell"), ("1", "taste")],
     daily="ground", ground_fields=["See (5)", "Hear (4)", "Touch (3)", "Smell (2)", "Taste (1)"],
     bullets=["Trigger blotter: time, trigger, felt", "5-4-3-2-1 grounding field, pre-written", "Safety line after the moment", "Trauma-informed, no analysis"],
     keywords=["flashback journal", "grounding technique workbook", "ptsd tracker", "trauma recovery diary", "5 4 3 2 1 grounding", "emotional flashback log", "undated trauma journal"],
     bisac=["PSY022000", "SEL032000"], bisac_names=["PSYCHOLOGY / Psychopathology / Anxiety Disorders", "SELF-HELP / Journaling"],
     also=["97 Dissociation Grounding Map", "98 Panic Drill Log", "95 Intrusive Thought Ledger"],
     hook="Grounding fails when you have to invent it mid-flashback. Flashback & Grounding Timeline pairs a trigger blotter with a pre-written 5-4-3-2-1 field so the anchors are ready before the moment."),

dict(n="97", stem="97_Dissociation_Grounding_Map", file_interior="97_Dissociation_Grounding_Map_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  97",
     cover_title="Dissociation\n& Grounding Map", cover_title_one="Dissociation & Grounding Map",
     subtitle="Present-ness gauge, fog scale,\nanchor menu and body check",
     spine="Dissociation & Grounding Map", kdp_title="Dissociation & Grounding Map",
     kdp_subtitle="Present-ness Gauge, Fog Scale, Anchor Menu & Body Check (Undated)",
     tagline="Sixty undated days  ·  6 × 9 in", days=60, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.82, 0.84), ink=(0.21, 0.17, 0.22), panel=(0.95, 0.93, 0.95),
     mechanic="A present-ness gauge (how here am I), a fog scale, an anchor menu you choose from (name, body, object, room), and a body check — dissociation is a distance, and distance is measurable.",
     howto=[("Gauge", ["How present do you feel, 0-10? Distance is data."]),
            ("Fog scale", ["Separate fog from distance. They are different numbers."]),
            ("Anchor menu", ["Pick from your menu, not a stranger's. Anchors are personal by design."])],
     legend=[("0", "gone"), ("5", "drifting"), ("10", "here")],
     daily="gauge", gauge_label="Presentness", gauge_max=10,
     quad_fields=["Fog 0-10", "Body check", "Anchor used", "Note"],
     bullets=["Present-ness gauge 0-10", "Fog scale, separate from distance", "Personal anchor menu", "Body check — feet, hands, breath"],
     keywords=["dissociation journal", "grounding workbook", "depersonalization tracker", "derealization diary", "presentness log", "trauma grounding journal", "undated dissociation planner"],
     bisac=["PSY022000", "SEL032000"], bisac_names=["PSYCHOLOGY / Psychopathology / Anxiety Disorders", "SELF-HELP / Journaling"],
     also=["96 Flashback & Grounding", "93 Sensory Overload Kit", "98 Panic Drill Log"],
     hook="Dissociation is a distance, not a fog. Dissociation & Grounding Map measures presentness, separates fog from distance, and keeps your own anchor menu close."),

dict(n="98", stem="98_Panic_Drill_Log", file_interior="98_Panic_Drill_Log_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  98",
     cover_title="Panic\nDrill Log", cover_title_one="Panic Drill Log",
     subtitle="Trigger, body signs, one slow action\nand an after-line",
     spine="Panic Drill Log", kdp_title="Panic Drill Log",
     kdp_subtitle="Trigger, Body Signs, One Slow Action & After-Line (Undated)",
     tagline="Sixty undated days  ·  6 × 9 in", days=60, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.83, 0.86), ink=(0.16, 0.19, 0.26), panel=(0.93, 0.94, 0.97),
     mechanic="A panic drill: trigger, the body signs (not the thoughts), one slow action, and an after-line — the record that separates a panic attack from a story about one.",
     howto=[("Body signs", ["Write what the body did: heart, breath, hands. Body signs are the true timeline."]),
            ("One slow action", ["Choose one: name five things, slow breath, cold water. One action, not a ritual."]),
            ("After-line", ["One line after it passed. The after-line is kindness; the log is data."])],
     legend=[("B", "body"), ("1", "one action"), ("A", "after")],
     daily="dial", dial_fields=["Trigger", "Body signs", "One slow action", "After-line"],
     bullets=["Trigger + body-sign timeline", "One slow action, chosen in advance", "After-line — kindness after data", "Weekly attack count (no scoreboard)"],
     keywords=["panic attack journal", "anxiety tracker", "panic log", "body signs diary", "coping plan journal", "anxiety workbook women", "undated panic planner"],
     bisac=["PSY022000", "SEL032000"], bisac_names=["PSYCHOLOGY / Psychopathology / Anxiety Disorders", "SELF-HELP / Journaling"],
     also=["97 Dissociation Grounding Map", "95 Intrusive Thought Ledger", "96 Flashback & Grounding"],
     hook="A panic attack is a body event wearing a story. Panic Drill Log records the body signs, prepares one slow action, and leaves an after-line of kindness when it passes."),

dict(n="99", stem="99_Depression_Energy_Gauge", file_interior="99_Depression_Energy_Gauge_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  99",
     cover_title="Depression\nEnergy Gauge", cover_title_one="Depression Energy Gauge",
     subtitle="Capacity vs motivation, smallest action\nand one light thing",
     spine="Depression Energy Gauge", kdp_title="Depression Energy Gauge",
     kdp_subtitle="Capacity vs Motivation, Smallest Action & One Light Thing (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.82, 0.83), ink=(0.15, 0.20, 0.21), panel=(0.93, 0.95, 0.95),
     mechanic="Two gauges that are usually confused: capacity (can I) and motivation (do I want) — plus the smallest possible action and one light thing. Depression lies about both gauges; this book records them separately.",
     howto=[("Two gauges", ["Capacity and motivation are different dials. Filling both tells the truth."]),
            ("Smallest action", ["One action small enough to be possible. The gauge never demands more."]),
            ("Light thing", ["One thing that was not terrible. The light thing is evidence, not optimism."])],
     legend=[("C", "capacity"), ("M", "motivation"), ("L", "light")],
     daily="gauge", gauge_label="Capacity", gauge_max=10,
     quad_fields=["Motivation 0-10", "Smallest action", "One light thing", "Note"],
     bullets=["Capacity and motivation gauges — separate", "Smallest possible action", "One light thing daily", "Weekly honest note, no positivity mandate"],
     keywords=["depression journal", "low energy tracker", "mental health journal", "capacity log", "motivation gauge", "depression recovery diary", "undated mood journal"],
     bisac=["PSY022000", "SEL032000"], bisac_names=["PSYCHOLOGY / Psychopathology / Anxiety Disorders", "SELF-HELP / Journaling"],
     also=["98 Panic Drill Log", "97 Dissociation Grounding Map", "94 Rejection Sensitivity Radar"],
     hook="Depression confuses two gauges: what you can do and what you want. Depression Energy Gauge records capacity and motivation separately, plus the smallest action that is actually possible."),

dict(n="100", stem="100_Pet_Loss_Grief_Ledger", file_interior="100_Pet_Loss_Grief_Ledger_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  100",
     cover_title="Pet Loss\nGrief Ledger", cover_title_one="Pet Loss Grief Ledger",
     subtitle="Memory pages, grief weather and\na kindness check — no stages",
     spine="Pet Loss Grief Ledger", kdp_title="Pet Loss Grief Ledger",
     kdp_subtitle="Memory Pages, Grief Weather & Kindness Check (No Stages, Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.81, 0.79), ink=(0.23, 0.16, 0.13), panel=(0.96, 0.93, 0.91),
     mechanic="Memory pages (what I remember, a good day) plus a grief-weather line (sun, rain, fog, storm) and a kindness check — grief is weather, and weather is allowed to change without stages.",
     howto=[("Memory cards", ["What you remember, one detail at a time. Details are the grief's shape."]),
            ("Weather line", ["One word for the day: sun, rain, fog, storm. Weather needs no explanation."]),
            ("Kindness check", ["What would be kind to me today? One line; no prescriptions."])],
     legend=[("☀", "sun"), ("🌧", "rain"), ("🌫", "fog"), ("⛈", "storm")],
     daily="cards", card_fields=["What I remember", "A good day", "Grief weather", "Kindness check"],
     bullets=["Memory pages — one detail at a time", "Grief weather: sun, rain, fog, storm", "Kindness check, no prescriptions", "No stages, no silver linings"],
     keywords=["pet loss journal", "pet grief diary", "dog loss notebook", "cat memorial journal", "grief memory book", "pet bereavement journal", "undated pet loss planner"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["101 Loss After Miscarriage", "102 Estrangement Ledger", "108 Care Partner's Long Goodbye"],
     hook="Grief after a pet is not small; it is just quiet. Pet Loss Grief Ledger holds memory pages, a weather line that changes without stages, and a kindness check."),

dict(n="101", stem="101_Loss_After_Miscarriage", file_interior="101_Loss_After_Miscarriage_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  101",
     cover_title="Loss After\nMiscarriage", cover_title_one="Loss After Miscarriage",
     subtitle="Gentle day page, what I remember\nand who I told",
     spine="Loss After Miscarriage", kdp_title="Loss After Miscarriage",
     kdp_subtitle="Gentle Day Page, What I Remember & Who I Told (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.85, 0.83, 0.84), ink=(0.24, 0.18, 0.22), panel=(0.96, 0.94, 0.95),
     mechanic="A gentle day page (how today felt, what I remember), who I told, and a small memory box — a place where the loss is allowed to be real without being a task.",
     howto=[("Gentle page", ["How today felt, four options: heavy, soft, numb, okay. All four are allowed."]),
            ("What I remember", ["One detail of what you carry. Details are allowed to be yours."]),
            ("Who I told", ["Names go in the box. Telling is a choice, and the box records it without pressure."])],
     legend=[("H", "heavy"), ("S", "soft"), ("N", "numb"), ("O", "okay")],
     daily="quad", quad_fields=["How today felt", "What I remember", "Someone I told", "Gentle thing"],
     bullets=["Four-feeling day page — all allowed", "What I remember, one detail", "Who I told — a record, not pressure", "Small memory box per week"],
     keywords=["miscarriage journal", "pregnancy loss diary", "infant loss journal", "baby loss memory book", "grief after miscarriage", "loss support journal", "undated miscarriage planner"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["100 Pet Loss Grief Ledger", "108 Care Partner's Long Goodbye", "103 Divorce & Rebuilding Map"],
     hook="A loss this private needs a page that doesn't demand progress. Loss After Miscarriage is a gentle day page, a detail you remember, and a box for who you told."),

dict(n="102", stem="102_Estrangement_Contact_Ledger", file_interior="102_Estrangement_Contact_Ledger_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  102",
     cover_title="Estrangement &\nContact Ledger", cover_title_one="Estrangement & Contact Ledger",
     subtitle="Contact decision, cost meter and\na boundary card",
     spine="Estrangement & Contact Ledger", kdp_title="Estrangement & Contact Ledger",
     kdp_subtitle="Contact Decision, Cost Meter & Boundary Card (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.83, 0.80), ink=(0.17, 0.21, 0.16), panel=(0.94, 0.95, 0.92),
     mechanic="A contact ledger: the decision, a cost meter (0-10), and a boundary card written once — estrangement is decided daily, and the ledger makes the decision yours instead of automatic.",
     howto=[("Decision", ["Today: contact, no contact, or maybe. The decision is yours each day."]),
            ("Cost meter", ["Cost the interaction before it happens. Cost is a fact, not guilt."]),
            ("Boundary card", ["Write the boundary once: what you will and won't discuss. The card holds when the moment doesn't."])],
     legend=[("Y", "contact"), ("N", "no"), ("?","maybe"), ("C", "cost")],
     daily="meter", meter_fields=["Decision Y/N/?", "Cost 0-10", "Boundary card", "What I need"],
     bullets=["Daily contact decision — yours", "Cost meter before interaction", "Boundary card written once", "Weekly check: what I need, no verdict"],
     keywords=["estrangement journal", "family estrangement diary", "boundary cost log", "family contact decision", "no contact workbook", "toxic family journal", "undated estrangement planner"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["103 Divorce & Rebuilding Map", "104 Sandwich Generation Log", "100 Pet Loss Grief Ledger"],
     hook="Estrangement is decided daily, not once. Estrangement & Contact Ledger records the decision, meters its cost, and holds a boundary card you write once."),

dict(n="103", stem="103_Divorce_Rebuilding_Map", file_interior="103_Divorce_Rebuilding_Map_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  103",
     cover_title="Divorce &\nRebuilding Map", cover_title_one="Divorce & Rebuilding Map",
     subtitle="Who I am, what I miss, what I want\nand one step — four rings",
     spine="Divorce & Rebuilding Map", kdp_title="Divorce & Rebuilding Map",
     kdp_subtitle="Identity Rings, What I Miss & One Step Forward (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.81, 0.81), ink=(0.20, 0.16, 0.16), panel=(0.95, 0.93, 0.93),
     mechanic="Four rings around the center: who I am now, what I miss, what I want, one step — the map that keeps a divorce from becoming a disappearance of identity.",
     howto=[("Four rings", ["Identity, grief, desire, action — four rings, one center. The center is yours."]),
            ("What I miss", ["Name it honestly. Missed things are real, not regressions."]),
            ("One step", ["One small step per ring per week. The map is a pace, not a plan."])],
     legend=[("A", "who I am"), ("M", "what I miss"), ("W", "what I want"), ("1", "one step")],
     daily="orbit", orbit_rings=["Who I am now", "What I miss", "What I want", "One step"],
     bullets=["Four-ring identity map", "Missed things named, not erased", "One small step per week", "Milestone check-ins, no 'moving on' clock"],
     keywords=["divorce journal", "divorce recovery workbook", "rebuilding life planner", "post divorce diary", "identity after divorce", "divorce support journal", "undated divorce recovery book"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["102 Estrangement Contact Ledger", "66 Reboot Orbit", "108 Care Partner's Long Goodbye"],
     hook="A divorce is a change of map, not a deletion of self. Divorce & Rebuilding Map holds four rings — who you are, what you miss, what you want, one step — around a center that stays yours."),

dict(n="104", stem="104_Sandwich_Generation_Bandwidth", file_interior="104_Sandwich_Generation_Bandwidth_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  104",
     cover_title="Sandwich\nGeneration Bandwidth", cover_title_one="Sandwich Generation Bandwidth",
     subtitle="Parent care, kid care, me and\nwhat got covered",
     spine="Sandwich Generation Bandwidth", kdp_title="Sandwich Generation Bandwidth",
     kdp_subtitle="Parent Care, Kid Care, Me & What Got Covered (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.84, 0.85), ink=(0.17, 0.21, 0.22), panel=(0.93, 0.95, 0.95),
     mechanic="A four-field daily log (parent care, kid care, me, what got covered) with a weekly bandwidth note — the sandwich generation's problem is invisibility, and this book makes the number of hats visible.",
     howto=[("Four fields", ["Parent care, kid care, me, covered. Filling all four is the inventory."]),
            ("Bandwidth note", ["One line on what was squeezed. The note is the day's truth."]),
            ("Help line", ["Who helped, who I asked. Help lines make asking easier next time."])],
     legend=[("P", "parent"), ("K", "kid"), ("M", "me"), ("✓", "covered")],
     daily="quad", quad_fields=["Parent care", "Kid care", "Me", "Covered?"],
     bullets=["Four-field daily inventory", "Weekly bandwidth note", "Help line — who helped, who I asked", "Respite check, three lines"],
     keywords=["sandwich generation journal", "caregiver planner", "aging parent organizer", "multigenerational care diary", "family care coordinator", "caregiver burnout journal", "undated sandwich care planner"],
     bisac=["FAM014000", "SEL032000"], bisac_names=["FAMILY & RELATIONSHIPS / Caregiving", "SELF-HELP / Journaling"],
     also=["108 Care Partner's Long Goodbye", "107 Aging Strong Journal", "50 Caregiver Shift Log"],
     hook="The sandwich generation wears so many hats it forgets to count them. Sandwich Generation Bandwidth logs parent care, kid care, you, and what got covered — then checks the help line."),

dict(n="105", stem="105_ADHD_Meds_Appointments", file_interior="105_ADHD_Meds_Appointments_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  105",
     cover_title="ADHD Meds &\nAppointments", cover_title_one="ADHD Meds & Appointments",
     subtitle="As-directed tracker, appointment brief\nand refill gate",
     spine="ADHD Meds & Appointments", kdp_title="ADHD Meds & Appointments",
     kdp_subtitle="As-Directed Tracker, Appointment Brief & Refill Gate (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.85, 0.88), ink=(0.18, 0.20, 0.28), panel=(0.95, 0.95, 0.97),
     mechanic="A one-row-per-day medicine tracker (exactly as directed), an appointment brief, and a refill gate — the ADHD brain forgets the routine, so the routine lives on the page.",
     howto=[("As directed", ["Record exactly what your prescriber directed. No adjustments, no advice."]),
            ("Appointment brief", ["One page per appointment: what worked, what didn't, what to ask."]),
            ("Refill gate", ["A check-line on the last week. The gate is before the gap, not after."])],
     legend=[("✓", "taken"), ("·", "missed"), ("R", "refill")],
     daily="ledger", ledger_cols=["Time", "Meds (as directed)", "Appointment", "Note"],
     bullets=["As-directed daily tracker", "One-page appointment brief", "Refill gate on the last week", "Prescriber question list"],
     keywords=["adhd medication tracker", "adhd planner adults", "prescription log", "medication adherence journal", "adhd appointment book", "refill reminder journal", "undated adhd med planner"],
     bisac=["SEL032000", "HEA020000"], bisac_names=["SELF-HELP / Journaling", "HEALTH & FITNESS / Reference"],
     also=["91 ADHD Task Paralysis Planner", "106 Neurodivergent Routine Map", "61 ADHD Money Bandwidth"],
     hook="The ADHD brain forgets the routine, not the medicine. ADHD Meds & Appointments keeps an as-directed tracker, an appointment brief, and a refill gate on the page."),

dict(n="106", stem="106_Neurodivergent_Routine_Map", file_interior="106_Neurodivergent_Routine_Map_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  106",
     cover_title="Neurodivergent\nRoutine Map", cover_title_one="Neurodivergent Routine Map",
     subtitle="Before-during-after transition plan,\nthree-step ramp, flex note",
     spine="Neurodivergent Routine Map", kdp_title="Neurodivergent Routine Map",
     kdp_subtitle="Before-During-After Transition Plan, 3-Step Ramp & Flex Note (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.83, 0.86), ink=(0.18, 0.18, 0.25), panel=(0.94, 0.94, 0.97),
     mechanic="A transition plan for each routine (before / during / after) plus a three-step ramp and a flex note — transitions are where neurodivergent days break, and the map makes them routine.",
     howto=[("Before-during-after", ["Write each part of the routine across three phases. The break is usually the 'before'."]),
            ("Three-step ramp", ["Three tiny steps into the routine. Ramps beat willpower."]),
            ("Flex note", ["One line on what flex you need today. Flex is a plan, not a failure."])],
     legend=[("B", "before"), ("D", "during"), ("A", "after"), ("F", "flex")],
     daily="ladder", ladder_steps=["Transition: before", "During", "After", "Flex note"],
     bullets=["Before/during/after transition plan", "Three-step ramp into each routine", "Flex note — planned, not failed", "Weekly routine review"],
     keywords=["neurodivergent routine planner", "autism routine journal", "adhd transition map", "daily structure planner", "flexibility tracker", "routine reset journal", "undated routine planner"],
     bisac=["SEL032000", "PSY022000"], bisac_names=["SELF-HELP / Journaling", "PSYCHOLOGY / Psychopathology / Anxiety Disorders"],
     also=["91 ADHD Task Paralysis Planner", "92 Autistic Burnout Ledger", "93 Sensory Overload Kit"],
     hook="Transitions, not tasks, are where neurodivergent days break. Neurodivergent Routine Map plans before-during-after, builds a three-step ramp, and leaves a flex note by design."),

dict(n="107", stem="107_Aging_Strong_Journey", file_interior="107_Aging_Strong_Journey_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  107",
     cover_title="Aging Strong\nJourney", cover_title_one="Aging Strong Journey",
     subtitle="Mobility check, medicine list as directed\nand a home-safety note",
     spine="Aging Strong Journey", kdp_title="Aging Strong Journey",
     kdp_subtitle="Mobility Check, Medicine List As Directed & Home-Safety Note (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.85, 0.82, 0.78), ink=(0.25, 0.18, 0.12), panel=(0.96, 0.93, 0.90),
     mechanic="A daily strength index (balance, grip, stair) plus a medicine list entered as directed and a home-safety note — aging strong is measured in small capacities, and this book counts them without decline narratives.",
     howto=[("Strength index", ["Balance, grip, stairs — one number each. Capacities, not comparisons."]),
            ("Medicine list", ["Enter the list exactly as directed. The list is a record for the family, not advice."]),
            ("Home-safety note", ["What changed in the house: rugs, light, stairs. The note is practical, not fearful."])],
     legend=[("B", "balance"), ("G", "grip"), ("S", "stairs")],
     daily="meter", meter_fields=["Balance 0-10", "Grip 0-10", "Meds (as directed)", "Home note"],
     bullets=["Daily strength index: balance, grip, stairs", "Medicine list as directed", "Home-safety note", "Family brief — what to know"],
     keywords=["senior journal", "aging well planner", "balance tracker", "elderly care organizer", "medicine list book", "fall prevention journal", "undated aging strong book"],
     bisac=["HEA020000", "SEL032000"], bisac_names=["HEALTH & FITNESS / Reference", "SELF-HELP / Journaling"],
     also=["104 Sandwich Generation Bandwidth", "108 Care Partner's Long Goodbye", "50 Caregiver Shift Log"],
     hook="Aging strong is measured in small capacities, not decline. Aging Strong Journey tracks balance, grip, and stairs, keeps a medicine list as directed, and notes what changed at home."),

dict(n="108", stem="108_Care_Partner_Long_Goodbye", file_interior="108_Care_Partner_Long_Goodbye_interior.pdf",
     series=LIFE, series_short="LIFE RANGE  ·  108",
     cover_title="Care Partner's\nLong Goodbye", cover_title_one="Care Partner's Long Goodbye",
     subtitle="What happened today, what they said,\nwhat I need — gentle cards",
     spine="Care Partner's Long Goodbye", kdp_title="Care Partner's Long Goodbye",
     kdp_subtitle="What Happened, What They Said, What I Need & One Memory (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", days=90, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.80, 0.82), ink=(0.22, 0.16, 0.21), panel=(0.95, 0.92, 0.94),
     mechanic="Gentle cards for the long goodbye: what happened today, what they said, what I need, and one memory — the care partner carries two losses at once, and this book holds both.",
     howto=[("What happened", ["One card for the day's care. Facts hold the day together."]),
            ("What they said", ["Write what they said — even fragments. Fragments are the voice you keep."]),
            ("What I need", ["One card for you. The care partner's need is not optional."])],
     legend=[("D", "day"), ("V", "voice"), ("N", "need"), ("M", "memory")],
     daily="cards", card_fields=["What happened today", "What they said", "What I need", "One memory"],
     bullets=["Daily care card — what happened", "Voice card: what they said, even fragments", "Need card for the care partner", "Memory card, one per week"],
     keywords=["caregiver grief journal", "dementia caregiver diary", "long goodbye notebook", "end of life journal", "family care partner", "advanced care planning book", "undated caregiver memory journal"],
     bisac=["FAM014000", "SEL032000"], bisac_names=["FAMILY & RELATIONSHIPS / Caregiving", "SELF-HELP / Journaling"],
     also=["104 Sandwich Generation Bandwidth", "101 Loss After Miscarriage", "107 Aging Strong Journey"],
     hook="The long goodbye holds two losses: the one coming and the one already begun. Care Partner's Long Goodbye keeps daily cards, the voice you want to keep, and one card for you."),
]
