"""Range Band Press Volume 3 — Inner Range Series (titles 57-72). Candidate-only."""

INNER_RANGE = [

dict(n="57", stem="57_Shadow_Work_Doorways", file_interior="57_Shadow_Work_Doorways_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  57",
     cover_title="Shadow Work\nDoorways", cover_title_one="Shadow Work Doorways",
     subtitle="Twelve door cards, one letter back,\nand a weekly truce page",
     spine="Shadow Work Doorways", kdp_title="Shadow Work Doorways",
     kdp_subtitle="12 Door Cards, One Letter Back & a Weekly Truce Page (Undated)",
     tagline="Twelve undated doors  ·  6 × 9 in", pages=112, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.85, 0.82, 0.80), ink=(0.24, 0.18, 0.15), panel=(0.95, 0.93, 0.92),
     mechanic="Twelve door cards (Anger, Need, Shame, Control, Permission…): write what is behind the door, then a letter back from that part — a structure, not a vague prompt dump.",
     howto=[("Open a door", ["Choose a card. Write what is behind it — the part you usually don't look at."]),
            ("Letter back", ["Write from that part to you, honestly. One page max; the door stays open."]),
            ("Weekly truce", ["One sentence: what you and that part agreed on. Not a cure — a truce."])],
     legend=[("Door", "12 cards"), ("✉", "letter back")],
     daily="cards", days=84, card_fields=["Part", "What it wants", "What it fears", "Letter back (1 page)"],
     bullets=["12 shadow door cards — named parts, not vague prompts", "Letter-back page from each part", "Weekly truce line — agreement, not cure", "No guru voice; your own words only"],
     keywords=["shadow work journal", "shadow work prompts", "inner child workbook", "self discovery diary", "shadow cards journal", "journal for healing", "undated shadow work book"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["60 Inner Critic Courtroom", "58 Boundary Script Builder", "65 The Yes/No Ledger"],
     hook="Shadow work dies in vague prompts. Shadow Work Doorways gives you twelve named doors, a letter-back format, and a weekly truce line — structure for the part of you that usually stays dark."),

dict(n="58", stem="58_Boundary_Script_Builder", file_interior="58_Boundary_Script_Builder_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  58",
     cover_title="Boundary\nScript Builder", cover_title_one="Boundary Script Builder",
     subtitle="Fill-in scripts, rehearsal rating,\nand three doorways a week",
     spine="Boundary Script Builder", kdp_title="Boundary Script Builder",
     kdp_subtitle="Fill-In Scripts, Rehearsal Rating & Three Doorways a Week (Undated)",
     tagline="Twelve undated weeks  ·  6 × 9 in", pages=108, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.84, 0.82), ink=(0.18, 0.22, 0.18), panel=(0.93, 0.95, 0.93),
     mechanic="Script builder: four fill-in fields (This matters to me… When… I need… And here is what I can offer), a rehearsal star rating, then a doorway log of which script you actually used.",
     howto=[("Build the script", ["Four fields, one sentence each. A script is a sentence, not a speech."]),
            ("Rehearse", ["Rate 1-5 stars before you use it. Rehearsal is where 'say no' becomes sayable."]),
            ("Doorway log", ["Three boundary opportunities a week. Mark used / nearly / skipped — the log is the practice, not the proof."])],
     legend=[("★", "rehearsed"), ("✓", "used"), ("△", "nearly")],
     daily="script", days=84, script_fields=["This matters to me", "When you", "I need", "What I can offer"],
     bullets=["Four-field fill-in script builder", "Rehearsal star rating before use", "Three boundary doorways per week", "Weekly calm note — no scoreboard"],
     keywords=["boundaries workbook", "boundary script journal", "people pleasing recovery", "assertiveness planner", "relationship boundaries book", "how to say no journal", "undated boundary tracker"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["65 The Yes/No Ledger", "57 Shadow Work Doorways", "64 Repair Map"],
     hook="'Set a boundary' is not a sentence. Boundary Script Builder gives you four fill-in fields, a rehearsal star rating, and a doorway log — so the boundary is practiced before it is needed."),

dict(n="59", stem="59_Mens_Pressure_Valve", file_interior="59_Mens_Pressure_Valve_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  59",
     cover_title="The Pressure\nValve", cover_title_one="The Pressure Valve",
     subtitle="Five-minute neutral checks, weight log,\nand a garage protocol — no therapy speak",
     spine="The Pressure Valve", kdp_title="The Pressure Valve",
     kdp_subtitle="5-Minute Neutral Checks, Weight Log & a Garage Protocol (No Therapy Speak)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=112, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.82, 0.84), ink=(0.15, 0.18, 0.22), panel=(0.92, 0.94, 0.95),
     mechanic="One dial a day (pressure 0-10), three neutral fields (body, work, one good thing), and a garage protocol — a practical reset list with no jargon and no grading.",
     howto=[("One dial", ["Pressure 0-10. That's the whole check-in — no vocabulary exam."]),
            ("Three fields", ["Body (fuel, sleep, ache), work (one task), one good thing. Neutral by design."]),
            ("Garage protocol", ["If pressure is past 8: walk, lift, call, or fix one actual thing. Practical resets only."])],
     legend=[("0", "fine"), ("5", "loaded"), ("10", "redline")],
     daily="dial", days=90, dial_fields=["Pressure", "Body note", "Work note", "One good thing"],
     bullets=["One pressure dial a day, 0-10", "Three neutral fields — no therapy speak", "Garage protocol: walk, lift, call, fix one thing", "Weekly reset line for the hard weeks"],
     keywords=["men journal", "men mental health", "stress log for guys", "emotional check in men", "pressure valve journal", "mens wellness notebook", "undated mens journal"],
     bisac=["SEL032000", "PSY022000"], bisac_names=["SELF-HELP / Journaling", "PSYCHOLOGY / Psychopathology / Anxiety Disorders"],
     also=["60 Inner Critic Courtroom", "70 Social Battery Gauge", "57 Shadow Work Doorways"],
     hook="Men don't need more vocabulary; they need a valve. The Pressure Valve is one dial, three neutral fields, and a garage protocol — pressure checked in plain language, in five minutes."),

dict(n="60", stem="60_Inner_Critic_Courtroom", file_interior="60_Inner_Critic_Courtroom_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  60",
     cover_title="Inner Critic\nCourtroom", cover_title_one="Inner Critic Courtroom",
     subtitle="Evidence ledger vs feeling log\nwith a weekly verdict page",
     spine="Inner Critic Courtroom", kdp_title="Inner Critic Courtroom",
     kdp_subtitle="Evidence Ledger vs Feeling Log with a Weekly Verdict (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=110, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.82, 0.86), ink=(0.19, 0.16, 0.24), panel=(0.94, 0.93, 0.96),
     mechanic="Courtroom: left column 'what the critic says', middle 'evidence in the record', right 'what I actually did' — then a verdict page where the case is closed or adjourned.",
     howto=[("Three columns", ["Claim, evidence, action. The critic testifies; the record answers."]),
            ("Cross-examine", ["One question per page: 'What would I say if a friend did this?' Three short answers."]),
            ("Verdict", ["Guilty of being hard on yourself / not guilty / adjourned. A verdict, not a sentence."])],
     legend=[("C", "critic"), ("E", "evidence"), ("A", "action")],
     daily="court", days=90, court_cols=["The critic says", "Evidence in the record", "What I actually did"],
     bullets=["Claim / evidence / action three-column page", "One cross-exam question, three short answers", "Weekly verdict: guilty, not guilty, adjourned", "No affirmation fluff — just the record"],
     keywords=["inner critic journal", "self compassion workbook", "negative self talk log", "thought record journal", "self esteem tracker", "mindfulness cbt diary", "undated inner work journal"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["57 Shadow Work Doorways", "64 Repair Map", "68 The Done Ladder"],
     hook="The inner critic never cites evidence. Inner Critic Courtroom puts the claim, the record, and the action in three columns, then lets you deliver a verdict — not a self-flagellation session."),

dict(n="61", stem="61_ADHD_Money_Bandwidth", file_interior="61_ADHD_Money_Bandwidth_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  61",
     cover_title="ADHD Money\nBandwidth", cover_title_one="ADHD Money Bandwidth",
     subtitle="Decision-load meter, three-tier budget,\nand a paid-off-interest tracker",
     spine="ADHD Money Bandwidth", kdp_title="ADHD Money Bandwidth",
     kdp_subtitle="Decision-Load Meter, Three-Tier Budget & Interest Tracker (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=112, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.84, 0.86), ink=(0.16, 0.20, 0.26), panel=(0.93, 0.95, 0.96),
     mechanic="Money as bandwidth: a decision-load meter per money task, a three-tier budget (auto / one-look / big), and a paid-off-interest tracker that turns 'good enough' into a visible win.",
     howto=[("Meter first", ["Before any money task, rate decision load 0-10. If it is past 7, it is a one-look task, not a big one."]),
            ("Three tiers", ["Tier 1 auto, tier 2 one-look, tier 3 big decisions with a 24-hour gate. Budgeting stops being a moral test."]),
            ("Interest tracker", ["Log what you paid and what you avoided. Good-enough money beats perfect money you never do."])],
     legend=[("0", "auto"), ("5", "one-look"), ("10", "big")],
     daily="meter", days=90, meter_fields=["Decision load", "Tier 1/2/3", "One action (small)", "Money note"],
     bullets=["Decision-load meter before money tasks", "Three-tier budget: auto / one-look / big", "24-hour gate on big decisions", "Paid-off-interest tracker — visible wins"],
     keywords=["adhd finances planner", "adhd money journal", "decision fatigue book", "money tracker neurodivergent", "executive function budget", "low effort money planner", "undated adhd budget"],
     bisac=["BUS088000", "SEL032000"], bisac_names=["BUSINESS & ECONOMICS / Time Management", "SELF-HELP / Journaling"],
     also=["69 The Decision Diet", "68 The Done Ladder", "70 Social Battery Gauge"],
     hook="ADHD money fails at decisions, not math. ADHD Money Bandwidth rates decision load before every money task, splits the budget into three tiers, and tracks interest interest actually paid off."),

dict(n="62", stem="62_One_Room_Launch", file_interior="62_One_Room_Launch_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  62",
     cover_title="One Room\nLaunch", cover_title_one="One Room Launch",
     subtitle="Twenty-minute slices, attachment triage,\nand a done-anything board",
     spine="One Room Launch", kdp_title="One Room Launch",
     kdp_subtitle="20-Minute Slices, Attachment Triage & Done-Anything Board (Undated)",
     tagline="Sixty undated slices  ·  6 × 9 in", pages=112, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.83, 0.80), ink=(0.22, 0.18, 0.14), panel=(0.95, 0.94, 0.92),
     mechanic="One room, 20-minute slices: pick the slice, run the timer, triage each item (keep / keep-in-photo / give / drop), then check the done-anything board — progress without a mountain.",
     howto=[("Pick a slice", ["One room, one 20-minute slice: a drawer, a shelf, a corner. Small enough to actually start."]),
            ("Triage each item", ["Keep, photo-and-keep, give, drop. The photo option unlocks the hardest things — you can keep the memory without keeping the box."]),
            ("Done-anything board", ["Check one box per slice. The board is not a scoreboard; it is proof that a slice counts."])],
     legend=[("K", "keep"), ("P", "photo"), ("G", "give"), ("D", "drop")],
     daily="cards", days=60, card_fields=["Slice", "Timer 20 min", "Triage K/P/G/D", "Done-anything box"],
     bullets=["One 20-minute slice per spread", "Attachment triage: keep, photo, give, drop", "Done-anything board — a slice counts", "No room-scale plan; only the slice in front of you"],
     keywords=["declutter journal", "decluttering workbook", "room reset planner", "attachment triage", "20 minute tidy book", "let go journal", "undated declutter tracker"],
     bisac=["SEL032000", "BUS088000"], bisac_names=["SELF-HELP / Journaling", "BUSINESS & ECONOMICS / Time Management"],
     also=["61 ADHD Money Bandwidth", "68 The Done Ladder", "71 Time Capsule"],
     hook="A messy room is a mountain; a 20-minute slice is a step. One Room Launch runs the timer, triages each item (keep, photo, give, drop), and marks the done-anything board."),

dict(n="63", stem="63_Connection_Compass", file_interior="63_Connection_Compass_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  63",
     cover_title="The Connection\nCompass", cover_title_one="The Connection Compass",
     subtitle="Five-minute check-ins, a co-regulation ladder,\nand after-storm notes",
     spine="The Connection Compass", kdp_title="The Connection Compass",
     kdp_subtitle="5-Minute Check-Ins, Co-Regulation Ladder & After-Storm Notes (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=112, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.84, 0.88), ink=(0.18, 0.20, 0.28), panel=(0.94, 0.95, 0.97),
     mechanic="Compass for caregivers of neurodivergent kids: a 5-minute check-in (body, done, wanted, one hug), a co-regulation ladder (calm before words), and an after-storm note that ends the fight, not the day.",
     howto=[("Five minutes", ["Four lines, one answer each. Check-ins work when they are shorter than the resistance."]),
            ("Co-regulation ladder", ["Go down the ladder: lower your voice, sit, breathe, name the feeling. Calm first; words later."]),
            ("After-storm", ["One note when the storm passes: what helped, what to try, what to let go. The fight ends here."])],
     legend=[("○", "check-in"), ("▥", "ladder"), ("✎", "storm note")],
     daily="quad", days=90, quad_fields=["Body", "Done today", "Wanted", "One connection"],
     bullets=["Five-minute check-in — four lines max", "Co-regulation ladder: calm before words", "After-storm notes end the fight, not the day", "Weekly compass review for the grown-up"],
     keywords=["neurodivergent parent journal", "adhd parenting planner", "co regulation tools", "special needs parent diary", "connection check in book", "autistic child journal", "undated parenting tracker"],
     bisac=["SEL032000", "PSY022000"], bisac_names=["SELF-HELP / Journaling", "PSYCHOLOGY / Psychopathology / Anxiety Disorders"],
     also=["70 Social Battery Gauge", "57 Shadow Work Doorways", "64 Repair Map"],
     hook="You can't pour from a dysregulated cup. The Connection Compass gives you a five-minute check-in, a co-regulation ladder, and an after-storm note — connection, not perfection."),

dict(n="64", stem="64_Repair_Map", file_interior="64_Repair_Map_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  64",
     cover_title="Repair\nMap", cover_title_one="Repair Map",
     subtitle="Trigger → rupture → pause → repair bridge\nwith a weekly weather report",
     spine="Repair Map", kdp_title="Repair Map",
     kdp_subtitle="Trigger → Rupture → Pause → Repair Bridge & Weekly Weather Report (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=108, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.85, 0.82, 0.84), ink=(0.24, 0.16, 0.22), panel=(0.96, 0.93, 0.95),
     mechanic="Bridge: trigger (what happened), rupture (what you did), pause (the 10-minute rule), repair (one sentence to repair). Plus a weekly weather report for the relationship, not the market.",
     howto=[("Four spans", ["Trigger, rupture, pause, repair — four spans, one bridge. The pause is the span most people skip."]),
            ("Ten-minute rule", ["Where you stopped, write the pause you will take next time. A pause is a plan, not a punishment."]),
            ("Weather report", ["One word for the relationship's week: sunny, cloudy, storm, clearing. Weather is honest without being a fight."])],
     legend=[("T", "trigger"), ("R", "rupture"), ("P", "pause"), ("R", "repair")],
     daily="bridge", days=90, bridge_steps=["Trigger", "What I did", "Pause (10 min)", "Repair sentence"],
     bullets=["Four-span repair bridge per day", "Ten-minute pause plan after rupture", "Weekly relationship weather report", "Repair sentence bank for hard weeks"],
     keywords=["relationship repair journal", "couple conflict log", "repair conversation planner", "triggers tracker couples", "apology notebook", "conflict resolution diary", "undated relationship journal"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["58 Boundary Script Builder", "63 The Connection Compass", "65 The Yes/No Ledger"],
     hook="Fights are survivable; unfixed ruptures are not. Repair Map walks a four-span bridge — trigger, rupture, pause, repair — and ends each week with an honest weather report for the relationship."),

dict(n="65", stem="65_Yes_No_Ledger", file_interior="65_Yes_No_Ledger_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  65",
     cover_title="The Yes/No\nLedger", cover_title_one="The Yes/No Ledger",
     subtitle="One question per page, an energy cost\nmeter, and a lean-no box",
     spine="The Yes/No Ledger", kdp_title="The Yes/No Ledger",
     kdp_subtitle="One Ask per Page, Energy Cost Meter & Lean-No Box (Undated)",
     tagline="Ninety undated asks  ·  6 × 9 in", pages=108, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.83, 0.86), ink=(0.17, 0.20, 0.26), panel=(0.93, 0.94, 0.96),
     mechanic="One ask per page: the question, the energy cost 0-10, three reasons to say yes, and a lean-no box filled with a yes-that-feels-like-a-no — the ledger makes 'no' a decision, not a crisis.",
     howto=[("One page, one ask", ["Write the exact ask. One page per ask; the ledger is the discipline."]),
            ("Cost meter", ["Rate energy cost before you answer. Cost is a fact, not a weakness."]),
            ("Lean-no box", ["If you want to say no but feel yes, write the lean-no sentence anyway. The box practices honesty before the conversation."])],
     legend=[("0", "free"), ("5", "costs"), ("10", "too much")],
     daily="ledger", days=90, ledger_cols=["The ask", "Cost 0-10", "Reasons to say yes", "Lean-no? yes/no + sentence"],
     bullets=["One ask per page — nothing vague", "Energy cost meter before you answer", "Lean-no box: practice the sentence", "Weekly yes-rate — not a scoreboard, a mirror"],
     keywords=["no people pleaser journal", "energy ledger", "yes no workbook", "overcommitment tracker", "personal boundaries log", "energy cost journal", "undated assertiveness diary"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["58 Boundary Script Builder", "64 Repair Map", "70 Social Battery Gauge"],
     hook="Every yes has a cost and most of us pay in energy. The Yes/No Ledger puts one ask on a page, meters its cost, and gives you a lean-no box so 'no' becomes a decision, not a drama."),

dict(n="66", stem="66_Reboot_Orbit", file_interior="66_Reboot_Orbit_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  66",
     cover_title="Reboot\nOrbit", cover_title_one="Reboot Orbit",
     subtitle="Skills inventory, energy map,\nand a 90-day launch orbit",
     spine="Reboot Orbit", kdp_title="Reboot Orbit",
     kdp_subtitle="Skills Inventory, Energy Map & 90-Day Launch Orbit (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=116, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.85, 0.81), ink=(0.20, 0.23, 0.16), panel=(0.95, 0.96, 0.93),
     mechanic="Orbit: inventory skills in rings (have / want / transferable), map energy to work type, then launch a 90-day orbit with one weekly burn — change without the cliff.",
     howto=[("Skills inventory", ["Rings: what you have, what you want, what transfers. Orbit makes skills a map, not a resume."]),
            ("Energy map", ["Which work gives energy, which drains. The map is for planning, not nostalgia."]),
            ("90-day orbit", ["One launch action per week. The orbit is a path, not a leap; no quitting-the-job version."])],
     legend=[("★", "have"), ("◐", "want"), ("↗", "transferable")],
     daily="orbit", days=90, orbit_rings=["Skills have", "Skills want", "Transferable", "Week action"],
     bullets=["Skills inventory in three rings", "Energy map: gives vs drains", "90-day orbit — one action per week", "Milestone check-ins, not a CV rewrite"],
     keywords=["career change journal", "career pivot journal", "skills inventory workbook", "job transition diary", "career pivot notebook", "90 day career plan", "undated career journal"],
     bisac=["BUS088000", "SEL032000"], bisac_names=["BUSINESS & ECONOMICS / Time Management", "SELF-HELP / Journaling"],
     also=["61 ADHD Money Bandwidth", "68 The Done Ladder", "69 The Decision Diet"],
     hook="Changing careers is an orbit, not a cliff. Reboot Orbit inventories your skills in three rings, maps energy to work type, and launches a 90-day path with one action a week."),

dict(n="67", stem="67_Work_Before_Feeling", file_interior="67_Work_Before_Feeling_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  67",
     cover_title="Work Before\nFeeling", cover_title_one="Work Before Feeling",
     subtitle="Ten-minute draft timer, resistance log,\nand a show-up scoreboard",
     spine="Work Before Feeling", kdp_title="Work Before Feeling",
     kdp_subtitle="10-Minute Draft Timer, Resistance Log & Show-Up Scoreboard (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=108, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.85, 0.83), ink=(0.17, 0.23, 0.19), panel=(0.93, 0.95, 0.94),
     mechanic="Start before the feeling is right: ten-minute timer box, what you produced, then a resistance log (what said no today) and a show-up scoreboard — work, then meaning.",
     howto=[("Ten minutes", ["Set the timer, write anything. The box is for the draft, not the masterpiece."]),
            ("Resistance log", ["Name what said no today (the critic, tiredness, 'not ready'). Naming it shrinks it."]),
            ("Show-up board", ["One check per day you worked before feeling. Showing up is the method; feeling is the side effect."])],
     legend=[("10'", "timer"), ("✘", "resistance"), ("✓", "showed")],
     daily="cards", days=90, card_fields=["Draft (anything)", "Words produced", "Resistance said", "Show-up ✓"],
     bullets=["Ten-minute draft timer per day", "Resistance log — name what said no", "Show-up scoreboard, not a quality score", "Weekly note: what the draft became"],
     keywords=["creative block journal", "writing habit tracker", "resistance log book", "artist productivity journal", "10 minute writing timer", "show up daily", "undated creativity planner"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["68 The Done Ladder", "69 The Decision Diet", "70 Social Battery Gauge"],
     hook="Motivation is a symptom, not a prerequisite. Work Before Feeling runs a ten-minute draft timer, logs the resistance by name, and scores showing up — the work comes first, the feeling follows."),

dict(n="68", stem="68_Done_Ladder", file_interior="68_Done_Ladder_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  68",
     cover_title="The Done\nLadder", cover_title_one="The Done Ladder",
     subtitle="Versions not perfection: rung check-ins,\nsunk-cost notes, and a ship-it gate",
     spine="The Done Ladder", kdp_title="The Done Ladder",
     kdp_subtitle="Versions Not Perfection: Rung Check-Ins, Sunk-Cost Notes & Ship-It Gate (Undated)",
     tagline="Twelve undated projects  ·  6 × 9 in", pages=108, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.83, 0.85), ink=(0.19, 0.18, 0.24), panel=(0.94, 0.94, 0.96),
     mechanic="Done ladder: five rungs (v1 rough, v2 usable, v3 good, v4 better, v5 perfect-never), check what version you have, note sunk cost, then a ship-it gate when the rung is good enough.",
     howto=[("Name the version", ["Write where you are on the ladder. Version, not verdict."]),
            ("Sunk-cost note", ["One line on what you've spent and whether it still helps. The note is honesty, not an excuse."]),
            ("Ship-it gate", ["When v3 is good enough, sign the gate. A finished v3 beats a perfect v5 that never ships."])],
     legend=[("v1", "rough"), ("v3", "good"), ("v5", "never")],
     daily="ladder", days=90, ladder_steps=["Version (v1-v5)", "What's missing", "Sunk-cost note", "Ship-it gate? Y/N"],
     bullets=["Five-rung version ladder — no verdicts", "Sunk-cost note per project", "Ship-it gate when good enough", "Weekly 'shipped' log, not a wall of perfect"],
     keywords=["perfectionism workbook", "done is better journal", "version ladder book", "shipping diary", "sunk cost tracker", "good enough notebook", "undated anti perfection journal"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["67 Work Before Feeling", "69 The Decision Diet", "66 Reboot Orbit"],
     hook="A finished v3 beats a perfect v5 that never ships. The Done Ladder labels your version, checks the sunk cost, and gives you a ship-it gate — so done is a place, not a failure."),

dict(n="69", stem="69_Decision_Diet", file_interior="69_Decision_Diet_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  69",
     cover_title="The Decision\nDiet", cover_title_one="The Decision Diet",
     subtitle="Pre-decisions, veto cards,\nand a daily decision meter",
     spine="The Decision Diet", kdp_title="The Decision Diet",
     kdp_subtitle="Pre-Decisions, Veto Cards & Daily Decision Meter (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=108, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.82, 0.81), ink=(0.23, 0.17, 0.15), panel=(0.95, 0.93, 0.92),
     mechanic="Decision diet: pre-decide five things in the morning (meals, outfit, one priority), note rejections with a veto card (a pre-made no), and meter decisions spent each day.",
     howto=[("Pre-decide", ["Five slots before 9 a.m. Pre-decisions are decisions made while the tank is full."]),
            ("Veto cards", ["Write three things you will not decide today. A veto is a boundary, not a no."]),
            ("Decision meter", ["Count spent decisions. The meter is the diet's budget — spend it on what matters."])],
     legend=[("○", "pre"), ("✕", "veto"), ("0-10", "spent")],
     daily="meter", days=90, meter_fields=["Pre-decided (5)", "Veto cards", "Decisions spent", "One keep / one drop"],
     bullets=["Five pre-decisions before 9 a.m.", "Three veto cards — pre-made no's", "Daily decision meter, spend wisely", "Weekly 'one keep, one drop' review"],
     keywords=["decision fatigue planner", "decision journal", "pre decision card", "veto card workbook", "simplify choices book", "executive decision diary", "undated decisions tracker"],
     bisac=["SEL032000", "BUS088000"], bisac_names=["SELF-HELP / Journaling", "BUSINESS & ECONOMICS / Time Management"],
     also=["61 ADHD Money Bandwidth", "68 The Done Ladder", "62 One Room Launch"],
     hook="Willpower does not run out; decision budget does. The Decision Diet pre-decides five things, issues three veto cards, and meters what you spend so the tank lasts for what matters."),

dict(n="70", stem="70_Social_Battery_Gauge", file_interior="70_Social_Battery_Gauge_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  70",
     cover_title="Social Battery\nGauge", cover_title_one="Social Battery Gauge",
     subtitle="Charge level, recharge map,\nand a small-talk script wallet",
     spine="Social Battery Gauge", kdp_title="Social Battery Gauge",
     kdp_subtitle="Charge Level, Recharge Map & Small-Talk Script Wallet (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=108, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.83, 0.86), ink=(0.15, 0.20, 0.28), panel=(0.93, 0.95, 0.97),
     mechanic="Gauge before and after social time (charge 0-10), a recharge map (what actually recharges you, from a menu), and a script wallet of three small-talk exits.",
     howto=[("Two readings", ["Charge before and after. The gap is the data, not a personality flaw."]),
            ("Recharge map", ["Pick from the menu: silence, walk, book, headphones. What recharges is yours to define."]),
            ("Script wallet", ["Three exits written once: 'I have to go', 'I'm worn', 'rain check'. Exits are kindness, not rudeness."])],
     legend=[("0", "empty"), ("5", "half"), ("10", "full")],
     daily="gauge", days=90, gauge_label="Charge", gauge_max=10,
     bullets=["Charge before and after social time", "Recharge map — from a menu, yours to define", "Three script-wallet exits", "Weekly plan: preserve the charge"],
     keywords=["introvert journal", "social battery tracker", "small talk scripts", "energy recharge planner", "social fatigue diary", "recharge map book", "undated introvert planner"],
     bisac=["SEL032000", "PSY022000"], bisac_names=["SELF-HELP / Journaling", "PSYCHOLOGY / Psychopathology / Anxiety Disorders"],
     also=["63 The Connection Compass", "59 The Pressure Valve", "65 The Yes/No Ledger"],
     hook="Social energy is a battery, not a personality test. Social Battery Gauge reads charge before and after, maps what actually recharges you, and stocks three exit scripts in your wallet."),

dict(n="71", stem="71_Time_Capsule", file_interior="71_Time_Capsule_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  71",
     cover_title="Time\nCapsule", cover_title_one="Time Capsule",
     subtitle="Body-clock map, task-to-hour fits,\nand a weekly timey-feeling review",
     spine="Time Capsule", kdp_title="Time Capsule",
     kdp_subtitle="Body-Clock Map, Task-to-Hour Fits & Weekly Timey-Feeling Review (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=110, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.83, 0.85), ink=(0.17, 0.19, 0.25), panel=(0.93, 0.94, 0.96),
     mechanic="Body-clock wheel: mark your energy for each daypart, fit tasks to hours (deep 9-11, admin 2-4), then a weekly timey-feeling review — time blindness becomes a map.",
     howto=[("Body-clock wheel", ["Shade morning, midday, afternoon, night. Your clock is not the world's clock."]),
            ("Fit tasks", ["Deep work to peak hours, admin to low. Fit before you fill."]),
            ("Timey-feeling review", ["One line: when did time feel like it disappeared? The review is the teacher, not the shame."])],
     legend=[("▲", "peak"), ("■", "flat"), ("▼", "low")],
     daily="wheel", days=90, wheel_rings=["Morning", "Midday", "Afternoon", "Night"],
     bullets=["Body-clock wheel — your energy, your dayparts", "Task-to-hour fit before filling the day", "Weekly timey-feeling review", "Ghost-time log: where time went missing"],
     keywords=["time blindness journal", "time management planner adhd", "body clock tracker", "task timing diary", "productivity clock book", "time feeling journal", "undated time planner"],
     bisac=["SEL032000", "BUS088000"], bisac_names=["SELF-HELP / Journaling", "BUSINESS & ECONOMICS / Time Management"],
     also=["69 The Decision Diet", "61 ADHD Money Bandwidth", "67 Work Before Feeling"],
     hook="Time blindness is not laziness; it is a map you never drew. Time Capsule shades your body-clock wheel, fits tasks to the hours you actually have, and reviews the week with feeling, not shame."),

dict(n="72", stem="72_Empty_Nest_Compass", file_interior="72_Empty_Nest_Compass_6x9.pdf",
     series="INNER RANGE SERIES", series_short="INNER RANGE  ·  72",
     cover_title="The Empty Nest\nCompass", cover_title_one="The Empty Nest Compass",
     subtitle="Identity inventory, reconnection map,\nand a quiet-recipe grid",
     spine="The Empty Nest Compass", kdp_title="The Empty Nest Compass",
     kdp_subtitle="Identity Inventory, Reconnection Map & Quiet-Recipe Grid (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=110, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.82, 0.79), ink=(0.23, 0.18, 0.14), panel=(0.95, 0.93, 0.91),
     mechanic="Compass: identity inventory (before 'parent of' and after), a reconnection map (people, places, skills left behind), and a quiet-recipe grid of small weeks that are yours alone.",
     howto=[("Identity inventory", ["Two columns: who you were as a full-time parent, who you are now. Both are real; the compass holds them."]),
            ("Reconnection map", ["People, places, skills you set down. The map is for the next chapter, not the old one."]),
            ("Quiet-recipe grid", ["One week's worth of small recipes: a book, a walk, a class, a call. The nest is empty; the life is not."])],
     legend=[("A", "before"), ("B", "now"), ("↺", "reconnect")],
     daily="quad", days=90, quad_fields=["Who I was", "Who I am", "One reconnection", "One quiet recipe"],
     bullets=["Identity inventory: before and now", "Reconnection map — people, places, skills", "Quiet-recipe grid for one week", "Weekly compass note, no rush to 'move on'"],
     keywords=["empty nest journal", "empty nest gift", "midlife identity workbook", "reinvention diary", "second chapter planner", "after kids leave book", "undated empty nest journal"],
     bisac=["SEL032000", "SEL016000"], bisac_names=["SELF-HELP / Journaling", "SELF-HELP / Personal Growth / Happiness"],
     also=["66 Reboot Orbit", "58 Boundary Script Builder", "57 Shadow Work Doorways"],
     hook="The nest empties; the identity doesn't have to. The Empty Nest Compass inventories who you were and who you are now, maps what to reconnect with, and cooks up quiet recipes for the weeks that are yours alone."),
]
