"""Range Band Press Volume 3 — Chronic Care Series (titles 37-56).
Each product has a distinct CORE MECHANIC that solves the niche's actual problem.
Candidate-only. No upload. Catalog branches frozen; nothing here touches them.
"""

CHRONIC_CARE = [
dict(
    n="37", stem="37_PCOS_Cycle_Compass",
    file_interior="37_PCOS_Cycle_Compass_6x9.pdf",
    series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  37",
    cover_title="PCOS Cycle\n& Metabolism Compass", cover_title_one="PCOS Cycle & Metabolism Compass",
    subtitle="Cycle gear map, four daily quadrants,\nand a 90-day pattern ledger",
    spine="PCOS Cycle & Metabolism Compass",
    kdp_title="PCOS Cycle & Metabolism Compass",
    kdp_subtitle="Cycle Gear Map, Energy-Skin-Appetite Quadrants & 90-Day Pattern Ledger (Undated)",
    tagline="Ninety undated days  ·  6 × 9 in", pages=118, trim=(6.0, 9.0), paper="white", dark=False,
    bg=(0.80, 0.83, 0.88), ink=(0.16, 0.20, 0.28), panel=(0.93, 0.94, 0.96),
    mechanic="Cycle gear map: label each day G1-G4, then a four-quadrant daily page (energy / appetite / skin / mood) so pattern beats guesswork.",
    howto=[("The gear map", ["Pick the gear you are in before filling anything: G1 first days, G2 rising, G3 peak, G4 before bleed.",
                             "One gear box per day. The compass page at the end of each cycle turns four gears into a month shape."]),
           ("Four quadrants", ["Each quadrant is a 0-10 scale plus a short note. Do not chase perfect — only pattern."]),
           ("Pattern, not verdict", ["This book records. It never interprets, prescribes, or concludes. Bring it at your own pace."])],
    legend=[("G1", "quiet / low"), ("G2", "building"), ("G3", "full"), ("G4", "turning")],
    quad_fields=["Energy", "Appetite / craving", "Skin", "Mood"],
    daily="quad", days=90,
    bullets=["Cycle gear map — G1 to G4, one box a day", "Four daily quadrants: energy, appetite, skin, mood", "Monthly compass turn: gear weeks into a shape", "Clinic brief built from your own records"],
    keywords=["pcos journal", "pcos cycle tracker", "pcos symptom diary", "cycle gear tracker", "insulin resistance log", "pcos metabolism notebook", "undated hormone journal"],
    bisac=["HEA028000", "HEA019000"], bisac_names=["HEALTH & FITNESS / Women's Health", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
    also=["63 Connection Compass", "45 Gut-Brain Wire", "38 Endometriosis Pain Radar"],
    hook="A cycle is not a diagnosis on a chart; it is a gear you learn to read. PCOS Cycle & Metabolism Compass gives you a four-quadrant daily page and a monthly gear turn so the mess becomes a map."),

dict(
    n="38", stem="38_Endometriosis_Pain_Radar",
    file_interior="38_Endometriosis_Pain_Radar_6x9.pdf",
    series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  38",
    cover_title="Endometriosis\nPain Radar", cover_title_one="Endometriosis Pain Radar",
    subtitle="Ten-zone body heat map, flare constellations,\nand a monthly signature page",
    spine="Endometriosis Pain Radar",
    kdp_title="Endometriosis Pain Radar",
    kdp_subtitle="10-Zone Body Heat Map, Flare Constellation & Trigger Ledger (Undated)",
    tagline="Ninety undated days  ·  6 × 9 in", pages=116, trim=(6.0, 9.0), paper="white", dark=False,
    bg=(0.86, 0.81, 0.82), ink=(0.26, 0.16, 0.18), panel=(0.96, 0.93, 0.93),
    mechanic="10-zone body heat map shaded 0-3 daily, then a flare constellation (zone x day dots) that reveals the pattern — not a diary of complaints.",
    howto=[("Heat map", ["Shade every zone you felt today: 0 none, 1 mild, 2 steady, 3 loud. The body outline is on every page."]),
           ("Flare constellation", ["Each month the dots line up. The constellation is the thing you can actually show a clinician — sharper than words."]),
           ("Trigger ledger", ["Log only what you tried. No conclusions; the pattern is the point."])],
    legend=[("0", "none"), ("1", "mild"), ("2", "steady"), ("3", "loud")],
    quad_fields=["Pelvis", "Lower back", "Hip", "Thigh", "Belly", "Head"],  # used as map zones
    daily="map", days=90, zones=["Pelvis L", "Pelvis R", "Lower back", "Hip L", "Hip R", "Belly", "Thigh", "Head", "Shoulder", "Other"],
    bullets=["Ten-zone body heat map, shaded daily", "Flare constellation: zone × day dots per month", "Trigger ledger with a 'nothing obvious' option", "Monthly signature page for the clinic folder"],
    keywords=["endometriosis journal", "pelvic pain tracker", "endo symptom diary", "period pain log", "pelvic pain map", "flare tracker undated", "endo care journal"],
    bisac=["HEA009000", "HEA028000"], bisac_names=["HEALTH & FITNESS / Pain Management", "HEALTH & FITNESS / Women's Health"],
    also=["37 PCOS Cycle Compass", "55 Symptom Detective Kit", "46 Lupus & RA Joint Map"],
    hook="Words leak under pain. A body map does not. Endometriosis Pain Radar turns a flare into a 10-zone heat map and a monthly constellation a clinician can read in seconds."),

dict(
    n="39", stem="39_LongCovid_Energy_Ledger",
    file_interior="39_LongCovid_Energy_Ledger_6x9.pdf",
    series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  39",
    cover_title="Long COVID\nEnergy Ledger", cover_title_one="Long COVID Energy Ledger",
    subtitle="Battery budget, 70% guardrail,\nand crash triage pages",
    spine="Long COVID Energy Ledger",
    kdp_title="Long COVID Energy Ledger",
    kdp_subtitle="Battery Budget, 70% Pacing Guardrail & Crash Triage Pages (Undated)",
    tagline="Twelve undated weeks  ·  6 × 9 in", pages=118, trim=(6.0, 9.0), paper="white", dark=False,
    bg=(0.80, 0.86, 0.84), ink=(0.15, 0.24, 0.20), panel=(0.93, 0.95, 0.94),
    mechanic="Battery budget planned BEFORE the day: capacity units on top, then a 70% guardrail line, then post-crash triage pages with a stop-now checklist.",
    howto=[("Budget first", ["Fill your planned units before you spend them. The 70% guardrail is drawn on the page for you."]),
           ("Spend, then settle", ["At night record actual units. The gap is the lesson — no shaming, just data."]),
           ("Crash triage", ["If you are already past the guardrail, use the triage page: stop, hydrate, rest, tell someone. It is a map, not a lecture."])],
    legend=[("70%", "guardrail"), ("!", "crash triage"), ("0-10", "units")],
    quad_fields=["Planned units", "Actual units", "Quality 0-10", "Note"],
    daily="gauge", days=84, gauge_label="Battery", gauge_max=10,
    bullets=["Budget your battery before 8 a.m.", "70% pacing guardrail drawn on every page", "Crash triage pages: stop, hydrate, rest, tell someone", "Weekly capacity summary"],
    keywords=["long covid journal", "post viral fatigue tracker", "energy pacing log", "chronic fatigue diary", "battery budget journal", "crash prevention tracker", "long covid planner"],
    bisac=["HEA039000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"],
    also=["53 POTS Position Ledger", "55 Symptom Detective Kit", "54 Hypermobility Joint Guard"],
    hook="Pacing is easy to say and impossible to remember mid-crash. Long COVID Energy Ledger puts a battery budget and a 70% guardrail on the page before you spend a unit — and a triage page for when you already have."),
]
