"""Range Band Press Volume 3 — Chronic Care Series, titles 40-56. Candidate-only."""

_CHRONIC_REST = [

dict(n="40", stem="40_SleepApnea_NightShift_Gauge", file_interior="40_SleepApnea_NightShift_Gauge_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  40",
     cover_title="Sleep Apnea\nNight Shift Gauge", cover_title_one="Sleep Apnea Night Shift Gauge",
     subtitle="Mask hours, leak and event gauges\nwith a 30-night trend line",
     spine="Sleep Apnea Night Shift Gauge", kdp_title="Sleep Apnea Night Shift Gauge",
     kdp_subtitle="Mask Hours, Leak, Event & Morning-Fog Gauges with a 30-Night Trend (Undated)",
     tagline="Sixty undated nights  ·  6 × 9 in", pages=104, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.79, 0.83, 0.89), ink=(0.14, 0.20, 0.30), panel=(0.92, 0.94, 0.97),
     mechanic="Nightly gauge rings (mask hours, leak, events, morning fog) plus a 30-night trend line — therapy questions answered with one glance.",
     howto=[("Four rings", ["Score each ring 0-10 or tick the range box. Gauge reading is faster and truer than 'felt fine'."]),
            ("Morning fog", ["One honest number before coffee. The trend line takes the fog out of the week."]),
            ("No conclusions", ["Record what your device and body say. Clinicians read trend lines, not adjectives."])],
     legend=[("Mask", "hours on"), ("Leak", "rings"), ("Events", "rings"), ("Fog", "0-10")],
     daily="gauge2", days=60, gauge_fields=["Mask hours", "Leak", "Events", "Morning fog"],
     bullets=["Four nightly gauges: mask hours, leak, events, fog", "60-night trend line in one spread", "Morning routine field: water, light, no screens 20m", "Weekend reset check — no perfection, just pattern"],
     keywords=["sleep apnea journal", "cpap tracker log", "mask fit diary", "night shift sleep log", "morning fog tracker", "apnea symptoms notebook", "undated sleep therapy journal"],
     bisac=["HEA043000", "HEA039000"], bisac_names=["HEALTH & FITNESS / Sleep", "HEALTH & FITNESS / Diseases / General"],
     also=["52 Tinnitus Sound Ladder", "47 Cardiac Rhythm & BP Wave", "51 Vertigo Position Map"],
     hook="After 30 nights the trend line tells the story your memory cannot. Sleep Apnea Night Shift Gauge scores mask hours, leak, events, and morning fog every night, then draws the trend for you."),

dict(n="41", stem="41_T1D_Bolt_Log", file_interior="41_T1D_Bolt_Log_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  41",
     cover_title="Type 1 Diabetes\nBolt Log", cover_title_one="Type 1 Diabetes Bolt Log",
     subtitle="Carb, insulin and correction record —\nwrite what your clinician directed",
     spine="Type 1 Diabetes Bolt Log", kdp_title="Type 1 Diabetes Bolt Log",
     kdp_subtitle="Carb, Insulin & Corrections Record — Write What Your Clinician Directed (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=118, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.88, 0.84), ink=(0.15, 0.22, 0.18), panel=(0.94, 0.96, 0.94),
     mechanic="Bolt log: carb box, insulin box, correction box in one row, with a 'prescribed only' footer and a hypo-noted column — record, never advise.",
     howto=[("One row per entry", ["The bolt log puts carbs, insulin, and corrections side by side so the relationship shows itself. No advice is given — only columns."]),
            ("Prescribed only", ["Write exactly what your clinician directed. This book does not dose, correct, or suggest."]),
            ("Hypo notes", ["Use the flagged column for lows. Bring the whole row to clinic — it is sharper than recall."])],
     legend=[("Carb", "grams"), ("Ins", "as directed"), ("Corr", "as directed")],
     daily="ledger", days=90, ledger_cols=["Time", "Carbs", "Insulin (as directed)", "Correction", "Note"],
     bullets=["One-row bolt structure: time, carbs, insulin, correction, note", "Hypo flag column — no advice, just record", "Weekend pattern page and 4-week trend grid", "Clinic brief with 'what I noticed' — facts only"],
     keywords=["type 1 diabetes log", "carb counting journal", "insulin tracker book", "blood sugar diary", "diabetic carb log", "corrections record book", "t1d management notebook"],
     bisac=["HEA039020", "HEA019000"], bisac_names=["HEALTH & FITNESS / Diseases / Diabetes", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
     also=["55 Symptom Detective Kit", "45 Gut-Brain Wire", "47 Cardiac Rhythm & BP Wave"],
     hook="A row with carbs, insulin, and corrections side by side teaches more than a page of numbers. Type 1 Diabetes Bolt Log records what your clinician directed — no dosing advice, no app, just the pattern."),

dict(n="42", stem="42_Neuropathy_Nerve_Map", file_interior="42_Neuropathy_Nerve_Map_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  42",
     cover_title="Neuropathy\nNerve Map", cover_title_one="Neuropathy Nerve Map",
     subtitle="Dendrite symptom drawings, a touch-shock\nladder, and a weekly signal page",
     spine="Neuropathy Nerve Map", kdp_title="Neuropathy Nerve Map",
     kdp_subtitle="Dendrite Drawings, Touch-Shock Ladder & Weekly Signal Page (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=118, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.81, 0.87), ink=(0.22, 0.16, 0.28), panel=(0.95, 0.93, 0.96),
     mechanic="Daily dendrite drawing (arms/legs) plus a touch-shock ladder 0-10, so 'numb' and 'zing' become locations and numbers.",
     howto=[("Draw the dendrite", ["Mark each limb where you feel tingling, numbness, or shock. Draw the shape you feel — it changes with the week."]),
            ("Touch-shock ladder", ["One number per limb, daily. Ladders beat adjectives in clinic."]),
            ("Weekly signal", ["Sunday: circle what got louder and what got quiet. No interpretation — just signal."])],
     legend=[("o", "tingle"), ("x", "numb"), ("~", "shock")],
     daily="map", days=90, zones=["Feet L", "Feet R", "Shin L", "Shin R", "Hand L", "Hand R", "Fingers", "Other"],
     bullets=["Dendrite drawing: mark tingling, numbness, shock", "Touch-shock ladder 0-10 per limb", "Weekly signal page — louder vs quieter", "Clinic brief prepped from the map"],
     keywords=["neuropathy journal", "nerve pain tracker", "tingling log book", "peripheral neuropathy diary", "numb feet tracker", "nerve symptom map", "undated pain diary"],
     bisac=["HEA039050", "HEA009000"], bisac_names=["HEALTH & FITNESS / Diseases / Nervous System", "HEALTH & FITNESS / Pain Management"],
     also=["54 Hypermobility Joint Guard", "38 Endometriosis Pain Radar", "46 Lupus & RA Joint Map"],
     hook="'It's numb' is not data. Neuropathy Nerve Map makes you draw the dendrite and score the touch-shock ladder so the clinic sees a map, not a memory."),

dict(n="43", stem="43_Histamine_Bucket_Diary", file_interior="43_Histamine_Bucket_Diary_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  43",
     cover_title="Histamine\nBucket Diary", cover_title_one="Histamine Bucket Diary",
     subtitle="Visible 0-10 bucket fill, food-heat-stress\ntriad ticks, and a 30-day pattern",
     spine="Histamine Bucket Diary", kdp_title="Histamine Bucket Diary",
     kdp_subtitle="Bucket Fill 0-10, Food-Heat-Stress Triad & 30-Day Pattern (Undated)",
     tagline="Sixty undated days  ·  6 × 9 in", pages=104, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.87, 0.82, 0.78), ink=(0.26, 0.18, 0.14), panel=(0.96, 0.93, 0.91),
     mechanic="Visible bucket: fill segments 0-10 before bed, tick the food-heat-stress triad that day, then a 30-day pattern column that shows what actually filled it.",
     howto=[("Fill the bucket", ["Shade the bucket to your day. Filling is honest; guessing is the enemy."]),
            ("Tick the triad", ["Food, heat, stress, other — tick what you noticed. The pattern page counts, not you."]),
            ("Thirty-day pattern", ["The three columns at month's end are the conversation starter. This book draws no conclusions."])],
     legend=[("Food", "had"), ("Heat", "had"), ("Stress", "had"), ("Other", "had")],
     daily="bucket", days=60, triad=["Food", "Heat", "Stress", "Other"],
     bullets=["Fill the 0-10 bucket every evening", "Food / heat / stress / other triad ticks", "30-day pattern column — no conclusions", "Clinic brief with 'patterns I noticed'"],
     keywords=["histamine journal", "mcas tracker", "food intolerance diary", "histamine bucket log", "allergy symptom diary", "food reaction log", "undated intolerance journal"],
     bisac=["HEA039010", "HEA019000"], bisac_names=["HEALTH & FITNESS / Diseases / Gastrointestinal", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
     also=["44 Celiac Contamination Trail", "45 Gut-Brain Wire", "56 IBD Flare Timeline"],
     hook="One bucket, three ticks, thirty days. Histamine Bucket Diary makes the invisible visible — without a single diagnosis, dose, or diet mandate."),

dict(n="44", stem="44_Celiac_Contamination_Trail", file_interior="44_Celiac_Contamination_Trail_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  44",
     cover_title="Celiac\nContamination Trail", cover_title_one="Celiac Contamination Trail",
     subtitle="Cross-contact hunt, hidden-source checklist,\nand symptom-after grid",
     spine="Celiac Contamination Trail", kdp_title="Celiac Contamination Trail",
     kdp_subtitle="Cross-Contact Hunt, Hidden-Source Checklist & Symptom-After Grid (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=116, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.85, 0.83), ink=(0.16, 0.24, 0.20), panel=(0.93, 0.95, 0.94),
     mechanic="Contamination trail: trace each meal back through seven cross-contact nodes, tick a hidden-source checklist, then log symptom-after in a grid — hunt, don't assume.",
     howto=[("Seven nodes", ["Counter, utensils, toaster, fryer, condiment, cutting board, shared package. Tick the nodes you touched."]),
            ("Hidden-source list", ["Soups, sauces, oats, spice blends, deli slicers. The checklist keeps the hunt honest."]),
            ("Symptom-after grid", ["3 items max per day. Grid = pattern; pattern = better question at clinic."])],
     legend=[("node", "risk"), ("✓", "checked"), ("? ", "unsure")],
     daily="trail", days=90, trail_nodes=["Counter", "Utensils", "Toaster", "Fryer", "Condiment", "Board", "Shared jar"],
     bullets=["Seven-node cross-contact trail per day", "Hidden-source checklist: sauces, oats, spice blends", "Symptom-after grid — 3 items max", "Weekly trail score, no shame attached"],
     keywords=["celiac journal", "gluten cross contamination log", "coeliac diary", "hidden gluten checklist", "gut symptom tracker", "gluten free food log", "undated celiac planner"],
     bisac=["HEA039010", "HEA019000"], bisac_names=["HEALTH & FITNESS / Diseases / Gastrointestinal", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
     also=["43 Histamine Bucket Diary", "56 IBD Flare Timeline", "45 Gut-Brain Wire"],
     hook="Cross-contact hides in seven places. Celiac Contamination Trail turns each meal into a seven-node hunt and a symptom-after grid — evidence instead of anxiety."),

dict(n="45", stem="45_GutBrain_Wire", file_interior="45_GutBrain_Wire_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  45",
     cover_title="Gut-Brain\nWire", cover_title_one="Gut-Brain Wire",
     subtitle="Thirty-day stress-to-GI correlation grid\nwith a weekly wiring map",
     spine="Gut-Brain Wire", kdp_title="Gut-Brain Wire",
     kdp_subtitle="30-Day Stress-to-GI Correlation Grid & Weekly Wiring Map (Undated)",
     tagline="Sixty undated days  ·  6 × 9 in", pages=104, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.81, 0.84, 0.88), ink=(0.16, 0.20, 0.28), panel=(0.93, 0.95, 0.97),
     mechanic="Two numbers a day — stress 0-10 and GI 0-10 — plotted on one 30-day grid, then a weekly wiring map that joins the dots.",
     howto=[("Two numbers", ["Stress at breakfast, GI at dinner. Two scales, nothing else."]),
            ("The grid", ["Drop one dot per day. The 30-day grid is the correlation — no statistics needed."]),
            ("Wiring map", ["Each Sunday draw lines between stress and GI days. You will see the wires, not guess at them."])],
     legend=[("S", "stress"), ("G", "gut"), ("•", "day")],
     daily="wire", days=60, wire_rows=["Stress 0-10", "GI discomfort 0-10", "Food note (1 line)"],
     bullets=["Stress 0-10 and GI 0-10, one dot each day", "30-day correlation grid on one spread", "Weekly wiring map — join your own dots", "No diagnosis; only the relationship you can see"],
     keywords=["gut brain axis journal", "ibs symptom tracker", "stress gut diary", "stomach pain log", "gi correlation journal", "mind gut notebook", "undated ibs journal"],
     bisac=["HEA039010", "PSY022000"], bisac_names=["HEALTH & FITNESS / Diseases / Gastrointestinal", "PSYCHOLOGY / Psychopathology / Anxiety Disorders"],
     also=["43 Histamine Bucket Diary", "56 IBD Flare Timeline", "37 PCOS Cycle Compass"],
     hook="The gut and the brain share one wire. Gut-Brain Wire logs two numbers a day, draws a 30-day grid, and lets you see (not guess) what your stress does to your stomach."),

dict(n="46", stem="46_Lupus_RA_Joint_Map", file_interior="46_Lupus_RA_Joint_Map_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  46",
     cover_title="Lupus & RA\nJoint Map", cover_title_one="Lupus & RA Joint Map",
     subtitle="Two-sided joint heat map, dawn-stiffness\nclock, and a flare timeline",
     spine="Lupus & RA Joint Map", kdp_title="Lupus & RA Joint Map",
     kdp_subtitle="Two-Sided Joint Heat Map, Dawn-Stiffness Clock & Flare Timeline (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=120, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.81, 0.88), ink=(0.20, 0.16, 0.28), panel=(0.94, 0.93, 0.96),
     mechanic="Two-sided joint heat map (left/right) shaded 0-3, plus a dawn-stiffness clock (how long until you move well) and a flare timeline that shows burst shape.",
     howto=[("Joint map", ["Shade hands, wrists, elbows, shoulders, hips, knees, ankles 0-3. Two sides, one page — symmetry is information."]),
            ("Dawn clock", ["Tick how long stiffness lasted. Ten minutes versus three hours is the difference the clinic needs."]),
            ("Flare timeline", ["One bar per day for a month. The timeline is the burst; the notes are the echo."])],
     legend=[("0", "fine"), ("1", "achy"), ("2", "stiff"), ("3", "loud")],
     daily="map", days=90, zones=["Hand L", "Hand R", "Wrist L", "Wrist R", "Elbow L", "Elbow R", "Shoulder L", "Shoulder R", "Knee L", "Knee R", "Ankle L", "Ankle R"],
     bullets=["12-joint two-sided heat map, 0-3", "Dawn-stiffness clock on every page", "Flare timeline — burst shape, not adjectives", "Clinic brief: symmetry, duration, pattern"],
     keywords=["lupus journal", "rheumatoid arthritis tracker", "joint pain map", "morning stiffness log", "autoimmune flare diary", "inflammation tracker", "undated arthritis journal"],
     bisac=["HEA039000", "HEA009000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Pain Management"],
     also=["54 Hypermobility Joint Guard", "42 Neuropathy Nerve Map", "56 IBD Flare Timeline"],
     hook="Symmetry and stiffness are the two words clinics need. Lupus & RA Joint Map shades 12 joints on both sides, times your dawn stiffness, and draws the flare shape."),

dict(n="47", stem="47_Cardiac_BP_Wave", file_interior="47_Cardiac_BP_Wave_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  47",
     cover_title="Cardiac Rhythm\n& BP Wave", cover_title_one="Cardiac Rhythm & BP Wave",
     subtitle="Wave-strip blood pressure, pulse, and\nexertion windows with a 12-week trend",
     spine="Cardiac Rhythm & BP Wave", kdp_title="Cardiac Rhythm & BP Wave",
     kdp_subtitle="Wave-Strip BP, Pulse & Exertion Windows with a 12-Week Trend (Undated)",
     tagline="Twelve undated weeks  ·  6 × 9 in", pages=112, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.84, 0.87), ink=(0.16, 0.20, 0.28), panel=(0.93, 0.94, 0.96),
     mechanic="Wave strips: plot BP and pulse as connected waves (not separate numbers), mark exertion windows, and see the 12-week trend line in one place.",
     howto=[("Wave strips", ["Plot each reading as a point on the wave, not a standalone number. Waves show rhythm; numbers show instants."]),
            ("Exertion windows", ["Tick what you did and for how long. The window is context that numbers alone lose."]),
            ("Twelve-week trend", ["One line per week. The trend is for your clinician, not for you to interpret."])],
     legend=[("BP", "points"), ("Pulse", "points"), ("Win", "exertion")],
     daily="wave", days=84, wave_series=["BP systolic", "BP diastolic", "Pulse"],
     bullets=["Wave-strip plotting for BP and pulse", "Exertion window tick: what, how long, felt how", "12-week trend line on one page", "Medication record line — as prescribed only"],
     keywords=["blood pressure log book", "pulse tracker diary", "heart health journal", "bp record book", "exertion window tracker", "cardiac diary undated", "rhythm log"],
     bisac=["HEA007000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Heart", "HEALTH & FITNESS / Reference"],
     also=["39 Long COVID Energy Ledger", "53 POTS Position Ledger", "55 Symptom Detective Kit"],
     hook="A blood pressure number is a snapshot; a wave is a story. Cardiac Rhythm & BP Wave plots BP and pulse as connected lines, marks exertion windows, and hands your clinician a 12-week trend."),

dict(n="48", stem="48_Stroke_Recovery_Runway", file_interior="48_Stroke_Recovery_Runway_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  48",
     cover_title="Stroke Recovery\nRunway", cover_title_one="Stroke Recovery Runway",
     subtitle="Therapy homework, fatigue gates,\nand a milestone runway",
     spine="Stroke Recovery Runway", kdp_title="Stroke Recovery Runway",
     kdp_subtitle="Therapy Homework, Fatigue Gates & Milestone Runway (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=118, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.87, 0.83), ink=(0.18, 0.24, 0.18), panel=(0.94, 0.96, 0.94),
     mechanic="Runway: homework box per day, fatigue gates (green/yellow/red) to protect the work, milestones drawn on a runway rather than a scoreboard.",
     howto=[("Homework box", ["Write the therapist's assignment in your own words. One box, one task."]),
            ("Fatigue gates", ["Green: full effort. Yellow: half. Red: rest. Gates are for the runway, not for grading."]),
            ("Milestone runway", ["Lay milestones down the runway — distance, not speed. Every landed mile counts."])],
     legend=[("G", "go"), ("Y", "half"), ("R", "rest")],
     daily="ladder", days=90, ladder_steps=["Therapist task", "Effort done", "Fatigue gate G/Y/R", "One win (any size)"],
     bullets=["Therapy homework box per day", "Green / yellow / red fatigue gates", "Milestone runway — distance, not speed", "Family note line so caregivers can help"],
     keywords=["stroke recovery journal", "neuro rehab log", "therapy homework tracker", "brain injury diary", "fatigue gate planner", "stroke survivor notebook", "undated rehab journal"],
     bisac=["HEA039050", "HEA039000"], bisac_names=["HEALTH & FITNESS / Diseases / Nervous System", "HEALTH & FITNESS / Diseases / General"],
     also=["50 Caregiver Shift Log", "55 Symptom Detective Kit", "39 Long COVID Energy Ledger"],
     hook="Recovery is a runway, not a scoreboard. Stroke Recovery Runway records the homework, guards it with fatigue gates, and lays milestones you can actually land."),

dict(n="49", stem="49_Oncology_Treatment_Companion", file_interior="49_Oncology_Treatment_Companion_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  49",
     cover_title="Oncology\nTreatment Companion", cover_title_one="Oncology Treatment Companion",
     subtitle="Cycle wheel, side-effect meter, and\nappointment brief — records only",
     spine="Oncology Treatment Companion", kdp_title="Oncology Treatment Companion",
     kdp_subtitle="Cycle Wheel, Side-Effect Meter & Appointment Brief — Records Only, Not Treatment Advice",
     tagline="Six undated cycles  ·  6 × 9 in", pages=116, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.82, 0.86), ink=(0.16, 0.18, 0.26), panel=(0.92, 0.93, 0.95),
     mechanic="Cycle wheel (one ring per cycle day), a side-effect meter per symptom, and an appointment brief that turns 'I've been okay' into a one-page record.",
     howto=[("Cycle wheel", ["Fill today's rings on treatment days. The wheel shows where you are in the cycle — calm for you, useful at clinic."]),
            ("Side-effect meter", ["One bar per symptom, 0-10. Meters are kinder than memory and faster than explanation."]),
            ("Appointment brief", ["Use the one-page brief: what happened, what helped, what to ask. Records only — no treatment advice, ever."])],
     legend=[("D", "infusion"), ("~", "rest"), ("0-10", "meter")],
     daily="wheel", days=84, wheel_rings=["Energy", "Appetite", "Nausea scale", "Mood", "Sleep"],
     bullets=["Cycle wheel — one ring per treatment day", "Side-effect meter 0-10 per symptom", "One-page appointment brief", "Questions page: what to ask the team"],
     keywords=["chemo journal", "cancer treatment tracker", "oncology diary", "side effect log", "chemo cycle planner", "infusion day notebook", "treatment appointment book"],
     bisac=["HEA039000", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Reference"],
     also=["50 Caregiver Shift Log", "55 Symptom Detective Kit", "39 Long COVID Energy Ledger"],
     hook="'I've been okay' is not a record. Oncology Treatment Companion is a cycle wheel, a side-effect meter, and a one-page appointment brief — records only, never medical advice."),

dict(n="50", stem="50_Caregiver_Shift_Log", file_interior="50_Caregiver_Shift_Log_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  50",
     cover_title="Caregiver\nShift Log", cover_title_one="Caregiver Shift Log",
     subtitle="Medications given, handoff sheet,\nand a respite check — one page per shift",
     spine="Caregiver Shift Log", kdp_title="Caregiver Shift Log",
     kdp_subtitle="Medications Given, Handoff Sheet & Respite Check — One Page per Shift (Undated)",
     tagline="Sixty undated shifts  ·  6 × 9 in", pages=116, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.86, 0.84), ink=(0.17, 0.24, 0.20), panel=(0.94, 0.96, 0.95),
     mechanic="One page per shift: meds-given grid with time boxes, a handoff sheet the next caregiver can read in 60 seconds, and a three-line respite check for you.",
     howto=[("Meds grid", ["Time, medicine (as directed by the prescriber), given by, note. The grid is a record, not advice."]),
            ("Handoff sheet", ["Fill the lines the next shift needs: ate, slept, mood, changes, concerns. Handoffs are where care quietly breaks."]),
            ("Respite check", ["Three lines only. If you skip them for nine shifts, that is a signal — for you, not a failure."])],
     legend=[("T", "time"), ("✓", "given"), ("!", "flag")],
     daily="ledger", days=60, ledger_cols=["Time", "Medicine (as directed)", "Given by", "Note"],
     bullets=["Meds-given grid with time boxes", "60-second handoff sheet per shift", "Respite check — three lines for you", "Flag column for anything the team should see"],
     keywords=["caregiver log book", "medication administration record", "home caregiver planner", "handoff sheet notebook", "elderly care journal", "respite tracker", "undated caregiving diary"],
     bisac=["FAM014000", "HEA020000"], bisac_names=["FAMILY & RELATIONSHIPS / Caregiving", "HEALTH & FITNESS / Reference"],
     also=["49 Oncology Treatment Companion", "48 Stroke Recovery Runway", "55 Symptom Detective Kit"],
     hook="Care breaks at the handoff, not at the task. Caregiver Shift Log is one page per shift — meds grid, a 60-second handoff, and three lines of respite for the person doing the caring."),

dict(n="51", stem="51_Vertigo_Position_Map", file_interior="51_Vertigo_Position_Map_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  51",
     cover_title="Vertigo\nPosition Map", cover_title_one="Vertigo Position Map",
     subtitle="Trigger × position × duration constellation\nwith a weekly balance check",
     spine="Vertigo Position Map", kdp_title="Vertigo Position Map",
     kdp_subtitle="Trigger × Position × Duration Constellation & Weekly Balance Check (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=116, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.84, 0.88), ink=(0.15, 0.20, 0.28), panel=(0.92, 0.94, 0.97),
     mechanic="Position constellation: mark the trigger, the position, and the duration as three linked points — one page shows the geometry of a dizzy spell.",
     howto=[("Three points", ["Trigger (what you were doing), position (lying/sitting/standing/turning), duration (minutes). Three points make a constellation."]),
            ("Link them", ["Draw the line between them. The shape of the spell is the clue you keep losing to memory."]),
            ("Weekly balance check", ["One honest line: how safe did you feel? Not how perfect — how safe."])],
     legend=[("T", "trigger"), ("P", "position"), ("M", "minutes")],
     daily="map", days=90, zones=["Lying", "Sitting", "Standing", "Turning", "Walking", "Bending"],
     bullets=["Trigger × position × duration constellation", "Duration dots in minutes — the shape of the spell", "Weekly balance check, safety over perfection", "Clinic brief prepped from the constellation"],
     keywords=["vertigo diary", "dizziness tracker", "bppv journal", "balance log book", "positional vertigo tracker", "ear balance diary", "undated vertigo journal"],
     bisac=["HEA039050", "HEA020000"], bisac_names=["HEALTH & FITNESS / Diseases / Nervous System", "HEALTH & FITNESS / Reference"],
     also=["52 Tinnitus Sound Ladder", "42 Neuropathy Nerve Map", "47 Cardiac Rhythm & BP Wave"],
     hook="A dizzy spell is geometry you lose to memory. Vertigo Position Map links trigger, position, and duration into a constellation the clinic can read at a glance."),

dict(n="52", stem="52_Tinnitus_Sound_Ladder", file_interior="52_Tinnitus_Sound_Ladder_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  52",
     cover_title="Tinnitus\nSound Ladder", cover_title_one="Tinnitus Sound Ladder",
     subtitle="Loudness ladder, masking log,\nand a left-right ear check",
     spine="Tinnitus Sound Ladder", kdp_title="Tinnitus Sound Ladder",
     kdp_subtitle="Loudness Ladder, Masking Log & Ear-Picture Check (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=112, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.82, 0.84, 0.88), ink=(0.17, 0.20, 0.28), panel=(0.93, 0.94, 0.96),
     mechanic="Loudness ladder (0 = silent, 10 = all you hear) scored daily, a masking log (what you tried), and an ear-picture check left vs right.",
     howto=[("Ladder", ["One number per ear per day on the ladder. Ladders beats 'really loud'."]),
            ("Masking log", ["Note what you tried (sound, fan, silence, nothing). The log is for your audiologist, not a verdict."]),
            ("Ear-picture", ["Tick left, right, both, and the tone (ring / hiss / buzz). Picture + ladder = usable data."])],
     legend=[("0", "silent"), ("5", "noticeable"), ("10", "all you hear")],
     daily="ladder", days=90, ladder_steps=["Loudness L", "Loudness R", "Tone: ring/hiss/buzz", "Masking tried"],
     bullets=["Loudness ladder 0-10 per ear", "Masking log — sound, fan, silence, nothing", "Left / right / both + tone picture", "Weekend note: what made it quieter"],
     keywords=["tinnitus journal", "ringing ears diary", "hearing sound log", "loudness tracker", "tinnitus relief planner", "ear noise notebook", "undated tinnitus log"],
     bisac=["HEA039050", "HEA043000"], bisac_names=["HEALTH & FITNESS / Diseases / Nervous System", "HEALTH & FITNESS / Sleep"],
     also=["51 Vertigo Position Map", "40 Sleep Apnea Night Shift Gauge", "42 Neuropathy Nerve Map"],
     hook="A number beats 'it's loud again.' Tinnitus Sound Ladder scores loudness per ear, logs what you tried, and gives your audiologist a picture instead of a shrug."),

dict(n="53", stem="53_POTS_Position_Ledger", file_interior="53_POTS_Position_Ledger_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  53",
     cover_title="POTS\nPosition Ledger", cover_title_one="POTS Position Ledger",
     subtitle="Sitting-lying-standing heart-rate strips,\nsymptom spikes, and a hydration ring",
     spine="POTS Position Ledger", kdp_title="POTS Position Ledger",
     kdp_subtitle="Sitting-Lying-Standing HR Strips, Symptom Spikes & Hydration Ring (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=118, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.83, 0.82, 0.88), ink=(0.20, 0.16, 0.28), panel=(0.94, 0.93, 0.96),
     mechanic="Position strips: HR while lying, sitting, standing drawn as three linked strips, symptom spikes marked, and a daily hydration ring you shade.",
     howto=[("Three strips", ["Record only. Lying, sitting, standing — three short strips beside each other. The change is the signal."]),
            ("Spike dots", ["Mark symptom spikes on the strip. Dots + strips tell the clinic where the body disagrees with the posture."]),
            ("Hydration ring", ["Shade the ring in four quarters. Hydration is a record, never a prescription."])],
     legend=[("L", "lying"), ("S", "sitting"), ("T", "standing")],
     daily="wave", days=90, wave_series=["HR lying", "HR sitting", "HR standing"],
     bullets=["Three HR strips: lying, sitting, standing", "Symptom spike dots on the strip", "Hydration ring in four quarters", "Clinic brief with the strips, not adjectives"],
     keywords=["pots journal", "dysautonomia tracker", "heart rate position log", "standing hr diary", "postural hr notebook", "hydration tracker chronic", "undated pots planner"],
     bisac=["HEA039000", "HEA039050"], bisac_names=["HEALTH & FITNESS / Diseases / General", "HEALTH & FITNESS / Diseases / Nervous System"],
     also=["47 Cardiac Rhythm & BP Wave", "39 Long COVID Energy Ledger", "55 Symptom Detective Kit"],
     hook="POTS lives in the change between positions. POTS Position Ledger draws three HR strips — lying, sitting, standing — marks the spikes, and shades a daily hydration ring."),

dict(n="54", stem="54_Hypermobility_Joint_Guard", file_interior="54_Hypermobility_Joint_Guard_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  54",
     cover_title="Hypermobility\nJoint Guard", cover_title_one="Hypermobility Joint Guard",
     subtitle="Joint-by-joint wear log, flare shield,\nand safe-movement notes",
     spine="Hypermobility Joint Guard", kdp_title="Hypermobility Joint Guard",
     kdp_subtitle="Joint-By-Joint Wear Log, Flare Shield & Safe-Movement Notes (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=118, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.84, 0.85, 0.82), ink=(0.19, 0.22, 0.17), panel=(0.95, 0.95, 0.93),
     mechanic="Wear log per joint (0-3), a flare shield with overload gates (what load the joint took and how it answered), and movement notes — guard, don't guess.",
     howto=[("Wear log", ["One number per loaded joint. Wear is a meter, not a complaint."]),
            ("Flare shield", ["Load taken, how it answered, what helped. The shield turns 'I overdid it' into a record."]),
            ("Movement notes", ["Write what your own physio/therapist said to try. This book never prescribes movement."])],
     legend=[("0", "calm"), ("1", "sore"), ("2", "wobbly"), ("3", "loud")],
     daily="map", days=90, zones=["Shoulder L", "Shoulder R", "Elbow L", "Elbow R", "Wrist L", "Wrist R", "Hip L", "Hip R", "Knee L", "Knee R", "Ankle L", "Ankle R"],
     bullets=["Joint-by-joint wear log 0-3", "Flare shield: load, answer, what helped", "Movement notes from your own therapist", "Flag column for the clinic brief"],
     keywords=["hypermobility journal", "eds tracker", "joint pain diary", "hsd flare log", "joint instability tracker", "bendy body journal", "undated hypermobility log"],
     bisac=["HEA009000", "HEA039000"], bisac_names=["HEALTH & FITNESS / Pain Management", "HEALTH & FITNESS / Diseases / General"],
     also=["46 Lupus & RA Joint Map", "42 Neuropathy Nerve Map", "38 Endometriosis Pain Radar"],
     hook="Bendy bodies need a meter, not a warning. Hypermobility Joint Guard logs wear per joint, measures load against answer on a flare shield, and keeps your therapist's notes in one place."),

dict(n="55", stem="55_Symptom_Detective_Kit", file_interior="55_Symptom_Detective_Kit_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  55",
     cover_title="Symptom\nDetective Kit", cover_title_one="Symptom Detective Kit",
     subtitle="Evidence cards, hypothesis tests,\nand a timeline board — facts only",
     spine="Symptom Detective Kit", kdp_title="Symptom Detective Kit",
     kdp_subtitle="Evidence Cards, Hypothesis Tests & Timeline Board — Facts Only, No Conclusions",
     tagline="Twelve undated weeks  ·  6 × 9 in", pages=124, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.81, 0.84, 0.86), ink=(0.15, 0.20, 0.26), panel=(0.93, 0.95, 0.96),
     mechanic="Detective kit for the undiagnosed maze: an evidence card per symptom, a one-question hypothesis test (did X change Y?), and a timeline board where dates, not stories, line up.",
     howto=[("Evidence cards", ["One symptom per card: when, how long, what preceded, what followed. Facts, not theories."]),
            ("Hypothesis test", ["Choose ONE question: 'When I did X, Y went up/down/stayed.' The kit never answers it for you."]),
            ("Timeline board", ["Lay events on the board by date. The board is what you hand to the clinician — evidence without a verdict."])],
     legend=[("E", "evidence"), ("H", "hypothesis"), ("T", "timeline")],
     daily="cards", days=84, card_fields=["Symptom", "When", "Before", "After", "Did X change Y? Y/N"],
     bullets=["Evidence card per symptom — facts only", "One-question hypothesis test", "Timeline board: dates, not stories", "Clinic brief builder with a question list"],
     keywords=["symptom tracker journal", "undiagnosed illness diary", "health timeline log", "symptom evidence book", "doctors visit prep", "medical mystery journal", "chronic illness binder"],
     bisac=["HEA020000", "HEA039000"], bisac_names=["HEALTH & FITNESS / Reference", "HEALTH & FITNESS / Diseases / General"],
     also=["39 Long COVID Energy Ledger", "38 Endometriosis Pain Radar", "45 Gut-Brain Wire"],
     hook="When no one has a name yet, evidence is the only asset. Symptom Detective Kit gives you evidence cards, one-question hypothesis tests, and a timeline board — facts only, no conclusions."),

dict(n="56", stem="56_IBD_Flare_Timeline", file_interior="56_IBD_Flare_Timeline_6x9.pdf",
     series="CHRONIC CARE SERIES", series_short="CHRONIC CARE  ·  56",
     cover_title="IBD Flare\nTimeline & Medicine Ledger", cover_title_one="IBD Flare Timeline & Medicine Ledger",
     subtitle="Severity timeline, Bristol rows, and a\nmedicine log — as prescribed, no advice",
     spine="IBD Flare Timeline & Medicine Ledger", kdp_title="IBD Flare Timeline & Medicine Ledger",
     kdp_subtitle="Severity Timeline, Bristol Rows & Medicine Log — As Prescribed, No Advice (Undated)",
     tagline="Ninety undated days  ·  6 × 9 in", pages=116, trim=(6.0, 9.0), paper="white", dark=False,
     bg=(0.80, 0.83, 0.84), ink=(0.15, 0.20, 0.22), panel=(0.93, 0.94, 0.95),
     mechanic="Flare timeline (severity bars per day), Bristol shorthand rows, and a medicine ledger with an 'as prescribed' footer — the flare gets a shape; the ledger stays factual.",
     howto=[("Severity bars", ["One bar per day, 0-10. The timeline is the flare's shape, not your mood."]),
            ("Bristol rows", ["Tick the Bristol shorthand row, and note ease. Rows beat adjectives in clinic."]),
            ("Medicine ledger", ["Record exactly what your clinician prescribed. This book never doses, adjusts, or advises."])],
     legend=[("0", "ok"), ("5", "active"), ("10", "worst")],
     daily="hist", days=90, hist_rows=["Severity bar", "Bristol row 1-7", "Ease 0-3", "Medicine (as directed)"],
     bullets=["Daily severity bar — flare shape, not mood", "Bristol shorthand row + ease scale", "Medicine ledger, as prescribed only", "Weekend pattern page for the clinic"],
     keywords=["ibd journal", "crohns tracker", "ulcerative colitis diary", "flare timeline log", "bowel severity chart", "medicine record book", "undated ibd planner"],
     bisac=["HEA039010", "HEA019000"], bisac_names=["HEALTH & FITNESS / Diseases / Gastrointestinal", "HEALTH & FITNESS / Diet & Nutrition / Nutrition"],
     also=["44 Celiac Contamination Trail", "45 Gut-Brain Wire", "43 Histamine Bucket Diary"],
     hook="A flare has a shape; a diary has a mood. IBD Flare Timeline draws the severity bars, keeps Bristol rows honest, and records medicine exactly as your clinician prescribed — never as advice."),
]

CHRONIC_REST = _CHRONIC_REST
